/* Generated by rccars_re/gen_ai_data.py -- do not edit.
 *
 * The AI opponents' roster and the constants behind the one number the
 * game decides for them at runtime: how fast to walk their recorded
 * path. See ai.h for the model and gen_ai_data.py for every source.
 */
#ifndef AI_DATA_H
#define AI_DATA_H

#include "rb.h"

#define AI_MAX_OPPONENTS 5
#define AI_N_RACES 10
#define AI_N_PLAYERS 7

/* ailayouts.ini's own #defines for AI<n>Races. */
#define AI_RACE_EASY    1
#define AI_RACE_NORMAL  2
#define AI_RACE_HARD    4

/* The seven drivers, ailayouts.ini "AIPlayer<n>". `car` is the model
   they are pictured with in the shop; the model they actually race is
   the opponent entry's own `car`, and the two DISAGREE (AIPlayer3 DOC
   is an Overkill and drives a Hummer on Fishers). The profile carries a
   third copy, and pack_ai.py checks it against the roster. */
typedef struct { const char *name; int car, skin; const char *face; } ai_player;
static const ai_player AI_PLAYERS[AI_N_PLAYERS] = {
    { "MCJocker", 1, 2, "MCJocker.tga" },
    { "MaxXMad", 2, 1, "MaxXMad.tga" },
    { "Doc", 0, 3, "Doc.tga" },
    { "BabyShark", 1, 1, "BabyShark.tga" },
    { "Rosy", 0, 1, "Daisy.tga" },
    { "Dakilla", 2, 2, "Dakilla.tga" },
    { "Johny", 0, 2, "Johny.tga" },
};

typedef struct {
    int ref;                /* 1..AI_N_PLAYERS, AI<n>Ref */
    int car;                /* 0 Overkill, 1 Buggy, 2 Hummer */
    int races;              /* AI_RACE_* mask, AI<n>Races */
    int boost, reson, tires;/* upgrade levels 0..3 */
    const char *path;       /* AI<n>Path, as authored */
} ai_opponent;

typedef struct {
    const char *track;      /* the port's own assets/<base> name */
    const char *dir;        /* the CarProfiles subdirectory */
    int   race;             /* the AIRace<n> number, for provenance */
    float coeff_common;     /* CoeffCommonOpponents */
    int   n;
    ai_opponent op[AI_MAX_OPPONENTS];
} ai_race;

/* Indexed the same as tracks.h's TRACKS[]. */
static const ai_race AI_RACES[AI_N_RACES] = {
    { "beach_1", "surf", 1, 0.850000f, 5, {
        { 3, 0, 4, 0, 1, 0, "surf/over1" },
        { 4, 1, 7, 0, 0, 1, "surf/buggy1" },
        { 5, 0, 6, 0, 0, 0, "surf/over2" },
        { 6, 2, 7, 0, 0, 0, "surf/hummer1" },
        { 7, 0, 7, 0, 0, 0, "surf/over3" },
    } },
    { "beach_2", "Camping", 6, 0.950000f, 5, {
        { 4, 1, 4, 1, 1, 2, "Camping/buggy1" },
        { 5, 0, 6, 1, 0, 1, "Camping/over1" },
        { 1, 1, 7, 0, 3, 1, "Camping/buggy2" },
        { 3, 0, 7, 0, 2, 2, "Camping/over2" },
        { 6, 2, 7, 1, 0, 1, "Camping/hummer1" },
    } },
    { "beach_3", "fort", 3, 0.900000f, 5, {
        { 1, 1, 4, 1, 0, 1, "Fort/buggy1" },
        { 2, 2, 7, 0, 2, 0, "Fort/hummer1" },
        { 5, 0, 6, 1, 0, 0, "Fort/over1" },
        { 4, 1, 7, 0, 2, 1, "Fort/buggy2" },
        { 7, 0, 7, 0, 0, 0, "Fort/over2" },
    } },
    { "beach_4", "Nuclear", 10, 1.070000f, 5, {
        { 1, 1, 6, 1, 3, 2, "Nuclear/buggy1" },
        { 3, 0, 4, 1, 3, 3, "Nuclear/over1" },
        { 4, 1, 7, 3, 0, 2, "Nuclear/buggy2" },
        { 2, 2, 7, 0, 3, 3, "Nuclear/hummer1" },
        { 5, 0, 7, 2, 0, 1, "Nuclear/over2" },
    } },
    { "country_1", "Rancho", 8, 1.000000f, 5, {
        { 2, 2, 6, 0, 3, 1, "Rancho/hummer1" },
        { 3, 0, 4, 0, 3, 2, "Rancho/over1" },
        { 6, 2, 7, 1, 0, 1, "Rancho/hummer2" },
        { 1, 1, 7, 1, 3, 1, "Rancho/buggy1" },
        { 5, 0, 7, 2, 0, 1, "Rancho/over2" },
    } },
    { "country_2", "mines", 5, 0.850000f, 5, {
        { 2, 2, 6, 0, 2, 1, "Mines/hummer1" },
        { 3, 0, 4, 0, 2, 2, "Mines/over1" },
        { 6, 2, 7, 1, 0, 0, "Mines/hummer2" },
        { 5, 0, 7, 1, 0, 1, "Mines/over2" },
        { 4, 1, 7, 1, 1, 2, "Mines/buggy1" },
    } },
    { "country_3", "fishers", 2, 0.850000f, 5, {
        { 2, 2, 4, 0, 1, 0, "fishers/hummer1" },
        { 3, 0, 6, 0, 1, 1, "fishers/over1" },
        { 4, 1, 7, 1, 0, 1, "fishers/buggy1" },
        { 6, 2, 7, 0, 0, 0, "fishers/hummer2" },
        { 5, 0, 7, 1, 0, 0, "fishers/over2" },
    } },
    { "country_4", "Silo", 9, 1.060000f, 5, {
        { 3, 0, 6, 0, 3, 3, "Silo/over1" },
        { 2, 2, 4, 0, 3, 2, "Silo/hummer1" },
        { 5, 0, 7, 2, 0, 1, "Silo/over2" },
        { 4, 1, 7, 3, 0, 2, "Silo/buggy1" },
        { 6, 2, 7, 2, 0, 2, "Silo/hummer2" },
    } },
    { "urban_1", "avax", 7, 0.970000f, 5, {
        { 1, 1, 4, 0, 3, 1, "Avax/buggy1" },
        { 3, 0, 6, 0, 2, 2, "Avax/over1" },
        { 4, 1, 7, 2, 0, 2, "Avax/buggy2" },
        { 2, 2, 7, 0, 3, 1, "Avax/hummer1" },
        { 7, 0, 7, 1, 0, 0, "Avax/over2" },
    } },
    { "urban_2", "AAD", 4, 0.900000f, 5, {
        { 1, 1, 4, 0, 2, 1, "AAD/buggy1" },
        { 3, 0, 6, 0, 2, 1, "AAD/over1" },
        { 4, 1, 7, 1, 1, 2, "AAD/buggy2" },
        { 6, 2, 7, 1, 0, 0, "AAD/hummer1" },
        { 7, 0, 7, 0, 0, 0, "AAD/over2" },
    } },
};

/* Scripts/aiCommonCoeffs.ini, selected by difficulty 0..3 -- and only
   in the championship (FUN_004f11b0 gates on FUN_004a4ca0() == 1). */
static const float AI_DIFFICULTY[4] = { 0.920000f, 1.000000f, 1.070000f, 1.150000f };

/* FUN_004fd4c0 clamps the product of the difficulty and the track
   coefficient into this band and logs "CAR: coeff for AI is
   unacceptable" when it has to. The shipped data never trips it:
   the widest product is 1.2305. */
#define AI_COEFF_MIN 0.5f
#define AI_COEFF_MAX 2.0f

/* Splines/FuncWaitAccel<n>.bspl -- signed metres of lead over the
   player, in, speed multiplier out. Negative means the opponent is
   behind and the curve returns more than 1. */
static const rb_curve_pt ai_fwa1[] = { {-40.000000f,1.100000f}, {-5.000000f,1.000000f}, {10.000000f,1.000000f}, {45.000000f,0.800000f} };
static const rb_curve_pt ai_fwa2[] = { {-40.000000f,1.100000f}, {-5.000000f,1.000000f}, {10.000000f,0.900000f}, {35.000000f,0.800000f} };
static const rb_curve_pt ai_fwa3[] = { {-39.827572f,1.124107f}, {-5.000000f,1.000000f}, {10.000000f,0.900000f}, {40.120975f,0.742998f} };
static const rb_curve_pt ai_fwa4[] = { {-39.817688f,1.164706f}, {-9.877256f,1.035000f}, {10.000000f,0.900000f}, {35.000000f,0.700000f} };
static const rb_curve_pt ai_fwa5[] = { {-50.000000f,1.200000f}, {-19.718655f,1.047740f}, {10.000000f,0.900000f}, {30.000000f,0.600000f} };
static const rb_curve_pt ai_fwa1_a[] = { {-39.827572f,1.057096f}, {-10.000000f,1.000000f}, {10.193834f,0.926667f}, {44.826370f,0.635119f} };
static const rb_curve_pt ai_fwa2_a[] = { {-39.608486f,1.057096f}, {-5.000000f,1.000000f}, {10.000000f,0.900000f}, {35.495220f,0.648036f} };
static const rb_curve_pt ai_fwa3_a[] = { {-40.000000f,1.100000f}, {-5.000000f,1.000000f}, {10.000000f,0.900000f}, {27.686272f,0.652342f} };
static const rb_curve_pt ai_fwa4_a[] = { {-40.000000f,1.100000f}, {-10.167304f,1.045588f}, {10.000000f,0.900000f}, {22.953575f,0.650189f} };
static const rb_curve_pt ai_fwa5_a[] = { {-50.000000f,1.200000f}, {-24.648010f,1.056177f}, {8.518853f,0.869790f}, {20.000000f,0.600000f} };

/* Index 0..4 is the opponent's own slot. FUN_004fd6b0 takes AI_FWA when
   the game mode is 5 and AI_FWA_A otherwise, so the CHAMPIONSHIP (mode
   1) races against the _A family. The two differ in both directions and
   neither is simply harder: _A slows a LEADING opponent much further
   (0.635 against 0.800 at +45 m on slot 0) and lets a TRAILING one
   catch up less (1.057 against 1.100 at -40 m). It is a tighter band
   around the player, which is what a championship with its own
   difficulty multiplier wants. */
static const rb_curve AI_FWA[5] = {
    { ai_fwa1, 4 },
    { ai_fwa2, 4 },
    { ai_fwa3, 4 },
    { ai_fwa4, 4 },
    { ai_fwa5, 4 },
};
static const rb_curve AI_FWA_A[5] = {
    { ai_fwa1_a, 4 },
    { ai_fwa2_a, 4 },
    { ai_fwa3_a, 4 },
    { ai_fwa4_a, 4 },
    { ai_fwa5_a, 4 },
};

/* Scripts/aiShiftsFuncWaitAccel.ini. FUN_004fd5e0 subtracts
   AI_FRONT_SHIFTS[gap] from the lead when the PLAYER is `gap`+2
   checkpoints ahead, gap clamped to 9 -- i.e. a player who is lapping
   the field stops pulling it along. AI_REAR_SHIFTS is loaded by the
   engine and never read back; it is here because it is data. */
static const float AI_FRONT_SHIFTS[10] = { 5.0f, 5.0f, 5.0f, 5.0f, 5.0f, 5.0f, 60.0f, 100.0f, 110.0f, 120.0f };
static const float AI_REAR_SHIFTS[10] = { 5.0f, 5.0f, 5.0f, 5.0f, 5.0f, 5.0f, 5.0f, 5.0f, 5.0f, 120.0f };  /* unread */

/* Settings/OpponentBehav.ini, through the .ini defaults -- the .crs
   carries none of these keys. FUN_004fd6b0 overwrites the three table
   entries FUN_00471a70 actually reads, so none of them reaches a
   shipped behaviour; see gen_ai_data.py. */
#define AI_DIST_EQUIL          4.545455f
#define AI_COEFF_ACCEL_MAX     10.000000f
#define AI_COEFF_ACCEL_MIN     3.272727f
#define AI_COEFF_WAIT_MAX      0.100000f
#define AI_COEFF_WAIT_MIN      0.427273f
#define AI_DELTA_ACCEL_FAR     30.472727f  /* MIN + MAX, as FUN_004f74f0 stores it */
#define AI_DELTA_WAIT_FAR      31.481818f  /* MIN + MAX, as FUN_004f74f0 stores it */
#define AI_DELTA_ACCEL_NEAR    6.154545f
#define AI_DELTA_WAIT_NEAR     6.154545f

/* Settings/AIEmu.ini via FUN_004a1440: DistCam is raw * 0.1 metres and
   FUN_004a0f60 calls a point visible when it is inside it -- or inside
   half of it BEHIND the camera. The Prob* pair belongs to the
   multiplayer GMAIEMU path, which repositions off-camera AI cars; the
   port has no equivalent and does not read them. */
#define AI_DIST_CAM 25.000000f
static const float AI_PROB_ACCUM[6] = { 36.0f, 28.0f, 22.0f, 18.0f, 15.0f, 12.0f };  /* unread */
static const float AI_PROB_CHECK[6] = { 10.0f, 15.0f, 22.0f, 30.0f, 40.0f, 50.0f };  /* unread */

#endif
