/*
 * carlight.c -- see carlight.h. Every constant is vis_data.h's, generated by
 * gen_vis_data.py from the game's own Settings and Splines; the model is
 * FUN_00531ff0's and carVisualBody's.
 */

#include "carlight.h"

#include <math.h>
#include <string.h>

#define DEG2RAD 0.017453292519943295f

static int cl_on = 1;

static float clamp01(float v)
{
    return v < 0.f ? 0.f : (v > 1.f ? 1.f : v);
}

/* ------------------------------------------------------------------ the curve */

float carlight_curve(float x)
{
    static const struct { float in, out; } pt[LIGHT_LM_CURVE_N] = LIGHT_LM_CURVE;
    int i;

    /* 0x0040f830: clamped to the endpoint value outside the range, linear
       between consecutive points. The same rule as rb_curve_eval in contact.c,
       written out here so this file links against nothing -- carlight_test
       asserts the two agree on this curve. */
    if (x <= pt[0].in)
        return pt[0].out;
    if (x >= pt[LIGHT_LM_CURVE_N - 1].in)
        return pt[LIGHT_LM_CURVE_N - 1].out;
    for (i = 0; i < LIGHT_LM_CURVE_N - 1; i++) {
        if (x >= pt[i].in && x < pt[i + 1].in) {
            const float dx = pt[i + 1].in - pt[i].in;
            if (dx < 1e-6f && dx > -1e-6f)
                return pt[i].out;
            return pt[i].out + (x - pt[i].in) * (pt[i + 1].out - pt[i].out) / dx;
        }
    }
    return pt[LIGHT_LM_CURVE_N - 1].out;
}

/* ------------------------------------------------------------- the direction */

void carlight_dir(float out[3])
{
    const float az = LIGHT_AZIMUTH_DEG * DEG2RAD;
    const float el = LIGHT_ELEVATION_DEG * DEG2RAD;
    const float ce = cosf(el);

    if (!out)
        return;
    /* Ry(azimuth) on (0,0,1) is (sin az, 0, cos az) -- the same row-vector
       convention dirarrow.c takes from FUN_0040cc60 -- and rotating a HORIZONTAL
       unit vector toward +Y by el is cos(el)*h + sin(el)*Y. carlight.h, point 4,
       for why FUN_0040b4c0's min() cannot bite here. */
    out[0] = sinf(az) * ce;
    out[1] = sinf(el);
    out[2] = cosf(az) * ce;
}

void carlight_model_dir(const float m[16], float out[3])
{
    float W[3];
    int r;

    if (!m || !out)
        return;
    carlight_dir(W);
    for (r = 0; r < 3; r++)
        out[r] = W[0] * m[r * 4 + 0] + W[1] * m[r * 4 + 1] + W[2] * m[r * 4 + 2];
}

/* ------------------------------------------------------------------ the level */

void carlight_reset(carlight_t *cl)
{
    if (!cl)
        return;
    /* 0x005320de's own pair: level 1.0 and the latch down. A car that has just
       been put on the grid is fully lit until the first sample lands, which is
       the engine's answer and not a placeholder. */
    cl->level = 1.f;
    cl->in_range = 0;
    cl->n_samples = 0;
    cl->raw = -1.f;
}

void carlight_step(carlight_t *cl, float cam_dist,
                   const float *samples, int n, float fallback, float dt)
{
    float mean = 0.f, target;
    int i, entered = 0;

    if (!cl)
        return;

    /* THE LOD GATE, and it is the engine's first act: with no camera inside
       maxdist the level is forced to 1.0 and the latch cleared, so a car that
       comes back into range snaps to whatever it is standing on rather than
       fading up from the last thing it saw. */
    if (!(cam_dist < LIGHT_LM_MAXDIST)) {
        cl->level = 1.f;
        cl->in_range = 0;
        cl->n_samples = 0;
        cl->raw = -1.f;
        return;
    }

    if (!cl->in_range) {
        cl->level = 1.f;
        cl->in_range = 1;
        entered = 1;
    }

    /* The mean over the wheels that answered -- FUN_00501820 per wheel, then
       FUN_004572c0 per contact, and only the ones that got a texel count. */
    cl->n_samples = 0;
    for (i = 0; i < n; i++) {
        if (samples[i] < 0.f)
            continue;
        mean += samples[i];
        cl->n_samples++;
    }
    if (cl->n_samples > 0) {
        mean /= (float)cl->n_samples;
    } else if (fallback >= 0.f) {
        /* The engine's sphere-query branch: one sample at the car's own
           position. It is the reason a car that jumps does not flicker. */
        mean = fallback;
    } else {
        /* Nothing to say. The engine returns here and leaves the level where it
           was -- NOT at 1.0, which is a different thing and would flash the car
           bright every time a wheel left a lightmapped face. */
        cl->raw = -1.f;
        return;
    }
    cl->raw = mean;

    target = carlight_curve(mean * 255.f) * (1.f / 255.f);

    if (entered) {
        /* The entry snap, `local_d0' at 0x00532105. */
        cl->level = target;
        return;
    }
    /* The dead band is on the DIFFERENCE, tested before the step, so a level
       within LIGHT_LM_DELTA of the target simply stops moving -- the engine
       never lands exactly on it and does not try to. */
    if (fabsf(cl->level - target) <= LIGHT_LM_DELTA)
        return;
    if (target > cl->level) {
        cl->level += LIGHT_LM_ALPHAVEL * dt;
        if (cl->level > target)
            cl->level = target;
    } else {
        cl->level -= LIGHT_LM_ALPHAVEL * dt;
        if (cl->level < target)
            cl->level = target;
    }
}

/* ------------------------------------------------------------- the two terms */

void carlight_terms(const carlight_t *cl, float cam_dist,
                    float *ambient, float *direct)
{
    const float level = cl ? cl->level : 1.f;
    float amb = (float)LIGHT_AMBIENT * level;
    float dir = (float)LIGHT_DIRECT * level;
    float f = 1.f;

    /* THE LOD FADE, 0x00507833: 1 inside NEAR, 0 outside FAR, a ramp between,
       and then the ambient lerps toward 255 while the direct lerps toward 0 --
       which together are the unlit texture. */
    if (cam_dist >= LIGHT_FADE_NEAR) {
        if (cam_dist > LIGHT_FADE_FAR
            || LIGHT_FADE_FAR - LIGHT_FADE_NEAR < 1e-6f)
            f = 0.f;
        else
            f = 1.f - (cam_dist - LIGHT_FADE_NEAR)
                      / (LIGHT_FADE_FAR - LIGHT_FADE_NEAR);
    }
    amb = f * (amb - 255.f) + 255.f;
    dir = f * dir;

    /* The engine's own two clamps, on the BYTES, before they are greyed. */
    if (amb > 255.f) amb = 255.f;
    if (dir > 255.f) dir = 255.f;

    if (ambient) *ambient = clamp01(amb * (1.f / 255.f));
    if (direct)  *direct  = clamp01(dir * (1.f / 255.f));
}

/* ------------------------------------------------------------------ the shading */

void carlight_set_enabled(int on) { cl_on = on ? 1 : 0; }
int  carlight_enabled(void)       { return cl_on; }

void carlight_shade(float ambient, float direct, const float L[3],
                    const float *nrm, unsigned int n, unsigned char *out)
{
    unsigned int i;

    if (!nrm || !out || !L)
        return;
    for (i = 0; i < n; i++) {
        const float *v = &nrm[i * 3];
        float d = v[0] * L[0] + v[1] * L[1] + v[2] * L[2];
        float c;
        int b;
        if (d < 0.f)
            d = 0.f;                  /* max(0, N.L): no negative light */
        c = ambient + direct * d;
        /* The clamp is on the SUM, which is where the engine's own is: 138 + 128
           is 266 of 255, so a face square to the sun saturates and the pair was
           chosen for exactly that. */
        b = (int)(clamp01(c) * 255.f + 0.5f);
        out[i * 4 + 0] = (unsigned char)b;
        out[i * 4 + 1] = (unsigned char)b;
        out[i * 4 + 2] = (unsigned char)b;
        out[i * 4 + 3] = 255;         /* the car is opaque; its cut-outs are the
                                         texture's alpha and the alpha TEST */
    }
}
