/* Generated by rccars_re/gen_champ_data.py -- do not edit.
 *
 * THE GARAGE'S ECONOMY, out of Scripts/championship.ini. Every
 * figure below is the shipped file's; the sell prices are the buy
 * prices times 0.9f AT SINGLE PRECISION and then truncated, which
 * is the only reading under which the game's own screenshot says
 * $900 for a $1000 car -- see the generator's docstring.
 *
 * The tyre pages are charged the RESONATOR's column, because that
 * is what the retail exe does -- see the generator's docstring for
 * the three call sites and the screenshot that says so. */
#ifndef CHAMP_DATA_H
#define CHAMP_DATA_H

#define CHAMP_N_CARS   3
#define CHAMP_N_LEVELS 3   /* the three above Default */

/* Common/DefaultCash -- what a new profile starts with, which is
   also the $100 on the game's own Garage screenshot. */
#define CHAMP_DEFAULT_CASH 100

/* Car<n>/AccessCash -- what a car costs, in rb_data.h's order
   (championship.ini's Car1/2/3 are Overkill, Buggy, Hummer, which
   its own #defines at the top of the file say). */
static const int CHAMP_CAR_PRICE[CHAMP_N_CARS] = { 1000, 2000, 1250 };
static const int CHAMP_CAR_SELL[CHAMP_N_CARS]  = { 900, 1800, 1125 };
/* Car<n>/IsEnabled -- which car a fresh profile already owns. Only
   the Overkill, which is what player_init_new builds. */
static const int CHAMP_CAR_OWNED[CHAMP_N_CARS] = { 1, 0, 0 };

/* Boost-Car<n>/Level<L> */
static const int CHAMP_BOOSTER_PRICE[CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   50,  190,  520 },
    {  220,  520,  890 },
    {  170,  430,  710 },
};

/* Resonator-Car<n>/Level<L> */
static const int CHAMP_ENGINE_PRICE[CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   65,  290,  730 },
    {  175,  790, 1325 },
    {  210,  775, 1290 },
};

/* Tires-Car<n>/Level<L> */
static const int CHAMP_TIRES_PRICE[CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   45,  210,  450 },
    {  210,  380,  690 },
    {  280,  510,  950 },
};

/* WHAT THE SHOP ACTUALLY CHARGES, kind x car x level -- the tables
   above indexed as the retail exe indexes them:
     *   booster -> BOOSTER
     *   engine  -> ENGINE
     *   tires   -> ENGINE
   The tyres read the ENGINE's column. That is the shipped game's
   own behaviour: the exe has no tyre-price getter, all three of the
   tyre page's call sites call the resonator's, and the game's own
   screenshot of that page prints $65 -- Resonator-Car1/Level1 --
   where Tires-Car1/Level1 is 45. */
static const int CHAMP_PART_PRICE[3][CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   /* booster, out of CHAMP_BOOSTER_PRICE */
        {   50,  190,  520 },
        {  220,  520,  890 },
        {  170,  430,  710 },
    },
    {   /* engine, out of CHAMP_ENGINE_PRICE */
        {   65,  290,  730 },
        {  175,  790, 1325 },
        {  210,  775, 1290 },
    },
    {   /* tires, out of CHAMP_ENGINE_PRICE */
        {   65,  290,  730 },
        {  175,  790, 1325 },
        {  210,  775, 1290 },
    },
};

static const int CHAMP_PART_SELL[3][CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   /* booster */
        {   45,  171,  468 },
        {  198,  468,  801 },
        {  153,  387,  639 },
    },
    {   /* engine */
        {   58,  261,  657 },
        {  157,  711, 1192 },
        {  189,  697, 1161 },
    },
    {   /* tires */
        {   58,  261,  657 },
        {  157,  711, 1192 },
        {  189,  697, 1161 },
    },
};

/* Nothing reads championship.ini's TEN TRACK SECTIONS yet -- their
   AccessCash, RaceTariff and Place1..3 are the championship's own
   entry fees and prize money, and no championship is built. They are
   deliberately not emitted rather than emitted unused. */

#endif /* CHAMP_DATA_H */
