/* Generated by rccars_re/gen_champ_data.py -- do not edit.
 *
 * THE ECONOMY, out of Scripts/championship.ini: the GARAGE's
 * price list and the CHAMPIONSHIP's ten track sections. Every
 * figure below is the shipped file's; the sell prices are the buy
 * prices times 0.9f AT SINGLE PRECISION and then truncated, which
 * is the only reading under which the game's own screenshot says
 * $900 for a $1000 car -- see the generator's docstring.
 *
 * The tyre pages are charged the RESONATOR's column, because that
 * is what the retail exe does -- see the generator's docstring for
 * the three call sites and the screenshot that says so. */
#ifndef CHAMP_DATA_H
#define CHAMP_DATA_H

#define CHAMP_N_CARS   3
#define CHAMP_N_LEVELS 3   /* the three above Default */

/* Common/DefaultCash -- what a new profile starts with, which is
   also the $100 on the game's own Garage screenshot. */
#define CHAMP_DEFAULT_CASH 100

/* Car<n>/AccessCash -- what a car costs, in rb_data.h's order
   (championship.ini's Car1/2/3 are Overkill, Buggy, Hummer, which
   its own #defines at the top of the file say). */
static const int CHAMP_CAR_PRICE[CHAMP_N_CARS] = { 1000, 2000, 1250 };
static const int CHAMP_CAR_SELL[CHAMP_N_CARS]  = { 900, 1800, 1125 };
/* Car<n>/IsEnabled -- which car a fresh profile already owns. Only
   the Overkill, which is what player_init_new builds. */
static const int CHAMP_CAR_OWNED[CHAMP_N_CARS] = { 1, 0, 0 };

/* Boost-Car<n>/Level<L> */
static const int CHAMP_BOOSTER_PRICE[CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   50,  190,  520 },
    {  220,  520,  890 },
    {  170,  430,  710 },
};

/* Resonator-Car<n>/Level<L> */
static const int CHAMP_ENGINE_PRICE[CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   65,  290,  730 },
    {  175,  790, 1325 },
    {  210,  775, 1290 },
};

/* Tires-Car<n>/Level<L> */
static const int CHAMP_TIRES_PRICE[CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   45,  210,  450 },
    {  210,  380,  690 },
    {  280,  510,  950 },
};

/* WHAT THE SHOP ACTUALLY CHARGES, kind x car x level -- the tables
   above indexed as the retail exe indexes them:
     *   booster -> BOOSTER
     *   engine  -> ENGINE
     *   tires   -> ENGINE
   The tyres read the ENGINE's column. That is the shipped game's
   own behaviour: the exe has no tyre-price getter, all three of the
   tyre page's call sites call the resonator's, and the game's own
   screenshot of that page prints $65 -- Resonator-Car1/Level1 --
   where Tires-Car1/Level1 is 45. */
static const int CHAMP_PART_PRICE[3][CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   /* booster, out of CHAMP_BOOSTER_PRICE */
        {   50,  190,  520 },
        {  220,  520,  890 },
        {  170,  430,  710 },
    },
    {   /* engine, out of CHAMP_ENGINE_PRICE */
        {   65,  290,  730 },
        {  175,  790, 1325 },
        {  210,  775, 1290 },
    },
    {   /* tires, out of CHAMP_ENGINE_PRICE */
        {   65,  290,  730 },
        {  175,  790, 1325 },
        {  210,  775, 1290 },
    },
};

static const int CHAMP_PART_SELL[3][CHAMP_N_CARS][CHAMP_N_LEVELS] = {
    {   /* booster */
        {   45,  171,  468 },
        {  198,  468,  801 },
        {  153,  387,  639 },
    },
    {   /* engine */
        {   58,  261,  657 },
        {  157,  711, 1192 },
        {  189,  697, 1161 },
    },
    {   /* tires */
        {   58,  261,  657 },
        {  157,  711, 1192 },
        {  189,  697, 1161 },
    },
};

/* ------------------------------------------ THE CHAMPIONSHIP
   championship.ini's TEN TRACK SECTIONS, in ITS OWN ORDER --
   Track1..Track10 is the ENGINE's track numbering (Surf, Fishers,
   Fort, AAD, Mines, Camping, AWACS, Rancho, Silo, War path), which
   is the order player.h's pl_track_slot() converts into and NOT
   the port's TRACKS[] order. champ.c is the only file that
   indexes these, and it converts. */
#define CHAMP_N_TRACKS 10
#define CHAMP_N_PLACES 3   /* Place1..3; there is no Place4 */

/* Track<n>/IsOpened -- open from the first race whatever the
   profile has done. The first four; the other six are earned. */
static const int CHAMP_TRACK_OPEN[CHAMP_N_TRACKS] = { 1, 1, 1, 1, 0, 0, 0, 0, 0, 0 };

/* Track<n>/AccessCash -- SCORES required, not cash (see above). */
static const int CHAMP_TRACK_SCORES[CHAMP_N_TRACKS] = {
        0,    15,    65,   250,   500,  1000,  1500,  2100,  3000,  5000
};

/* Track<n>/RaceTariff -- the entry fee, taken in CASH when the
   pre-race page is confirmed (FUN_004c0300, control 0xce4). */
static const int CHAMP_TRACK_FEE[CHAMP_N_TRACKS] = {
        0,    50,   100,   150,   200,   250,   300,   400,   500,  1000
};

/* Track<n>/Place1..3 -- the prize for finishing 1st, 2nd or 3rd,
   paid into BOTH cash and scores (FUN_004c56c0). Fourth and worse
   are paid nothing: the file has no Place4, and with a grid of
   four that leaves exactly the podium paid. */
static const int CHAMP_TRACK_PRIZE[CHAMP_N_TRACKS][CHAMP_N_PLACES] = {
    {   50,   30,   15 },   /* Surf (beach_1) */
    {  150,  100,   50 },   /* Fishers (country_3) */
    {  250,  150,   75 },   /* Fort (beach_3) */
    {  400,  250,  125 },   /* AAD (urban_2) */
    {  500,  300,  150 },   /* Mines (country_2) */
    {  600,  400,  200 },   /* Camping (beach_2) */
    {  700,  400,  200 },   /* AWACS (urban_1) */
    {  850,  500,  250 },   /* Rancho (country_1) */
    { 1000,  600,  250 },   /* Silo (country_4) */
    { 2000,  750,  350 },   /* War path (beach_4) */
};

#endif /* CHAMP_DATA_H */
