/*
 * char.h -- the 59 people, animals and road cars the tracks place.
 *
 * The other half of the dynamic layer. prop.c does the 129 knockable objects;
 * this does the Dogs, Seagulls, Crabs, Spiders, Vultures, Men, Women,
 * RepairMen, Guards, Trucks, Trailers, Hammers and the one Btr -- everything a
 * track instances out of AIChars.sb, people.sb and Roadcar.sb.
 *
 * WHERE THE DATA COMES FROM, and none of it is invented:
 *
 *   char_data.h   generated by gen_char_data.py: every placement with its own
 *                 markers, volumes and script keys, and the behaviour constants
 *                 out of the nine loaders in the exe.
 *   <track>.chr   packed by pack_chars.py: the models that track needs -- their
 *                 node hierarchy, their meshes, their SKIN, their animation
 *                 clips -- and the recorded paths its instances name.
 *
 * THREE THINGS THIS IS NOT.
 *
 *   It is not a physics object. A character does not collide with the car and
 *   the car does not collide with it, deliberately: the handling model is
 *   transcribed and every contact in it is accounted for, and adding a
 *   two-metre pedestrian to the contact solve is a handling change wearing a
 *   rendering change's clothes. What a character does notice is being RUN OVER
 *   -- a proximity test against the car, which raises a clip and a voice and
 *   moves nothing.
 *
 *   It is not the engine's own AI. Only the WALKERS and the PATH followers
 *   replay something recorded; the Dog, the Seagull, the Crab, the Spider and
 *   the Guard run state machines that are THE PORT'S. Every threshold in them
 *   is a recovered constant out of char_data.h and every target is a marker or
 *   a volume out of the instance's own subtree, so the shapes are the data's
 *   even where the machine is not. The nine behaviour loaders that fill those
 *   constants are recovered; what the engine DOES with them is not, and the
 *   header says so at each state machine.
 *
 *   It is not scene.c. A character rig runs to 89 parts against
 *   CARANI_MAX_PARTS's 56, and four of the thirteen models are skinned, which
 *   needs a per-vertex bone list and a blend that scene_draw has no place for.
 *   The one thing shared is the texture uploader -- scene_read_texture -- so
 *   quality, the 565 byte order and the mip rule cannot drift between the two
 *   formats.
 */
#ifndef CHAR_H
#define CHAR_H

#include "col.h"
#include "char_data.h"

/* Forward-declared rather than pulling rb.h in here: char.h is included by
   main.c, chartest.c and sfx.c, and only the solid contact below needs the car.
   char.c includes rb.h itself. */
struct rb_car;

#include <vitaGL.h>

/* The Crab is the widest rig in the shipped set at 89 parts; the Guard is 76
   and the Man 71. 96 leaves headroom without another allocation per instance --
   the pose arrays are per SCENE, not per instance, because only one character
   is being posed at a time. */
#define CHR_MAX_PARTS 96

/* Thirteen is the most any track places (beach_3). */
#define CHR_MAX_INST 16

#define CHR_NAME 32

/*
 * DRAW AND STEP RANGES, both THE PORT'S, and MEASURED FROM DIFFERENT POINTS.
 *
 * CHR_STEP_DIST is measured from the CAR, because what a character reacts to is
 * the car: the Dog's vision cone, the Guard's volume and the run-over test all
 * read it, and a Dog that only starts chasing once it is on screen has visibly
 * just woken up. The state machines are a few floats each, so 60 m costs
 * nothing.
 *
 * CHR_DRAW_DIST is measured from the EYE, because that is what drawing is about
 * -- and the two are not the same point. The chase camera sits about a metre
 * behind the car and the free camera can be anywhere at all. Past it the
 * instance is not posed, which is where the cost is: up to 89 matrix composes,
 * plus a blend over every vertex on a skinned model.
 *
 * It is the same order as ai.c's AI_DRAW_DIST (80 m) but shorter: an opponent
 * is a car the player is racing and a seagull is scenery.
 */
#define CHR_DRAW_DIST 45.0f
#define CHR_STEP_DIST 60.0f

/*
 * BEING RUN OVER. Both numbers are the port's, and the speed floor is
 * deliberately the same 0.35 m/s sfx.c uses for a prop knock -- a character
 * reacting to a car that is barely moving reads as a bug, and the two should
 * agree about what counts as a knock. CHR_HIT_RADIUS is a flat radius rather
 * than a proxy: nothing here is a collision, and a character's own collision
 * shape is not recovered (the Spider is the only model with CdtRad at all).
 */
/*
 * DROPPING A CHARACTER ONTO THE GROUND, and why it takes two probes.
 *
 * The authored Y is a pivot that floats -- the same convention the props and the
 * checkpoint markers follow, and prop_init has to drop those too. The first
 * probe uses a TIGHT ceiling, because a generous one lifts a character standing
 * under something onto the thing above it: that is exactly what beach_2's
 * overpass did to the car's own spawn, seven metres up.
 *
 * But a tight ceiling finds nothing at all when the character is authored BELOW
 * the surface it belongs on -- country_3's `Seagull_Na_Kamne`, the seagull on
 * the stone, is authored 1.12 m under the rock's own collision, and beach_3's is
 * 1.03 m under. Leaving those where they are buries them. So a second probe with
 * a generous ceiling runs ONLY when the first found nothing, which is the same
 * rule pack_col.py's own hole check had to learn: take the nearest surface in
 * either direction rather than insisting it be below.
 */
#define CHR_DROP_CEIL 1.0f      /* metres above the pivot -- the tight probe */
#define CHR_DROP_LIFT 8.0f      /* and the fallback, only if that found none */

#define CHR_HIT_RADIUS 0.45f
#define CHR_HIT_MIN_SPEED 0.35f
#define CHR_HIT_COOL 3.0f

/*
 * THE VULTURE IS SCALED AND SHIFTED BY ITS OWN CONFIG, and this is the one
 * placement the .sb does not settle on its own.
 *
 * Its mesh is 14.33 m across -- five times a real bird -- and country_2 places
 * it at instance scale 0.5, which still leaves 7.2 m. vulture.ini's `Scale`
 * 0.32 closes it: 14.33 * 0.32 * 0.5 = 2.29 m, which is a vulture. So BOTH
 * scales apply, and that is what the arithmetic says rather than what the names
 * suggest.
 *
 * `ShiftY` converts to -4.4 m, far more than the model's own 1.09 m of height,
 * and the path it flies is named ZEROCAM in its own header -- a camera path,
 * not a bird path. So the shift is applied to the WORLD position, lowering the
 * bird below the camera track it was recorded from. Marked as a reading, not a
 * recovery.
 */

typedef struct {
    unsigned short part, comp;      /* comp indexes a TRS triple, 0..8 */
    unsigned int n;
    float *k;                       /* 2n floats: time, value */
} chr_chan_t;

typedef struct {
    char name[CHR_NAME];
    float duration;
    unsigned int frames;
    unsigned int n_pose;
    unsigned short *pose_part;
    float *pose;                    /* 9 per entry: t, r(deg), s */
    unsigned int n_chan;
    chr_chan_t *chan;
} chr_clip_t;

/*
 * A part carries TWO poses and they are not the same pose.
 *
 *   trs   the node's own 0x540B -- the pose the model was SAVED in. What a part
 *         a clip says nothing about holds, and the whole pose of a model with no
 *         clips at all (the Vulture and the four road cars).
 *   bind  the node's own 0x5438 -- THE SKIN'S BIND POSE, the pose the packed
 *         vertices are in. `rest_inv` is the inverse of the composed bind chain,
 *         so posing the model from `bind` gives the identity on every part and
 *         posing it from `trs` does not.
 *
 * The people's mesh is a T-pose (1.57 m across against 1.66 m tall) their saved
 * pose is not, and binding the skin to `trs` is what drew every skinned model
 * stuck in its bind layout -- arms out, wings spread, the Dog splayed. `bind` is
 * carried so that relationship stays checkable; chr_pose does not read it.
 */
typedef struct {
    char name[CHR_NAME];
    int parent;                     /* -1 on the model's own root */
    float trs[9];                   /* t, SCALE, r(deg) -- the 0x540B order */
    float bind[9];                  /* the same order, the 0x5438 bind pose */
    float rest_inv[16];             /* model -> part at the BIND pose */
} chr_part_t;

typedef struct {
    unsigned int slot;              /* which texture slot, not which texture */
    unsigned int part;              /* rigid batches draw under this part */
    unsigned int nverts, nidx;
    unsigned int skinned;
    float *verts;                   /* 5 per vertex: x, y, z, u, v */
    unsigned char *inf_n;           /* skinned: influences per vertex */
    unsigned short *inf_part;       /* skinned: CHR_MAX_INF per vertex */
    float *inf_w;
    unsigned short *idx;
} chr_batch_t;

/*
 * The most bone influences a vertex can carry. FIVE, because that is the most
 * any shipped model uses -- the Dog has four vertices at five and the Seagull
 * four, everything else stops at three. A cap below the data is not free: the
 * weights are normalised at PACK time over all of them, so dropping the tail at
 * load leaves a vertex whose weights sum to less than one and which therefore
 * shrinks toward the model origin. char.c renormalises what it keeps for that
 * reason, so a smaller cap degrades rather than breaks.
 */
#define CHR_MAX_INF 5

/*
 * How many frames of skinning scratch to keep. vitaGL's own circular vertex
 * pool is one arena per display buffer (gxm_display_buffer_count, 3 by default),
 * reset at swap for the buffer coming round again -- so three is what says "the
 * GPU is done with it". See the skin ring in chr_t.
 */
#define CHR_SKIN_RINGS 3

/*
 * WHAT char_draw IS ALLOWED TO DRAW. A diagnostic, set from main.c and cycled on
 * a button: a screenshot cannot name geometry, so the way to find out what an
 * object on screen IS, is to stop drawing one class at a time and see what
 * disappears. `chr_t` carries it rather than a static so a track change resets it
 * with everything else.
 */
#define CHR_HIDE_NONE 0
#define CHR_HIDE_PATH 1     /* the road cars and the vultures: every replayer */
#define CHR_HIDE_ALL  2

typedef struct {
    char name[CHR_NAME];
    unsigned int n_parts, n_batches, n_clips, n_slot, n_var;
    chr_part_t *part;
    chr_batch_t *batch;
    chr_clip_t *clip;
    unsigned int *var;              /* n_var * n_slot -> texture index */
    float bmin[3], bmax[3];
    /*
     * Degrees to pre-rotate the model by so that its own forward becomes +Z,
     * which is the direction every heading in this file is expressed in.
     * Derived at pack time with a witness -- see sbchar.model_forward. It is
     * 0 on everything with a skeleton (their toes and their heads both point
     * +Z) and +90 on the Truck, the Trailer and the Hammer, whose headlamps sit
     * at the extreme -X of the model.
     */
    float yaw_off;
    float radius;                   /* about the model origin, for culling */
    unsigned int max_verts;         /* largest skinned batch, for the scratch */
    unsigned int skin_verts;        /* ALL of them, summed -- see CHR_SKIN_RINGS */
    /* This model's entry in char_data.h's CHR_PROXY, resolved by name once at
       load. NULL for a model the table does not name; ->n is 0 for the Seagull
       and the Vulture, which the engine's own registries leave unsolid. */
    const chr_proxy_t *proxy;
} chr_model_t;

typedef struct {
    char name[CHR_NAME];            /* what an instance's `path` names */
    unsigned int kind;              /* 0 = a person's .dat, 1 = a .gpf */
    unsigned int n;
    float duration;
    float *t;                       /* n */
    float *p;                       /* 3n */
    float *f;                       /* 3n */
    float *u;                       /* 3n */
    float *s;                       /* n -- the .dat's undecoded state column */
} chr_path_t;

/* What a state machine is doing. Shared across kinds because the shapes are the
   same: sit still, go somewhere, do something on arrival, come back. */
typedef enum {
    CHR_ST_IDLE,
    CHR_ST_GO,          /* moving toward `tx,ty,tz` */
    CHR_ST_ACT,         /* attacking / shooting / hiding, for `timer` */
    CHR_ST_RETURN,      /* going home */
    CHR_ST_FLY,         /* the seagull, once airborne */
    CHR_ST_HURT
} chr_state_t;

/*
 * What just happened to an instance, raised for ONE step and cleared at the top
 * of the next. char.c does not touch the audio layer for the reason menu.c does
 * not: it raises a cue saying what happened and the caller decides what that
 * sounds like. Each of these is an EDGE -- prop_t.hit's rule, and for the same
 * reason, since a dog with a car parked in front of it is in the attack state
 * for as long as the car is there.
 */
typedef enum {
    CHR_EV_NONE,
    CHR_EV_BARK,        /* a Dog began an attack          -> dog_attack     */
    CHR_EV_TAKEOFF,     /* a Seagull left the ground      -> seagull_vzliot */
    CHR_EV_HURT         /* anything was run over          -> man/woman_voice */
} chr_event_t;

typedef struct {
    const chr_place_t *place;
    int model;
    int path;                       /* index into chr_t.path, or -1 */
    int variant;

    float x, y, z;                  /* world position */
    float yaw;                      /* degrees, the model's own +Z heading */
    float pitch, roll;              /* PATH followers only, off the recorded up */
    float scale;

    int clip;
    float clip_t;
    float clip_rate;

    int state;
    float timer;                    /* what the current state is counting */
    float speed;
    float tx, ty, tz;               /* where CHR_ST_GO is going */
    int leg;                        /* BURROW: which hole it is at or heading to */

    float path_t;
    unsigned int cursor;

    float hit_cool;
    int event;                      /* chr_event_t, one step only */
    int seen;                       /* did it notice the car this step */
    float dist2;                    /* to the CAR, for the step cull */
    float eye2;                     /* to the EYE, for the draw cull */
    int drawn;
    int solid_hit;                  /* the car's proxy overlapped ours this tick */
} chr_inst_t;

typedef struct {
    GLuint *tex;
    unsigned int n_tex;
    chr_model_t *model;
    unsigned int n_models;
    chr_path_t *path;
    unsigned int n_paths;

    chr_inst_t inst[CHR_MAX_INST];
    unsigned int n_inst;

    const col_t *col;
    int track;

    /* Pose scratch, reused per instance. world[] is the animated node->model
       transform, draw[] is world * rest_inv -- what a bind-pose vertex goes
       through. */
    float world[CHR_MAX_PARTS][16];
    float draw[CHR_MAX_PARTS][16];

    /*
     * Skinning scratch. MALLOC'D, NOT STATIC, and that is load-bearing on the
     * Vita: vitaGL maps only the newlib heap for the GPU (mem_utils.c:535), so
     * a `static float v[N]` handed to gl*Pointer is an address GXM cannot see.
     * fx.c, trace.c and envmap.c all had to move for the same reason.
     *
     * AND IT IS A RING OF ARENAS, ONE PER DISPLAY BUFFER, BUMP-ALLOCATED PER
     * DRAW. One buffer reused per batch is what drew the Woman, the Dog, the
     * RepairMan and the Guard as exploding spikes on hardware while every host
     * harness said the blend was perfect:
     *
     *   the custom vitaGL is built with DRAW_SPEEDHACK=2, so for a draw whose
     *   vertex data exceeds SAFE_DRAW_SIZE_THRESHOLD (0x8000 = 32 KB) it stops
     *   copying into a mapped temp and HANDS GXM THE CLIENT POINTER (ffp.c:1553,
     *   1580). GXM reads it when the scene flushes, not when glDrawElements is
     *   called -- so every big skinned draw in the frame read whatever the LAST
     *   fill had left in the shared buffer.
     *
     *   At 20 bytes a vertex the line is 1,638 verts, and it cuts straight
     *   through this cast: Woman 1798 + 1930, Dog 2028, RepairMan 1668 and
     *   Guard 1950 are over it, Man 1572 + 1564, RepairMan's second 1364,
     *   Guard's 1386 and every Seagull batch are under. That is exactly which
     *   characters were reported broken and which were not.
     *
     * So each skinned draw gets its own slice, valid for the whole frame, and
     * the arena rotates over CHR_SKIN_RINGS frames -- which is vitaGL's OWN
     * discipline for the pool it copies small draws into (circular_data_pool is
     * one arena per display buffer, advanced at swap by
     * vgl_framecount % gxm_display_buffer_count, gxm.c:790), and 3 is that
     * count. Sized at load to every drawable instance's total skinned vertices,
     * so a frame that draws all of them still fits.
     */
    /* Per texture, kept for char_dump and for the same reason scene.c keeps
       has_px: a declared texture whose image is missing gets an id from
       glGenTextures and never a glTexImage2D, which leaves the sampler
       undefined -- so a white or black model is a question this can answer
       without a rebuild. */
    char (*tex_name)[CHR_NAME];
    unsigned char *tex_px;

    float *skin[CHR_SKIN_RINGS];    /* 5 floats per vertex, like a packed vert */
    unsigned int skin_cap;          /* VERTICES per arena */
    unsigned int skin_used;         /* vertices taken out of this frame's arena */
    unsigned int skin_ring;         /* which arena this frame is filling */
    int skin_full;                  /* the overflow has been logged once */

    unsigned int n_drawn, n_stepped;
    int hide;                       /* CHR_HIDE_*, a diagnostic -- see above */
} chr_t;

/*
 * Load <track>.chr and place that track's characters. `track` is the name the
 * placements are keyed on ("beach_1"), `col` is the loaded collision grid and
 * may be NULL, in which case nothing is dropped to the ground and every
 * character keeps its authored pivot.
 *
 * Returns 0 and leaves an empty, safe chr_t if the file is missing -- a track
 * with no characters is a normal state, not a failure.
 */
int char_init(chr_t *c, const char *path, const char *track, const col_t *col);

void char_free(chr_t *c);

/* Put every instance back where it started. Called from a race restart, for the
   same reason ai_reset is: a Dog left chasing across the finish line is state
   from the previous run. */
void char_reset(chr_t *c);

/*
 * Advance the state machines and the replays. `car` is the player's position,
 * `car_fwd` its heading and `car_speed` its speed -- what the Dog's vision cone,
 * the Guard's volume and the run-over test all read, and what CHR_STEP_DIST is
 * measured from.
 */
void char_step(chr_t *c, float dt, const float car[3], const float car_fwd[3],
               float car_speed);

/* Draw everything within CHR_DRAW_DIST of `eye`, posing it on the way. Leaves
   GL as it found it, buffers unbound included -- the same contract scene_draw
   has, and for the same reason. Takes the eye like prop_draw does, and for the
   same reason: the camera is not the car. */
void char_draw(chr_t *c, const float eye[3]);

/* Where an instance is, for the caller that wants to put a sound or a shadow on
   it. Returns 0 if `i` is out of range. */
int char_pos(const chr_t *c, unsigned int i, float out[3]);

/* -------------------------------------------------------------- for tests --- */

/* Sample one channel the way the runtime does: linear between keys, clamped at
   both ends, a single key meaning a constant. */
float chr_sample(const chr_chan_t *ch, float t);

/* Pose one instance into c->world / c->draw. Exposed so a harness can look at
   where a joint ended up without going through a draw. */
void chr_pose(chr_t *c, unsigned int inst);

/* The same composition run off each part's BIND transform, ignoring the clip.
   rest_inv is the inverse of the composed bind chain, so this MUST come out the
   identity on every part -- the one statement that ties a packed part's bind
   pose to its rest_inv. chr_pose's own no-clip result is a different pose and
   is NOT the identity; asserting that it was is what let the wrong bind pose
   ship. */
void chr_pose_bind(chr_t *c, unsigned int inst);

/* The index of a part by name, or -1. The Dog's proxy names its five bones. */
int chr_part_index(const chr_model_t *m, const char *name);

/* ----------------------------------------------------------------- solid --- */

/*
 * One character's collision proxy in WORLD space, as (x, y, z, radius) quads --
 * the same shape rb_gather_spheres writes for the car, because it is the same
 * thing: the retail engine registers one of these per object 4CC and the car's
 * is $CAR's. -> the number written, 0 for a model that is not solid.
 *
 * See char_data.h's CHR_PROXY for what each model's is and where it came from.
 */
int char_proxy(chr_t *c, unsigned int inst, float out[][4]);

/*
 * Make the characters solid to the car: every overlapping sphere pair within
 * CHR_SOLID_RANGE goes into rb_coll_resolve with the CAR as the only body, so
 * the car is stopped and the character is not moved. -> how many characters were
 * touched, and `impact` (may be NULL) gets the hardest closing speed BEFORE any
 * impulse, which is what a caller raises a knock sound off.
 *
 * A no-op when nothing overlaps: it gathers, finds no pairs and never reaches
 * the solve, so a car nowhere near a character is bit-identical with this in or
 * out. Call it once per tick after the car's own physics, the way the engine
 * steps its collision layer once per frame (0x4fc685).
 */
int char_car_solid(chr_t *c, struct rb_car *car, float *impact);

/* Index of a model / clip by name, or -1. */
int chr_model_index(const chr_t *c, const char *name);
int chr_clip_index(const chr_model_t *m, const char *name);

/* Is (x, z) inside the volume's quad and y inside its range? A general convex
   quad test -- every shipped volume is a parallelogram and nothing here relies
   on it. */
int chr_in_volume(const chr_volume_t *v, float x, float y, float z);

/*
 * EVERY PLACED CHARACTER, WITH WHAT IT WOULD DRAW WITH, to the log. A diagnostic,
 * not telemetry: it is what answers "what is that white box on screen", which
 * three rounds of screenshots could not. Per instance: model, variant, position,
 * distance from the eye, whether it is inside CHR_DRAW_DIST, and for every
 * texture slot the GL id its variant resolves to, with `!` on an id of 0 (nothing
 * bound -- the model draws white) and `?` on one whose image never uploaded (the
 * sampler is undefined -- black or garbage). main.c calls it on a button.
 */
void char_dump(const chr_t *c, const float eye[3]);

/* The wav one instance's model names in its own MOD_SNDCHANNEL, or NULL where the
   model has none -- see char.c. What the caller does with the name is its own
   business; char.c never touches the audio layer. */
const char *chr_model_wav(const chr_t *c, unsigned int inst);

#endif /* CHAR_H */
