/*
 * char_data.h -- the 59 people, animals and road cars the tracks place, and
 * every behaviour constant the engine loads for them.
 *
 * GENERATED by rccars_re/gen_char_data.py -- do not edit by hand.
 *
 * The placements, their markers, their volumes and their script keys come from
 * each track's own .sb; the constants come from the loaders in RCCars.exe,
 * whose addresses are quoted per group below. Geometry, animation and the
 * recorded paths are NOT here -- they are packed per track into <track>.chr by
 * pack_chars.py, and char.c binds the two together by MODEL NAME.
 */
#ifndef CHAR_DATA_H
#define CHAR_DATA_H

/* dog -- dog.ini + dog.crs */
#define CHR_DOG_CONEANGLE          45.0f          /* raw 45 crs, raw -> 0x14ee8e4 */
#define CHR_DOG_RADNEAR            0.349999994f   /* raw 35 crs, raw * 0.01 -> 0x14ee8e8 */
#define CHR_DOG_RADFAR_NEAR        0.5f           /* raw 50 crs, raw * 0.01 -> 0x14ee8f0 */
#define CHR_DOG_RADFAR_FAR         3.0f           /* raw 300 crs, raw * 0.01 -> 0x14ee8ec */
#define CHR_DOG_RADREACH           0.299999982f   /* raw 30 crs, raw * 0.01 -> 0x14ee8f4 */
#define CHR_DOG_TIMEATTACK         1.5f           /* raw 150 crs, raw * 0.01 -> 0x14ee8f8 */
#define CHR_DOG_ANISPEED           4.0f           /* raw 400 crs, raw * 0.01 -> 0x14eead8 */

/* seagull -- seagull.ini + seagull.crs */
#define CHR_SEAGULL_SPEEDRUN           0.209999993f   /* raw 21 crs, raw * 0.01 -> 0x14ee070 */
#define CHR_SEAGULL_SPEEDFLIGHT        0.25f          /* raw 25 crs, raw * 0.01 -> 0x14ee074 */
#define CHR_SEAGULL_FLIGHTHEIGHT       1.5f           /* raw 150 crs, raw * 0.01 -> 0x14ee06c */
#define CHR_SEAGULL_VERTANGLEMAX       45.0f          /* raw 45 crs, raw -> 0x14ee078 */
#define CHR_SEAGULL_TIMEIDLE           0.219999999f   /* raw 22 crs, raw * 0.01 -> 0x14ee07c */
#define CHR_SEAGULL_TIMETURN           2.56999993f    /* raw 257 ini, raw * 0.01 -> 0x14ee080 */

/* spider -- spider.ini */
#define CHR_SPIDER_CDTRAD             0.229999989f   /* raw 23 ini, raw * 0.01 -> 0x14ee460 */
#define CHR_SPIDER_CDTSHIFTY          -0.24000001f   /* raw 76 ini, (raw * 0.01) - 1 -> 0x14ee464 */
#define CHR_SPIDER_HEIGHTFLOOR        0.0100000007f  /* raw 10 ini, raw * 0.001 -> 0x14ee468 */
#define CHR_SPIDER_HEIGHTFLOORDEAD    0.0f           /* raw 0 ini, raw * 0.001 -> 0x14ee46c */

/* vulture -- vulture.ini */
#define CHR_VULTURE_FLYVEL             1.01999998f    /* raw 102 ini, raw * 0.01 -> 0x14ef0d0 */
#define CHR_VULTURE_SCALE              0.319999993f   /* raw 32 ini, raw * 0.01 -> 0x14ef0d4 */
#define CHR_VULTURE_SHIFTY             -4.4000001f    /* raw 56 ini, (raw - 100) * 0.1 -> 0x14ef0d8 */

/* people -- People.ini + People.crs */
#define CHR_PEOPLE_SPEEDFORW          0.585858583f   /* raw 30 crs, clamped remap at 0x5120e0 */

/* sole -- peop_sole.ini + peop_sole.crs */
#define CHR_SOLE_TIMEDELAY          0.680000007f   /* raw 68 crs, raw * 0.01 -> 0x14ee05c */
#define CHR_SOLE_SHIFTX             0.119999997f   /* raw 12 crs, raw * 0.01 -> 0x14ee060 */
#define CHR_SOLE_SHIFTY             0.0299999993f  /* raw 3 crs, raw * 0.01 -> 0x14ee064 */
#define CHR_SOLE_SIZE               0.179999992f   /* raw 18 crs, raw * 0.01 -> 0x14ee068 */

/* guard -- guard.ini + guard.crs */
#define CHR_GUARD_TIMEFOLLOW         1.0f           /* raw 100 crs, raw * 0.01 -> 0x14eeae0 */
#define CHR_GUARD_TIMEATTACK         1.5f           /* raw 150 crs, raw * 0.01 -> 0x14eeaec */
#define CHR_GUARD_TIMEFOLLOWEX       4.01999998f    /* raw 402 ini, raw * 0.01 -> 0x14eeae4 */
#define CHR_GUARD_EXVOLUMEDELTA      3.0f           /* raw 300 ini, raw * 0.01 -> 0x14eeae8 */

/* roadcar -- roadcar.ini */
#define CHR_ROADCAR_DELTAALPHA         0.140000001f   /* raw 14 ini, raw * 0.01 -> 0x14ee8a0 */
#define CHR_ROADCAR_SHADOWY            0.479999989f   /* raw 48 ini, raw * 0.01 -> 0x14ee8a4 */
#define CHR_ROADCAR_SHADOWR            0.459999979f   /* raw 46 ini, raw * 0.01 -> 0x14ee8a8 */
#define CHR_ROADCAR_TOWERVEL           13.6199999f    /* raw 1362 ini, raw * 0.01 -> 0x14ee8ac */
#define CHR_ROADCAR_TOWERSHIFT         1.10000002f    /* raw 310 ini, (raw - 200) * 0.01 -> 0x14ee8b0 */
#define CHR_ROADCAR_TOWERSHOOTT        1.0f           /* raw 10 ini, raw * 0.1 -> 0x14ee8b4 */

/*
 * THE COLLISION PROXY -- one per model, and the characters ARE solid.
 *
 * The retail engine registers a sphere-set provider per object 4CC and a
 * resolver per PAIR of them, both at 0x534d00:
 *
 *   proxies (0x533130)  $CAR STON PEOP CRAB SPDR RDCR DOG$ GUAM
 *   pairs   (0x533170)  $CAR/$CAR $CAR/STON STON/STON $CAR/PEOP $CAR/GUAM
 *                       $CAR/CRAB $CAR/SPDR $CAR/RDCR STON/RDCR $CAR/DOG$
 *
 * So the car collides with the people, the guards, the crabs, the spiders, the
 * road cars and the dogs. The SEAGULL AND THE VULTURE ARE IN NEITHER REGISTRY --
 * they fly -- and they are the two models below with no spheres.
 *
 * A provider writes (x, y, z, radius) quads, the same shape rb_gather_spheres
 * writes for the car, and every resolver ends at rb_coll_resolve with the car as
 * the ONLY body: the car is pushed out and the character does not move. It is
 * the static side, exactly as the world is.
 *
 * The whole layer is stepped once per FRAME with dt (0x4fc685) over the objects
 * within CHR_SOLID_RANGE of the car, so there is no carSubstepContact bisection
 * behind it and no depenetration in it. That is the original.
 */
typedef enum {
    CHR_PX_NONE,     /* the flyers: in neither of the engine's registries */
    CHR_PX_COLUMN,   /* n spheres stacked in WORLD +Y from the instance position */
    CHR_PX_BONES,    /* n spheres at named joints, at their posed world positions */
    CHR_PX_HULL      /* THE PORT'S -- see the road cars below */
} chr_proxy_kind_t;

#define CHR_PROXY_MAX     8    /* RDCR's slot count, the largest of the six */
#define CHR_PROXY_BONES   5    /* the Dog's, the only BONES proxy */
#define CHR_SOLID_RANGE   10.0f  /* 0x41200000 at 0x53343b */

typedef struct {
    const char *model;
    unsigned char kind;                    /* chr_proxy_kind_t */
    unsigned char n;                       /* spheres, 0 for the flyers */
    float radius;                          /* every sphere, metres */
    float shift_y;                         /* the first sphere off the pivot */
    float step_y;                          /* between spheres, world up */
    const char *bone[CHR_PROXY_BONES];     /* BONES only */
} chr_proxy_t;

static const chr_proxy_t CHR_PROXY[] = {
    { "Dog",       CHR_PX_BONES,    5, 0.200000003f,        0.0f,                  0.0f,          { "LHAND1", "RHAND1", "LFOOT2", "RFOOT2", "HEAD" } },  /* DOG$ 0x518820 */
    { "Seagull",   CHR_PX_NONE,     0, 0.0f,                0.0f,                  0.0f,          { NULL, NULL, NULL, NULL, NULL } },  /* in neither registry */
    { "Crab",      CHR_PX_COLUMN,   1, 0.200000003f,        -0.180000007f,         0.0f,          { NULL, NULL, NULL, NULL, NULL } },  /* CRAB 0x513840 */
    { "Spider",    CHR_PX_COLUMN,   1, CHR_SPIDER_CDTRAD,   CHR_SPIDER_CDTSHIFTY,  0.0f,          { NULL, NULL, NULL, NULL, NULL } },  /* SPDR 0x514cb0 */
    { "Vulture",   CHR_PX_NONE,     0, 0.0f,                0.0f,                  0.0f,          { NULL, NULL, NULL, NULL, NULL } },  /* in neither registry */
    { "Man",       CHR_PX_COLUMN,   3, 0.200000003f,        0.0f,                  0.200000003f,  { NULL, NULL, NULL, NULL, NULL } },  /* PEOP 0x511e30 */
    { "Woman",     CHR_PX_COLUMN,   3, 0.200000003f,        0.0f,                  0.200000003f,  { NULL, NULL, NULL, NULL, NULL } },  /* PEOP 0x511e30 */
    { "RepairMan", CHR_PX_COLUMN,   3, 0.200000003f,        0.0f,                  0.200000003f,  { NULL, NULL, NULL, NULL, NULL } },  /* PEOP 0x511e30 */
    { "Guard",     CHR_PX_COLUMN,   2, 0.200000003f,        0.0f,                  0.200000003f,  { NULL, NULL, NULL, NULL, NULL } },  /* GUAM 0x51a350 */
    { "Truck",     CHR_PX_HULL,     3, 0.0f,                0.0f,                  0.0f,          { NULL, NULL, NULL, NULL, NULL } },  /* RDCR 0x516480, the port's */
    { "Trailer",   CHR_PX_HULL,     3, 0.0f,                0.0f,                  0.0f,          { NULL, NULL, NULL, NULL, NULL } },  /* RDCR 0x516480, the port's */
    { "Hammer",    CHR_PX_HULL,     3, 0.0f,                0.0f,                  0.0f,          { NULL, NULL, NULL, NULL, NULL } },  /* RDCR 0x516480, the port's */
    { "Btr",       CHR_PX_HULL,     3, 0.0f,                0.0f,                  0.0f,          { NULL, NULL, NULL, NULL, NULL } },  /* RDCR 0x516480, the port's */
};

#define CHR_N_PROXY  13

/* Behaviour families. Each names what the instance's own brief supports. */
typedef enum {
    CHR_KIND_DOG,      /* a vision cone, a chase, an attackVolume, a resetPlace */
    CHR_KIND_SEAGULL,  /* walks its inhabitVolume, takes off along flightDir */
    CHR_KIND_BURROW,   /* Crab and Spider: runs between two named holes */
    CHR_KIND_WALKER,   /* Man, Woman, RepairMan: replays a recorded walk */
    CHR_KIND_GUARD,    /* stands, turns to follow the car inside guardVolume */
    CHR_KIND_PATH,     /* road cars and vultures: replays a .gpf */
    CHR_KIND_COUNT
} chr_kind_t;

/* A named point out of the instance's own subtree. Absent markers have
   have_flag clear -- a Dog with no resetPlace goes back to where it spawned. */
typedef struct {
    float x, y, z, yaw;
} chr_marker_t;

/* MOD_VOLUME: a y range and four (x, z) corners in traversal order. Convex, and
   every shipped one is a parallelogram, but chr_in_volume tests it as a general
   convex quad so nothing depends on that. */
typedef struct {
    float ylo, yhi;
    float qx[4], qz[4];
} chr_volume_t;

#define CHR_MARK_NONE   0u
#define CHR_MARK_A      1u   /* flightDir / seahole1 / hole1 / resetPlace */
#define CHR_MARK_B      2u   /* landhole1 / hole2 */
#define CHR_VOL_SIGHT   4u   /* visibilityVolume */
#define CHR_VOL_HOME    8u   /* inhabitVolume / guardVolume */
#define CHR_VOL_ATTACK 16u   /* attackVolume */

typedef struct {
    const char *name;       /* the instance's own node name -- documentation */
    const char *model;      /* the MOD_MODEL in the .chr */
    unsigned char kind;     /* chr_kind_t */
    unsigned char variant;  /* clother / body -- which texture set to wear */
    unsigned int  have;     /* CHR_MARK_* | CHR_VOL_* */
    float x, y, z;          /* the authored pivot; char_init drops it to ground */
    float yaw;              /* degrees, unwrapped in the file */
    float scale;
    const char *path;       /* recorded path name in the .chr, or NULL */
    float phase;            /* 0..1 of the path's duration -- THE PORT'S */
    chr_marker_t mark_a, mark_b;
    chr_volume_t sight, home, attack;
} chr_place_t;

static const chr_place_t CHR_PLACE_BEACH_1[] = {
    { "Seagull_NearYacht", "Seagull", CHR_KIND_SEAGULL, 0, CHR_MARK_A | CHR_VOL_SIGHT | CHR_VOL_HOME,
      -17.7699032f, -0.739999115f, -89.5087814f, -98.9449768f, 1.0f, 0, 0.0f,
      {-9.73361778f,8.75600147f,-125.643654f,-200.069962f}, {0,0,0,0},
      {-1.50000024f,13.9799986f,{-18.7988567f,2.31332207f,-15.8707638f,-36.9829102f},{-108.192108f,-97.3792496f,-61.8750496f,-72.6880722f}},
      {-1.80000019f,5.01999331f,{-19.2188377f,-22.2796478f,-18.4363594f,-15.3756685f},{-78.6310196f,-92.9577408f,-93.7790833f,-79.4523392f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Seagull_NearStream", "Seagull", CHR_KIND_SEAGULL, 0, CHR_MARK_A | CHR_VOL_SIGHT | CHR_VOL_HOME,
      -13.9360113f, -0.991999269f, -7.03287983f, 6.44499731f, 1.0f, 0, 0.0f,
      {24.7026443f,7.96500015f,9.4857111f,-118.619965f}, {0,0,0,0},
      {-1.50000024f,9.16999817f,{-25.5743084f,-25.7454224f,-4.75567245f,-4.58469105f},{10.8232832f,-18.8763371f,-18.9972286f,10.7023773f}},
      {-1.50000024f,3.00499749f,{-19.1791687f,-15.8071566f,-11.0797491f,-14.4518843f},{1.65893614f,-12.7519274f,-11.6457376f,2.76508904f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Crab_NearYacht", "Crab", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      -26.9880428f, 0.169000998f, -62.6573334f, 129.014923f, 2.0f, 0, 0.0f,
      {-30.1961975f,-0.367999524f,-71.5989914f,-205.740005f}, {-25.9283772f,0.0720004886f,-62.6217766f,-253.48497f},
      {-1.6500001f,14.5649977f,{-41.0586472f,-32.5459518f,-13.6563807f,-22.1692448f},{-59.6723976f,-78.3434067f,-69.7309952f,-51.0601501f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Crab_NearStream", "Crab", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      -14.5185356f, 1.71686769f, 31.5492229f, 378.270264f, 2.0f, 0, 0.0f,
      {-7.47461605f,-0.00799976289f,33.0953674f,-359.505127f}, {-13.2580996f,-0.0739997327f,35.8020935f,-353.069885f},
      {-1.6500001f,8.56499863f,{-24.1774864f,-9.65864944f,-2.08560228f,-16.6044407f},{23.5372448f,20.3476734f,54.8209572f,58.0102921f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Man", "Man", CHR_KIND_WALKER, 0, CHR_MARK_NONE,
      15.5109587f, -0.396873534f, -82.4895706f, 630.360352f, 1.0f, "beach_1_man", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Woman", "Woman", CHR_KIND_WALKER, 0, CHR_MARK_NONE,
      15.5109587f, -0.396873534f, -82.4895706f, 630.360352f, 1.0f, "beach_1_woman", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

static const chr_place_t CHR_PLACE_BEACH_2[] = {
    { "Hammer", "Hammer", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_2_forw", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Trailer1", "Trailer", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_2_back", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Trailer2", "Trailer", CHR_KIND_PATH, 1, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_2_forw", 0.370000005f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Truck1", "Truck", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_2_back", 0.370000005f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Truck2", "Truck", CHR_KIND_PATH, 1, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_2_forw", 0.74000001f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Truck3", "Truck", CHR_KIND_PATH, 2, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_2_back", 0.74000001f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Dog_Na_Benzokolonke", "Dog", CHR_KIND_DOG, 0, CHR_MARK_A | CHR_VOL_ATTACK,
      35.5852203f, 5.58767223f, 20.5391369f, 37.034874f, 1.0f, 0, 0.0f,
      {31.3449955f,5.51801825f,17.8347473f,37.5208817f}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {3.58999896f,15.0549974f,{24.5652695f,18.0724144f,36.155014f,42.6479034f},{31.9231033f,10.9728737f,5.36833668f,26.3186417f}} },
    { "Dog_Na_Plyazhe", "Dog", CHR_KIND_DOG, 0, CHR_MARK_A | CHR_VOL_ATTACK,
      -60.5920372f, 3.03567624f, -16.1978683f, 302.084686f, 1.0f, 0, 0.0f,
      {-63.460659f,1.83002472f,-16.831028f,-1.7191596f}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {-1.73000145f,9.7349987f,{-53.8011818f,-68.7441635f,-77.6459885f,-62.7029343f},{-16.6554832f,-7.10675859f,-21.0365353f,-30.5852909f}} },
    { "RepairMan", "RepairMan", CHR_KIND_WALKER, 0, CHR_MARK_NONE,
      45.0322304f, 5.26767206f, 7.53673029f, 23.0398769f, 1.0f, "beach_2_repairman", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Woman", "Woman", CHR_KIND_WALKER, 0, CHR_MARK_NONE,
      -78.7135849f, 0.243129998f, -35.8427353f, 743.403198f, 1.0f, "beach_2_woman", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Seagull", "Seagull", CHR_KIND_SEAGULL, 0, CHR_MARK_A | CHR_VOL_SIGHT | CHR_VOL_HOME,
      -58.4903679f, 0.787001252f, -31.6024475f, -48.0499649f, 1.0f, 0, 0.0f,
      {-74.7557144f,11.9800129f,-52.2480774f,-57.0605965f}, {0,0,0,0},
      {-1.50000024f,9.97999859f,{-71.1981812f,-43.4298782f,-35.6280403f,-63.396431f},{-34.010704f,-44.6033478f,-24.1509552f,-13.5584354f}},
      {0.199999094f,2.90999794f,{-60.9783897f,-58.0800629f,-57.810463f,-60.7088127f},{-30.1002617f,-30.8748569f,-29.8703423f,-29.0958672f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

static const chr_place_t CHR_PLACE_BEACH_3[] = {
    { "Hammer", "Hammer", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_3_forw", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Trailer1", "Trailer", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_3_back", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Trailer2", "Trailer", CHR_KIND_PATH, 1, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_3_forw", 0.370000005f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Truck1", "Truck", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_3_back", 0.370000005f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Truck2", "Truck", CHR_KIND_PATH, 1, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_3_forw", 0.74000001f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Truck3", "Truck", CHR_KIND_PATH, 2, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_beach_3_back", 0.74000001f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Man1", "Man", CHR_KIND_WALKER, 1, CHR_MARK_NONE,
      -51.8712311f, 8.7311306f, -58.0542183f, 657.768127f, 1.0f, "beach_3_man1", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Woman", "Woman", CHR_KIND_WALKER, 0, CHR_MARK_NONE,
      -48.8936195f, 8.7311306f, -55.104641f, 645.167358f, 1.0f, "beach_3_woman", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Man2", "Man", CHR_KIND_WALKER, 0, CHR_MARK_NONE,
      -61.5377655f, 0.659129977f, -62.894558f, 710.238342f, 1.0f, "beach_3_man2", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Dog", "Dog", CHR_KIND_DOG, 0, CHR_MARK_A | CHR_VOL_ATTACK,
      7.06283808f, 10.4836693f, -7.68487787f, 215.549942f, 1.0f, 0, 0.0f,
      {6.64566565f,10.2460155f,-7.81943274f,-54.3691292f}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {9.09999943f,14.9549971f,{1.80001783f,14.2548676f,11.1866894f,-1.26825643f},{-18.8621483f,-16.8692055f,2.30813217f,0.315176725f}} },
    { "Seagull", "Seagull", CHR_KIND_SEAGULL, 0, CHR_MARK_A | CHR_VOL_SIGHT | CHR_VOL_HOME,
      -64.4804916f, 1.12900233f, -26.6635551f, -340.730042f, 1.0f, 0, 0.0f,
      {-88.1431198f,11.9800129f,-19.4950428f,-22.6205578f}, {0,0,0,0},
      {-1.50000024f,9.97999859f,{-57.0281792f,-40.2679176f,-57.670742f,-74.4308853f},{-45.3513222f,-13.5359058f,-4.36815977f,-36.1836586f}},
      {0.199999094f,2.90999794f,{-64.8169556f,-64.4679108f,-63.7298965f,-64.0791168f},{-25.1618938f,-26.5589962f,-26.3769989f,-24.9799347f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Crab", "Crab", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      -65.8650818f, 2.40686584f, -34.9403419f, 733.200195f, 2.0f, 0, 0.0f,
      {-71.3001099f,0.815999389f,-33.0371742f,184.543961f}, {-65.0944443f,2.40199828f,-35.5630455f,23.3994579f},
      {-1.6500001f,11.0649977f,{-77.8962097f,-61.8294868f,-49.6729813f,-65.7397766f},{-48.2171478f,-55.0899963f,-26.6705227f,-19.7978859f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Seagull_2", "Seagull", CHR_KIND_SEAGULL, 0, CHR_MARK_A | CHR_VOL_SIGHT | CHR_VOL_HOME,
      -59.0313454f, 1.94300234f, -19.8447876f, -318.740082f, 1.0f, 0, 0.0f,
      {-85.335968f,9.70001411f,-7.63522863f,12.7794447f}, {0,0,0,0},
      {-1.50000024f,9.97999859f,{-57.0281792f,-40.2679176f,-57.670742f,-74.4308853f},{-45.3513222f,-13.5359058f,-4.36815977f,-36.1836586f}},
      {0.199999094f,3.99999785f,{-58.7889404f,-59.6588097f,-59.0596581f,-58.1899071f},{-18.7337856f,-19.6034355f,-20.2065353f,-19.3367577f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

static const chr_place_t CHR_PLACE_BEACH_4[] = {
    { "Dog", "Dog", CHR_KIND_DOG, 0, CHR_VOL_ATTACK,
      23.4366627f, 0.307672322f, 48.6662827f, 319.619812f, 1.0f, 0, 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {-0.72000134f,7.45499611f,{12.0862207f,26.0998287f,30.7267342f,16.713089f},{53.7466011f,40.1389732f,44.9031334f,58.510849f}} },
    { "Btr", "Btr", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      0.0f, 0.0f, 0.0f, 0.0f, 1.0f, "rdc_beach_4_forw", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Guard", "Guard", CHR_KIND_GUARD, 0, CHR_VOL_SIGHT | CHR_VOL_HOME,
      39.6145973f, 2.85751081f, 18.5694599f, 501.734161f, 1.0f, 0, 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {-1.20000029f,8.5799818f,{24.0552998f,17.2353764f,53.1455574f,59.9655609f},{29.0651817f,16.8270893f,-3.18496704f,9.05303383f}},
      {1.51999998f,6.10998392f,{44.9245491f,48.5908508f,36.0747795f,32.408432f},{8.70562649f,13.9513998f,22.6988773f,17.4531555f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

static const chr_place_t CHR_PLACE_COUNTRY_1[] = {
    { "Dog", "Dog", CHR_KIND_DOG, 0, CHR_VOL_ATTACK,
      5.54451323f, 0.427671999f, -30.2188721f, 628.664734f, 1.0f, 0, 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {-0.235001266f,4.65999508f,{8.96076965f,8.45443916f,0.411906004f,0.918216944f},{-38.2231979f,-21.5675449f,-21.811554f,-38.4672241f}} },
    { "Spider1", "Spider", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      27.0942459f, -1.49699926f, -7.44817209f, 71.1300125f, 1.70000005f, 0, 0.0f,
      {33.014698f,-1.79200053f,-6.79077005f,83.5643463f}, {26.4992523f,-1.85600066f,-6.24541616f,69.7047653f},
      {-6.05000019f,1.50499821f,{17.4267902f,24.8167343f,45.745182f,38.3550568f},{-8.78672409f,-17.5130138f,0.211162567f,8.93730736f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Spider2", "Spider", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      -3.46071148f, -1.49699926f, 22.7711067f, -81.8099976f, 1.70000005f, 0, 0.0f,
      {-9.25069618f,-1.05200064f,28.0047302f,-53.3256607f}, {-3.75827503f,-1.41200089f,21.8378716f,291.644806f},
      {-6.05000019f,1.50499821f,{7.20158577f,9.45006561f,-15.5868073f,-17.8350677f},{17.6991882f,28.910965f,33.9315186f,22.719696f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Spider3", "Spider", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      16.8117409f, 1.32300079f, 11.1800957f, 101.100014f, 1.70000005f, 0, 0.0f,
      {16.3019886f,0.0799992457f,13.9739084f,-316.815765f}, {20.7543659f,0.247999504f,5.79428101f,126.704811f},
      {-1.36999989f,6.18499851f,{30.8380394f,22.8389435f,1.93660736f,9.93589592f},{7.40872955f,22.8667145f,12.0499487f,-3.40793705f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

static const chr_place_t CHR_PLACE_COUNTRY_2[] = {
    { "Vulture1", "Vulture", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -48.0264854f, 13.3279905f, 22.4255295f, 223.260086f, 0.5f, "vlt_country_2_1", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Vulture2", "Vulture", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -48.0264854f, 13.3279905f, 22.4255295f, 223.260086f, 0.5f, "vlt_country_2_2", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Vulture3", "Vulture", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -48.0264854f, 13.3279905f, 22.4255295f, 223.260086f, 0.5f, "vlt_country_2_1", 0.5f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Vulture4", "Vulture", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -48.0264854f, 13.3279905f, 22.4255295f, 223.260086f, 0.5f, "vlt_country_2_2", 0.5f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Dog", "Dog", CHR_KIND_DOG, 0, CHR_MARK_A | CHR_VOL_ATTACK,
      31.9410782f, 8.3539629f, 30.9060555f, 103.662666f, 1.0f, 0, 0.0f,
      {32.627224f,8.70659637f,31.0979786f,-170.387314f}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {7.4149971f,12.3099918f,{27.2994232f,37.325985f,28.8189716f,18.792347f},{17.0268211f,37.6855278f,41.8147545f,21.1560326f}} },
};

static const chr_place_t CHR_PLACE_COUNTRY_3[] = {
    { "Dog_Na_Plyazhe", "Dog", CHR_KIND_DOG, 0, CHR_MARK_A | CHR_VOL_ATTACK,
      53.6750755f, 0.611672401f, -8.99787521f, 580.574219f, 1.0f, 0, 0.0f,
      {51.8154564f,1.05001998f,-9.0277729f,297.620911f}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {-0.235001266f,4.65999508f,{45.280201f,56.3302841f,61.6198692f,50.5697708f},{-8.42797756f,-18.0668926f,-12.0037241f,-2.36476851f}} },
    { "Dog_V_Derevne", "Dog", CHR_KIND_DOG, 0, CHR_MARK_A | CHR_VOL_ATTACK,
      -92.8056641f, 1.08367455f, -3.35243106f, 730.034973f, 1.0f, 0, 0.0f,
      {-92.8232956f,0.7420187f,-3.4063406f,360.920746f}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {-0.235001266f,3.17499542f,{-99.6750259f,-88.49263f,-86.5316315f,-97.7140808f},{-7.45705605f,-9.26962185f,2.82364988f,4.63624763f}} },
    { "Seagull_Na_Kamne", "Seagull", CHR_KIND_SEAGULL, 0, CHR_MARK_A | CHR_VOL_SIGHT | CHR_VOL_HOME,
      -25.9988251f, -0.859999001f, 3.38209295f, -75.4249573f, 1.0f, 0, 0.0f,
      {-32.7162285f,7.9919982f,32.3436432f,43.1396027f}, {0,0,0,0},
      {-1.50000024f,11.0099993f,{-10.6609459f,-9.37367439f,-43.725563f,-45.0126839f},{-13.129425f,8.99322414f,10.9919233f,-11.1307821f}},
      {-1.80000019f,2.51999378f,{-28.2654705f,-27.3794498f,-26.0370693f,-26.9232216f},{5.02158356f,2.74809408f,3.26946831f,5.54291821f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Seagull_Na_Playzhe", "Seagull", CHR_KIND_SEAGULL, 0, CHR_MARK_A | CHR_VOL_SIGHT | CHR_VOL_HOME,
      -33.530777f, -0.699998856f, 2.71771574f, -116.164955f, 1.0f, 0, 0.0f,
      {-25.724474f,10.7400074f,27.9296188f,43.1396027f}, {0,0,0,0},
      {-1.50000024f,11.0099993f,{-13.756567f,-30.8824425f,-51.22089f,-34.0948868f},{3.08559895f,17.133009f,-7.66279125f,-21.7101231f}},
      {-1.80000019f,2.51999378f,{-36.0980415f,-31.8798199f,-32.7039909f,-36.922184f},{0.0563277677f,1.50497222f,3.9076159f,2.45883846f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Crab", "Crab", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      44.261013f, 0.536867201f, -3.60110641f, 485.100037f, 2.0f, 0, 0.0f,
      {47.0189056f,-1.75200021f,1.2476244f,-237.735809f}, {44.7699928f,0.22999911f,-6.57331133f,-244.800583f},
      {-1.6500001f,8.56499863f,{33.4527473f,32.3195076f,54.421833f,55.5548592f},{2.6716435f,-12.3306589f,-13.9999056f,1.00239646f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Spider_Do_Mosta", "Spider", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      7.7668252f, 4.22100115f, -32.268959f, -55.3199959f, 1.70000005f, 0, 0.0f,
      {2.35179329f,4.71999931f,-24.1861935f,-49.9956512f}, {10.39569f,3.95999932f,-35.4828377f,-262.425385f},
      {1.94999993f,9.50499821f,{1.10769236f,-4.90788507f,15.0142145f,21.0295982f},{-19.9768448f,-29.7016659f,-42.0245552f,-32.2996063f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Spider_Za_Mostom", "Spider", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      -28.0168171f, 4.71700191f, -22.3369808f, -109.260002f, 1.70000005f, 0, 0.0f,
      {-35.3084335f,4.30799913f,-22.4416504f,59.5643692f}, {-32.6263962f,4.35800076f,-25.5673943f,-440.415405f},
      {1.94999993f,9.50499821f,{-41.1046829f,-43.405983f,-20.4599113f,-18.1588478f},{-15.3370247f,-26.538065f,-31.2520142f,-20.0508938f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

static const chr_place_t CHR_PLACE_COUNTRY_4[] = {
    { "Dog_Na_Starte", "Dog", CHR_KIND_DOG, 1, CHR_MARK_A | CHR_VOL_ATTACK,
      -22.1347656f, 1.9316889f, 25.6456051f, 337.632904f, 1.0f, 0, 0.0f,
      {-23.0685177f,1.71002293f,29.1851101f,480.229614f}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0.69499892f,8.08999538f,{-29.6415482f,-14.8222885f,-15.3078165f,-30.1271172f},{20.7788181f,21.4239616f,32.5896111f,31.944521f}} },
    { "Guard_Na_Baze", "Guard", CHR_KIND_GUARD, 0, CHR_VOL_SIGHT | CHR_VOL_HOME,
      11.7938423f, 2.98100591f, 15.4742451f, 315.553955f, 1.0f, 0, 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {2.54999995f,8.42998219f,{7.43545055f,-0.340987235f,17.5696507f,25.346159f},{30.1752052f,21.8940468f,5.07469845f,13.3558178f}},
      {2.14000034f,6.26998281f,{8.72752476f,5.20710754f,12.7156639f,16.2361221f},{21.0406723f,17.2681179f,10.2614727f,14.0339851f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Guard_U_Boegolovki", "Guard", CHR_KIND_GUARD, 0, CHR_VOL_SIGHT | CHR_VOL_HOME,
      25.7476883f, -0.0134892836f, 26.6951485f, 399.523956f, 1.0f, 0, 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {-1.20000029f,8.5799818f,{35.9387016f,16.3245144f,46.7228737f,66.3370819f},{49.363266f,21.5789394f,0.119303316f,27.9035397f}},
      {-0.829999804f,6.41998291f,{22.6729145f,26.366827f,32.0694885f,28.3756104f},{24.9476795f,22.3602066f,30.501564f,33.0890732f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "RepairMan", "RepairMan", CHR_KIND_WALKER, 0, CHR_MARK_NONE,
      3.87672567f, 3.235672f, -5.56973696f, 134.670258f, 1.0f, "country_4_repairman", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

static const chr_place_t CHR_PLACE_URBAN_1[] = {
    { "Guard1", "Guard", CHR_KIND_GUARD, 0, CHR_VOL_SIGHT | CHR_VOL_HOME,
      -42.220108f, 4.93851137f, 31.2032509f, 631.993591f, 1.0f, 0, 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {-0.265000463f,12.5699778f,{-62.3067398f,-26.1690407f,-26.0154591f,-62.1530495f},{21.6270809f,21.2108097f,34.5398369f,34.9562111f}},
      {-0.265000463f,7.33997869f,{-47.3275375f,-39.0279388f,-38.9966393f,-47.2961044f},{29.7390766f,29.6447563f,32.3644753f,32.4588966f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Hammer", "Hammer", CHR_KIND_PATH, 0, CHR_MARK_NONE,
      -19.5756874f, 8.07397938f, 43.1547699f, 1357.65442f, 1.0f, "rdc_urban_1_forw", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Guard2", "Guard", CHR_KIND_GUARD, 0, CHR_VOL_SIGHT | CHR_VOL_HOME,
      21.7731285f, 4.97718239f, 26.6000137f, 84.9742584f, 1.0f, 0, 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {-1.20000029f,11.5399809f,{53.6698036f,6.23595905f,6.4868536f,53.9206276f},{32.8975525f,32.1275635f,16.6696815f,17.4396267f}},
      {-0.829999804f,9.5399828f,{20.0608711f,20.0751419f,32.6750298f,32.66082f},{28.7870045f,23.337038f,23.370079f,28.8200531f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "Spider", "Spider", CHR_KIND_BURROW, 0, CHR_MARK_A | CHR_MARK_B | CHR_VOL_SIGHT,
      -12.3121939f, 7.64400244f, 35.5917282f, 122.64003f, 1.70000005f, 0, 0.0f,
      {-6.15996456f,7.86800003f,31.4712963f,132.554321f}, {-12.5763502f,7.71999979f,35.277359f,-634.90509f},
      {7.12000084f,14.6749973f,{-27.2390022f,-32.1686401f,-1.18388665f,3.7455349f},{43.3293533f,28.7818985f,18.2826443f,32.8301697f}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

static const chr_place_t CHR_PLACE_URBAN_2[] = {
    { "Guard", "Guard", CHR_KIND_GUARD, 0, CHR_VOL_SIGHT | CHR_VOL_HOME,
      55.436409f, -2.49458456f, -24.3120327f, 812.144043f, 1.0f, 0, 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {-3.20000029f,6.5799818f,{79.0506592f,78.723732f,35.5177879f,35.8446121f},{-38.3169327f,-14.3090363f,-14.8971958f,-38.904995f}},
      {-2.69999981f,2.66998291f,{52.3084641f,51.7923584f,65.4973907f,66.0135422f},{-14.4463034f,-25.5142574f,-26.1532631f,-15.0853138f}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
    { "RepairMan", "RepairMan", CHR_KIND_WALKER, 0, CHR_MARK_NONE,
      47.2589035f, -2.52032876f, 31.6885223f, 359.640381f, 1.0f, "urban_2_repairman", 0.0f,
      {0,0,0,0}, {0,0,0,0},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}},
      {0,0,{0,0,0,0},{0,0,0,0}} },
};

typedef struct {
    const char *track;
    const chr_place_t *place;
    unsigned int n;
} chr_track_t;

static const chr_track_t CHR_TRACKS[] = {
    { "beach_1", CHR_PLACE_BEACH_1, 6 },
    { "beach_2", CHR_PLACE_BEACH_2, 11 },
    { "beach_3", CHR_PLACE_BEACH_3, 13 },
    { "beach_4", CHR_PLACE_BEACH_4, 3 },
    { "country_1", CHR_PLACE_COUNTRY_1, 4 },
    { "country_2", CHR_PLACE_COUNTRY_2, 5 },
    { "country_3", CHR_PLACE_COUNTRY_3, 7 },
    { "country_4", CHR_PLACE_COUNTRY_4, 4 },
    { "urban_1", CHR_PLACE_URBAN_1, 4 },
    { "urban_2", CHR_PLACE_URBAN_2, 2 },
};
#define CHR_N_TRACKS 10
#define CHR_N_PLACEMENTS 59

#endif /* CHAR_DATA_H */
