/* Generated by rccars_re/gen_dlg_data.py -- do not edit.
 *
 * THE ENGINE'S OWN DIALOG LAYOUTS, read out of Settings/dlg*.ini --
 * one file per screen, each a list of `Key "<control><field>"' with
 * X0/Y0/SX/SY in the 800x600 frame the whole interface is authored
 * in (HUD_REF_W/H). A key with a `Mask float' is a percent carried as
 * an integer and comes out here as a FRACTION.
 *
 * The exe reads these through the same config getter every other .ini
 * goes through, which is why `tableWidth%i' is in the binary as a
 * format string. See gen_dlg_data.py. */
#ifndef DLG_DATA_H
#define DLG_DATA_H

/* dlgFINISH.ini -- 49 keys */
#define DLG_FINISH_rectFrameX0                   5.f
#define DLG_FINISH_rectFrameY0                   20.f
#define DLG_FINISH_rectFrameSX                   788.f
#define DLG_FINISH_rectFrameSY                   570.f
#define DLG_FINISH_tableFinishX0                 87.f
#define DLG_FINISH_tableFinishY0                 35.f
#define DLG_FINISH_tableFinishSX                 597.f
#define DLG_FINISH_tableFinishSY                 315.f
#define DLG_FINISH_tableWidth0                   0.0800f   /* 8% */
#define DLG_FINISH_tableWidth1                   0.1900f   /* 19% */
#define DLG_FINISH_tableWidth2                   0.0900f   /* 9% */
#define DLG_FINISH_tableWidth3                   0.1600f   /* 16% */
#define DLG_FINISH_tableWidth4                   0.1400f   /* 14% */
#define DLG_FINISH_tableWidth5                   0.1400f   /* 14% */
#define DLG_FINISH_tableHeaderHeight             0.1000f   /* 10% */
#define DLG_FINISH_tableItemHeight               0.1500f   /* 15% */
#define DLG_FINISH_buttonAbortX0                 244.f
#define DLG_FINISH_buttonAbortY0                 535.f
#define DLG_FINISH_buttonAbortSX                 150.f
#define DLG_FINISH_buttonAbortSY                 33.f
#define DLG_FINISH_staticBonusAllowedX0          173.f
#define DLG_FINISH_staticBonusAllowedY0          394.f
#define DLG_FINISH_staticBonusAllowedSX          458.f
#define DLG_FINISH_staticBonusAllowedSY          108.f
#define DLG_FINISH_staticBonusGainedX0           280.f
#define DLG_FINISH_staticBonusGainedY0           470.f
#define DLG_FINISH_staticBonusGainedSX           241.f
#define DLG_FINISH_staticBonusGainedSY           45.f
#define DLG_FINISH_staticBonusGainedCashX0       284.f
#define DLG_FINISH_staticBonusGainedCashY0       480.f
#define DLG_FINISH_staticBonusGainedCashSX       241.f
#define DLG_FINISH_staticBonusGainedCashSY       45.f
#define DLG_FINISH_staticBonusCashX0             173.f
#define DLG_FINISH_staticBonusCashY0             320.f
#define DLG_FINISH_staticBonusCashSX             456.f
#define DLG_FINISH_staticBonusCashSY             108.f
#define DLG_FINISH_tableBonusX0                  85.f
#define DLG_FINISH_tableBonusY0                  399.f
#define DLG_FINISH_tableBonusSX                  611.f
#define DLG_FINISH_tableBonusSY                  55.f
#define DLG_FINISH_tableBonusWidth0              0.3200f   /* 32% */
#define DLG_FINISH_tableBonusWidth1              0.0800f   /* 8% */
#define DLG_FINISH_tableBonusWidth2              0.1300f   /* 13% */
#define DLG_FINISH_tableBonusWidth3              0.3900f   /* 39% */
#define DLG_FINISH_tableBonusWidth4              0.0800f   /* 8% */
#define DLG_FINISH_tableMordaShift               0.0900f   /* 9% */
#define DLG_FINISH_buttonRaceAgainX0             407.f
#define DLG_FINISH_buttonRaceAgainY0             535.f
#define DLG_FINISH_buttonRaceAgainSX             34.f

/* dlgRACESUM.ini -- 48 keys */
#define DLG_RACESUM_shotTrackX0                  110.f
#define DLG_RACESUM_shotTrackY0                  82.f
#define DLG_RACESUM_shotTrackSX                  196.f
#define DLG_RACESUM_shotTrackSY                  153.f
#define DLG_RACESUM_enumTrackX0                  71.f
#define DLG_RACESUM_enumTrackY0                  191.f
#define DLG_RACESUM_enumTrackSX                  273.f
#define DLG_RACESUM_enumTrackSY                  25.f
#define DLG_RACESUM_enumTrackSE                  0.0000f   /* 0% */
#define DLG_RACESUM_staticTrackNameX0            323.f
#define DLG_RACESUM_staticTrackNameY0            70.f
#define DLG_RACESUM_staticTrackNameSX            197.f
#define DLG_RACESUM_staticTrackNameSY            40.f
#define DLG_RACESUM_staticTrackInfoX0            323.f
#define DLG_RACESUM_staticTrackInfoY0            112.f
#define DLG_RACESUM_staticTrackInfoSX            219.f
#define DLG_RACESUM_staticTrackInfoSY            80.f
#define DLG_RACESUM_enumNLapsX0                  115.f
#define DLG_RACESUM_enumNLapsY0                  265.f
#define DLG_RACESUM_enumNLapsSX                  450.f
#define DLG_RACESUM_enumNLapsSY                  25.f
#define DLG_RACESUM_enumNLapsSE                  0.4400f   /* 44% */
#define DLG_RACESUM_enumSkillX0                  115.f
#define DLG_RACESUM_enumSkillY0                  300.f
#define DLG_RACESUM_enumSkillSX                  450.f
#define DLG_RACESUM_enumSkillSY                  25.f
#define DLG_RACESUM_enumSkillSE                  0.4400f   /* 44% */
#define DLG_RACESUM_animCarX0                    306.f
#define DLG_RACESUM_animCarY0                    254.f
#define DLG_RACESUM_animCarSX                    374.f
#define DLG_RACESUM_animCarSY                    304.f
#define DLG_RACESUM_enumCarX0                    311.f
#define DLG_RACESUM_enumCarY0                    392.f
#define DLG_RACESUM_enumCarSX                    304.f
#define DLG_RACESUM_enumCarSY                    25.f
#define DLG_RACESUM_enumCarSE                    0.0000f   /* 0% */
#define DLG_RACESUM_staticCarNameX0              115.f
#define DLG_RACESUM_staticCarNameY0              387.f
#define DLG_RACESUM_staticCarNameSX              194.f
#define DLG_RACESUM_staticCarNameSY              25.f
#define DLG_RACESUM_staticCarInfoX0              85.f
#define DLG_RACESUM_staticCarInfoY0              413.f
#define DLG_RACESUM_staticCarInfoSX              225.f
#define DLG_RACESUM_staticCarInfoSY              110.f
#define DLG_RACESUM_staticClosedInfoX0           159.f
#define DLG_RACESUM_staticClosedInfoY0           196.f
#define DLG_RACESUM_staticClosedInfoSX           100.f
#define DLG_RACESUM_staticClosedInfoSY           25.f

/* dlgMAIN.ini -- 25 keys */
#define DLG_MAIN_animPrevCarX0                   188.f
#define DLG_MAIN_animPrevCarY0                   197.f
#define DLG_MAIN_animPrevCarSX                   320.f
#define DLG_MAIN_animPrevCarSY                   240.f
#define DLG_MAIN_shotListTracksX0                223.f
#define DLG_MAIN_shotListTracksY0                269.f
#define DLG_MAIN_shotListTracksSX                199.f
#define DLG_MAIN_shotListTracksSY                152.f
#define DLG_MAIN_shotListTracksBoundL            12.f
#define DLG_MAIN_shotListTracksBoundUp           303.f
#define DLG_MAIN_shotListTracksBoundR            632.f
#define DLG_MAIN_shotListTracksBoundSY           76.f
#define DLG_MAIN_shotListTracksBoundSpace        3.f
#define DLG_MAIN_staticInfoHeaderX0              233.f
#define DLG_MAIN_staticInfoHeaderY0              417.f
#define DLG_MAIN_staticInfoHeaderSX              174.f
#define DLG_MAIN_staticInfoHeaderSY              30.f
#define DLG_MAIN_staticInfoX0                    234.f
#define DLG_MAIN_staticInfoY0                    449.f
#define DLG_MAIN_staticInfoSX                    240.f
#define DLG_MAIN_staticInfoSY                    140.f
#define DLG_MAIN_chatRaceX0                      20.f
#define DLG_MAIN_chatRaceY0                      260.f
#define DLG_MAIN_chatRaceSX                      400.f
#define DLG_MAIN_chatRaceSY                      170.f

#endif /* DLG_DATA_H */
