/* Generated by rccars_re/gen_fx_data.py -- do not edit.
 *
 * The wheel dust, the exhaust smoke, the tyre marks and the body
 * glance, as the game itself configures them. Every value here is
 * raw/scale through FUN_00532410, with the scale read off the push
 * immediate at the call site; the loader each group comes from is
 * named above it. See gen_fx_data.py's docstring.
 *
 * All four effects ship ENABLED: RCCars.crs sets VIDEO_DustEff,
 * VIDEO_ExhaustGas, VIDEO_WheelTrace and VIDEO_EnvMap to 1.
 */

#ifndef FX_DATA_H
#define FX_DATA_H

#include "rb.h"          /* rb_curve_pt */

/* ---- car_dustx, FUN_0052ea60 -------------------------------- */
#define DUSTX_GRAVITY_Y            0.000000f   /* GravityY 0/-100 -- m/s^2 on the dust, +y */
#define DUSTX_DX                   6.100000f   /* DX 61/10 -- system +0xa0; not recovered */
#define DUSTX_DY                   6.100000f   /* DY 61/10 -- system +0xac; not recovered */
#define DUSTX_TWIST                1.640000f   /* TwistSpeed 164/100 -- sprite spin, turns/s */
#define DUSTX_SCALE_X              1.500000f   /* ScaleX 150/100 -- sprite half-width */
#define DUSTX_SCALE_X_DISP         0.500000f   /* ScaleXDisp 50/100 -- +- random on ScaleX */
#define DUSTX_SCALE_Y              1.500000f   /* ScaleY 150/100 -- sprite half-height */
#define DUSTX_SCALE_Y_DISP         0.500000f   /* ScaleYDisp 50/100 -- +- random on ScaleY */
#define DUSTX_DYN_SCALE            32.500000f   /* DynamicScale 325/10 -- growth over life, spinning */
#define DUSTX_DYN_SCALE_FORW       25.000000f   /* DynamicScaleForw 250/10 -- growth over life, rolling */
#define DUSTX_SPEED_ATT            0.100000f   /* SpeedAtt 10/100 -- velocity decay per second */
#define DUSTX_SPIN_THRESH          0.300000f   /* WheelSpinThresh 30/100 -- slip above which it is spin */
#define DUSTX_SPIN_SCALE           0.490000f   /* WheelSpinScale 49/100 -- rate multiplier when spinning */
#define DUSTX_SPIN_SPEED           0.250000f   /* WheelSpinSpeed 25/100 -- throw-back speed per unit slip */
#define DUSTX_SHIFT_X              0.060000f   /* ShiftX 6/100 -- front pair emit shift, inboard */
#define DUSTX_ZIGNORE_RAD          2.000000f   /* ZIgnoreRad 20/10 -- hide a particle nearer than this */

/* ScaleX/ScaleY are MULTIPLIERS, not metres. What they multiply is
   the particle system's own base sprite size, set by FUN_00477940,
   which is not transcribed -- so the port supplies the base (see
   fx.c's FX_SPRITE_UNIT) and applies these on top of it.

   DynamicScale/DynamicScaleForw are the growth over a particle's life,
   and FUN_0052e180 picks between them on the WHEEL INDEX -- < 2 gets
   ...Forw, so the front pair's dust grows less than the rear's. */

/* The sprite, FUN_0046e180("dust"). Both systems share it. */
#define FX_DUST_TEX  "dust"

/* ---- exhausted_gas, FUN_005308f0 ---------------------------- */
#define EG_GRAVITY_Y               0.000000f   /* GravityY 0/-100 -- m/s^2 on the smoke, +y */
#define EG_DX                      2.800000f   /* DX 28/10 -- system +0xa0; not recovered */
#define EG_DY                      2.800000f   /* DY 28/10 -- system +0xac; not recovered */
#define EG_TWIST                   1.640000f   /* TwistSpeed 164/100 -- sprite spin, turns/s */
#define EG_SCALE_X                 1.500000f   /* ScaleX 150/100 -- sprite half-width */
#define EG_SCALE_X_DISP            0.500000f   /* ScaleXDisp 50/100 -- +- random on ScaleX */
#define EG_SCALE_Y                 1.500000f   /* ScaleY 150/100 -- sprite half-height */
#define EG_SCALE_Y_DISP            0.500000f   /* ScaleYDisp 50/100 -- +- random on ScaleY */
#define EG_DYN_SCALE               30.300000f   /* DynamicScale 303/10 -- growth over life */
#define EG_SPEED                   0.980000f   /* Speed 98/100 -- ejection speed along the pipe */
#define EG_SPEED_ATT               0.100000f   /* SpeedAtt 10/100 -- velocity decay per second */
#define EG_LIFE                    0.060000f   /* TimeLife 6/100 -- seconds */
#define EG_LIFE_DISP               0.000000f   /* TimeLifeDisp 0/100 -- +- random on TimeLife */
#define EG_EXPLODE_TIME            0.400000f   /* ExplodeTime 40/100 -- backfire hold, seconds */
#define EG_EXPLODE_COLOR           0.160000f   /* ExplodeColor 16/100 -- backfire grey floor, 0..1 */
#define EG_EXPLODE_ALPHA           0.090000f   /* ExplodeAlpha 9/100 -- unused by the port */
#define EG_SPIN_THRESH             0.100000f   /* WheelSpin 10/100 -- slip above which the pipe puffs */

/* ---- car_trace, FUN_005300e0 -------------------------------- */
#define TRACE_LIFE                 60.000000f   /* timeLife 60/1 -- seconds a mark survives */
#define TRACE_MAX_LEN              1.000000f   /* maxLen 100/100 -- metres between samples before a break */
#define TRACE_SCALE_COEFF          3.280000f   /* scaleCoeff 328/100 -- texture repeats per metre */
#define TRACE_MAX_HEIGHT           0.090000f   /* maxHeight -- ABSENT; 90/1000 from car_trace.ini's second, misnamed maxLen. See gen_fx_data.maxheight() */

/* The ring, FUN_0052f050: 0x20 slots for wheels 0 and 1, 0x30 for
   the rest, halved for a car that is not a player's. */
#define TRACE_RING_FRONT           32   /* 0x20 at 0x0052f0a4 */
#define TRACE_RING_REAR            48   /* 0x30 at 0x0052f0ad */
#define TRACE_WHEELS               6   /* the loop bound in FUN_0052f050 */

/* The four marks, sprintf("t_halfdry_tire2_%d") in FUN_0052f050. */
#define TRACE_TEX_N                4   /* the loop bound in FUN_0052f050 */
#define TRACE_TEX_FMT  "t_halfdry_tire2_%d"

/* FUN_0052ff20 nudges each strip 2e-05 further along the depth
   range than the last, so overlapping marks do not z-fight. */
#define TRACE_DEPTH_STEP           0.000020f   /* 0x0052ffe8 */

/* ---- surf_<kind>, FUN_0052ed30 ------------------------------ */
/* Indexed by the engine's own surface id (FUN_0052ee10's switch):
   0 default, 1 sand, 2 wetsand, 3 dunesand, 5 stone road. 4 and
   anything else fall to default, whose IntScale is 0 -- so asphalt,
   grass, metal and wood raise NO dust, which is the original. */
typedef struct {
    float int_scale;    /* DustX_IntScale, rate multiplier */
    float r, g, b, a;   /* DustX_Color*, 0..255 */
    float life, life_disp;  /* DustX_TimeLife(Disp), seconds */
} fx_surf_t;

#define FX_SURF_N 6
static const fx_surf_t fx_surf[FX_SURF_N] = {
    /* 0 DEFAULT   */ { 0.0000f, 254.0f, 253.0f, 255.0f, 255.0f, 0.0000f, 0.0000f },   /* surf_default.crs */
    /* 1 SAND      */ { 1.2000f, 250.0f, 220.0f, 140.0f, 150.0f, 1.0000f, 0.2500f },   /* surf_sand.crs */
    /* 2 WETSAND   */ { 1.0000f, 190.0f, 140.0f, 80.0f, 120.0f, 0.0500f, 0.0000f },   /* surf_wetsand.crs */
    /* 3 DUNESAND  */ { 1.2000f, 255.0f, 240.0f, 180.0f, 200.0f, 1.0000f, 0.2500f },   /* surf_dunesand.crs */
    /* 4 unused    */ { 0.0000f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0000f, 0.0000f },
    /* 5 STONEROAD */ { 1.0000f, 150.0f, 150.0f, 150.0f, 200.0f, 0.1000f, 0.0000f },   /* surf_gravel.crs */
};

/* The port's own surface classes (pack_col.py / sfx.h SURF_*) mapped
   onto the engine's dust ids. sand, wetsand and gravel line up by
   name; asphalt, grass, metal, wood and water get the default table
   and so raise nothing.

   `stone` is the one judgement: the engine's id 5 is spelt
   SURF_STONEROAD in surf_gravel.crs, and the port splits that idea in
   two -- `gravel` (gravel, cobble, path) and `stone` (rock, cliff,
   brick). Both are mapped onto 5. Leaving stone on the default table
   would make 17% of the drivable area of these tracks dustless. */
#define FX_SURF_MAP { 0, 1, 2, 5, 5, 0, 0, 0, 0 }

/* ---- CarEnvMap, FUN_004f9aa0 -------------------------------- */
/* Stored as raw bytes and used as an alpha: physCreateSubsystem
   writes 0xffffff | EnvMapBody<<24 into the ENVIR_CAR_BODY material's
   colour, i.e. white at that alpha. */
#define ENVMAP_BODY                112   /* EnvMapBody -- the painted shell */
#define ENVMAP_GRE1                255   /* EnvMapGRE1 -- *_GRE1 / *_GER1 -- glass and chrome */
#define ENVMAP_GRE2                137   /* EnvMapGRE2 -- *_GRE2 / *_GER2 -- lamps, bumpers, underside */
#define ENVMAP_UPGRADES            156   /* EnvMapUpgrades -- the bolt-on exhaust */

/* The env-map source is the texture Car.sb declares as S_SKY: the
   ONLY declaration in the whole database with no source path, so the
   engine fills it at runtime. The port binds the track's own sky. */

/* ---- curves ------------------------------------------------- */
/* dust_int.spl: 3 Bezier segments -> 25 points */
static const rb_curve_pt fx_dust_int[] = {{-32.5300f,16.2650f}, {-27.7543f,15.1065f}, {-24.6473f,12.1431f}, {-22.4669f,8.1432f}, {-20.4709f,3.8750f}, {-17.9170f,0.1069f}, {-14.0630f,-2.3928f}, {-8.1667f,-2.8559f}, {0.5140f,-0.5140f}, {8.0372f,8.8919f}, {12.1787f,27.7964f}, {14.7939f,52.6402f}, {17.7385f,79.8644f}, {22.8678f,105.9097f}, {32.0373f,127.2170f}, {47.1026f,140.2271f}, {69.9190f,141.3810f}, {78.1062f,139.1725f}, {84.4261f,134.2828f}, {89.3583f,127.6291f}, {93.3829f,120.1284f}, {96.9795f,112.6980f}, {100.6280f,106.2550f}, {104.8082f,101.7166f}, {110.0000f,100.0000f}};
#define FX_DUST_INT_N 25

/* dust_speed.spl: 3 Bezier segments -> 21 points, 4 dropped as non-monotonic */
static const rb_curve_pt fx_dust_speed[] = {{-10.0000f,0.0000f}, {-5.7383f,0.5701f}, {-4.0611f,2.1193f}, {-4.0580f,4.4056f}, {-2.5781f,16.0881f}, {2.7110f,18.4340f}, {11.0691f,20.8255f}, {21.6186f,23.8941f}, {33.6672f,27.5695f}, {46.5227f,31.7815f}, {59.4930f,36.4598f}, {71.8856f,41.5342f}, {83.0083f,46.9343f}, {92.1690f,52.5900f}, {98.3807f,59.0369f}, {101.7014f,66.4774f}, {103.0078f,74.3404f}, {103.1762f,82.0546f}, {103.6052f,94.7520f}, {105.6186f,98.5928f}, {110.0000f,100.0000f}};
#define FX_DUST_SPEED_N 21

/* eg_int.spl: 3 Bezier segments -> 25 points */
static const rb_curve_pt fx_eg_int[] = {{-32.5300f,16.2650f}, {-27.7543f,15.1065f}, {-24.6473f,12.1431f}, {-22.4669f,8.1432f}, {-20.4709f,3.8750f}, {-17.9170f,0.1069f}, {-14.0630f,-2.3928f}, {-8.1667f,-2.8559f}, {0.5140f,-0.5140f}, {8.0372f,8.8919f}, {12.1787f,27.7964f}, {14.7939f,52.6402f}, {17.7385f,79.8644f}, {22.8678f,105.9097f}, {32.0373f,127.2170f}, {47.1026f,140.2271f}, {69.9190f,141.3810f}, {78.1062f,139.1725f}, {84.4261f,134.2828f}, {89.3583f,127.6291f}, {93.3829f,120.1284f}, {96.9795f,112.6980f}, {100.6280f,106.2550f}, {104.8082f,101.7166f}, {110.0000f,100.0000f}};
#define FX_EG_INT_N 25

#endif
