/* Generated by rccars_re/gen_hud_data.py -- do not edit.
 *
 * The in-race HUD's data, every number out of the shipped game: the
 * minimap's per-track world->art transform and its panel shape out of
 * RCCars.exe's .data, the screen layout out of the shipped Settings sliders, and the
 * engine's own Smash font out of Language/English. See the generator's
 * docstring for the address or the key behind each block. */
#ifndef HUD_DATA_H
#define HUD_DATA_H

/* THE FRAME EVERY PIXEL POSITION BELOW IS IN. RC Cars is a 2003 PC game
   and its HUD was authored at 800x600: map.ini's two sliders run 0..800
   and 0..600 exactly, and cockpit.ini's float ranges are -100..800 and
   -100..600. race_ui.c scales UNIFORMLY off the height and anchors each
   group to the edge it was authored against, so 4:3 art is not stretched
   4/3 wider on a 16:9 panel -- the same rule hud.h states for the
   message layer. */
#define HUD_REF_W 800.f
#define HUD_REF_H 600.f

/* ------------------------------------------------------- the minimap */

/* map.ini mapPosX_0 / mapPosY_0, raw pixels: the panel's top-left corner.
   The _1 pair (620, 401) is the second player's, for a split screen this
   port does not have; there is no unsuffixed pair in the file, so _0 is
   what single-player uses. */
#define MAP_POS_X 620.0f
#define MAP_POS_Y 79.0f

/* The panel's side, in the same pixels. 0x4b79ea puts every outline point
   through (u * 167.0 - 83.5) * 1/512, i.e. it centres u about 0.5 and
   scales it to a half-extent of 83.5 -- so the panel is 167 px across in
   the authored frame. Measured off the game's OWN screenshot of its HUD
   (Textures.1/opt_cock_m_1.csi, the cockpit option preview): the silver
   frame there is 167 px tall and 182 wide, so the height closes to the
   pixel and the width is 9% over. The extra width is NOT modelled -- see
   known-issues.md. */
#define MAP_SIDE 167.0f

/* The panel's own shape, 0x56db70: eight (u, v) in its own 0..1 box, four
   rows of two, which 0x4b79ea draws as a strip of three quads -- a
   rounded rectangle with clipped corners. Emitted as the raw fractions;
   race_ui.c does the centring and the scale. */
#define MAP_OUTLINE_N 8
static const float MAP_OUTLINE[MAP_OUTLINE_N][2] = {
    { 0.131737f, 0.029940f },
    { 0.874251f, 0.029940f },
    { 0.041916f, 0.113772f },
    { 0.958084f, 0.113772f },
    { 0.041916f, 0.880240f },
    { 0.958084f, 0.880240f },
    { 0.107784f, 0.952096f },
    { 0.886228f, 0.952096f },
};

/* THE WORLD -> ART TRANSFORM, per track: three world (x, z) points and
   the three art (u, v) they land on. FUN_004a9840 copies row `track` of
   0x56c378 and of 0x56c468 (24 bytes each) beside loading
   `trackmap_<track+1>`, and FUN_004b8500 solves the affine over them --
   after checking the three world points are not coincident. Three pairs
   determine an affine exactly; race_ui.c solves the same one.

   The generator CHECKS each row rather than trusting the pairing: a
   painted top-down map has to come out a uniform scale with no rotation,
   and it does on all ten. Per track (1/scale in metres across the art,
   the off-diagonal cosine, and where the race start lands):
     beach_1    195.4 x 195.3 m   cos +0.053   start (0.619, 0.392)
     beach_2    209.5 x 214.6 m   cos +0.005   start (0.741, 0.151)
     beach_3    206.2 x 217.4 m   cos +0.014   start (0.551, 0.647)
     beach_4    206.9 x 221.9 m   cos +0.011   start (0.489, 0.329)
     country_1  176.6 x 172.8 m   cos -0.010   start (0.702, 0.518)
     country_2  221.2 x 215.4 m   cos -0.052   start (0.532, 0.487)
     country_3  208.9 x 212.5 m   cos -0.003   start (0.488, 0.156)
     country_4  164.3 x 166.8 m   cos +0.018   start (0.397, 0.895)
     urban_1    188.3 x 188.3 m   cos +0.004   start (0.297, 0.788)
     urban_2    209.0 x 232.8 m   cos -0.064   start (0.472, 0.448)

   THAT IS STILL THESE TWO TABLES AGAINST EACH OTHER. Held against a
   DIFFERENT shipped artifact -- the cp_N markers in each packed .vsc
   against the ribbon as painted -- rccars_re/mapcheck.py measures 0.3 m
   of error on beach_1 and 0.7 on beach_3, and 3 to 19 m on the other
   eight. The arithmetic below IS the engine's (FUN_004b8500 + 0x410430,
   read instruction by instruction); the residual is unexplained and it is
   in known-issues.md. Run mapcheck.py after touching any of this. */
typedef struct {
    float world[3][2];   /* x, z in metres */
    float art[3][2];     /* u, v in the 512x512 trackmap */
} map_calib;

#define MAP_N_TRACKS 10
static const map_calib MAP_CALIB[MAP_N_TRACKS] = {
    /* beach_1 -- trackmap_1 */
    { { {   -18.32300f,   -10.89700f }, {   -28.02800f,    23.01600f }, {    -0.00200f,    -9.41700f } },
      { {  0.4101562f,  0.4921875f }, {  0.2441406f,  0.5566406f }, {  0.4570312f,  0.5742188f } } },
    /* beach_2 -- trackmap_2 */
    { { {    -4.72900f,   -29.40200f }, {   -57.25500f,   -27.65200f }, {     7.85800f,    23.74800f } },
      { {  0.4394531f,  0.3515625f }, {  0.2871094f,  0.5507812f }, {  0.6699219f,  0.4609375f } } },
    /* beach_3 -- trackmap_3 */
    { { {    56.99400f,   -67.27200f }, {   -48.36300f,    11.09800f }, {   -37.47200f,   -37.09000f } },
      { {  0.1445312f,  0.4335938f }, {  0.7656250f,  0.4453125f }, {  0.5937500f,  0.5937500f } } },
    /* beach_4 -- trackmap_4 */
    { { {    19.05100f,   -72.29400f }, {   -36.97800f,   -36.61000f }, {    64.69400f,    23.49400f } },
      { {  0.2128906f,  0.3828125f }, {  0.3007812f,  0.6835938f }, {  0.6875000f,  0.2734375f } } },
    /* country_1 -- trackmap_5 */
    { { {   -27.22900f,    11.02700f }, {    33.12800f,    38.58600f }, {    14.50600f,   -49.81900f } },
      { {  0.3203125f,  0.3671875f }, {  0.2988281f,  0.7421875f }, {  0.7363281f,  0.4589844f } } },
    /* country_2 -- trackmap_6 */
    { { {   -16.75900f,    39.28300f }, {   -79.66800f,   -14.82800f }, {    18.39200f,    11.45200f } },
      { {  0.5410156f,  0.6386719f }, {  0.1718750f,  0.6191406f }, {  0.5859375f,  0.4335938f } } },
    /* country_3 -- trackmap_7 */
    { { {   -72.88900f,   -34.10000f }, {   -63.04700f,    42.41100f }, {    12.70500f,    32.66700f } },
      { {  0.1445312f,  0.5351562f }, {  0.4453125f,  0.7382812f }, {  0.6503906f,  0.4355469f } } },
    /* country_4 -- trackmap_8 */
    { { {   -48.96300f,    15.00200f }, {    37.44400f,    13.42300f }, {    43.37500f,   -59.48100f } },
      { {  0.1777344f,  0.6035156f }, {  0.7031250f,  0.5859375f }, {  0.7246094f,  0.1484375f } } },
    /* urban_1 -- trackmap_9 */
    { { {   -23.31200f,    41.31500f }, {    36.89800f,    30.00500f }, {   -25.36900f,   -41.33800f } },
      { {  0.6992188f,  0.6308594f }, {  0.7226562f,  0.3066406f }, {  0.2714844f,  0.5312500f } } },
    /* urban_2 -- trackmap_10 */
    { { {    41.93200f,   -56.75800f }, {   -80.34700f,    12.02700f }, {     4.38400f,    54.51100f } },
      { {  0.4472656f,  0.7773438f }, {  0.7265625f,  0.1660156f }, {  0.3066406f,  0.2753906f } } },
};

/* ---------------------------------------- the badges and the clocks */

/* cockpit.ini. The unsuffixed keys are single-player's; the _0 / _1 pairs
   are the split screen's two halves. Each is the top-left of a 128x128
   quad drawn 1:1 -- which is what makes the negative Y right rather than
   wrong: place1..6 and lap carry 30-odd px of transparent margin above
   their word art, so the badge's INK lands on screen with the quad's own
   top edge above it. */
#define HUD_PLACE_X        25.000f   /* placePosX */
#define HUD_PLACE_Y       -20.000f   /* placePosY */
#define HUD_LAP_X         613.000f   /* lapPosX */
#define HUD_LAP_Y         -20.000f   /* lapPosY */
#define HUD_LAPNUM_X      725.000f   /* lapNumPosX */
#define HUD_LAPNUM_Y       24.000f   /* lapNumPosY */

/* The badge art is 128x128 with the word inside it -- place1..place6 and
   lap, all six places and the word, one texture each. */
#define HUD_BADGE_SIDE 128.f

/* cockpit_time.ini. Two clocks, one above the other, both centred across
   the screen: the race total and the current lap. cockpit.ini has a
   timeLapPosY of its own (43) and cockpit_time.ini overrides it; the file
   named for the feature wins. */
#define HUD_TIME_TOTAL_Y    6.000f   /* timeTotalPosY */
#define HUD_TIME_LAP_Y     43.000f   /* timeLapPosY */

/* timeLapBlinkInSec: how long a just-completed lap time is held blinking
   before the live one takes the line back. */
#define HUD_LAP_BLINK    4.200f

/* ------------------------------------------------------- the gauges */

/* cockpit.ini's `indicator` group: the sweep the needle runs through,
   degrees, zero straight up and positive clockwise. -34 is up-and-left
   and +127 is down-and-right, a 161 degree arc through the top -- which
   is exactly the arc the game's own HUD screenshot shows on both gauges
   (opt_cock_all.csi: grey, then gold over the top, then red down the
   right). indicatorShift is the offset from the gauge's own centre that
   the sweep is struck about. */
#define HUD_IND_ANG_MIN  -34.000f   /* indicatorAngMin */
#define HUD_IND_ANG_MAX  127.000f   /* indicatorAngMax */
#define HUD_IND_SHIFT_X   22.000f   /* indicatorShiftX */
#define HUD_IND_SHIFT_Y    0.000f   /* indicatorShiftY */


/* THE DIAL'S OWN GEOMETRY, measured off cockpit_sp1 and cockpit_sp2
   rather than read, because no config file carries it. cockpit_sp1 is the
   dial -- a dark translucent disc, a silver rim and a GOLD tube running
   the whole sweep; cockpit_sp2 is the same ring in two tones, RED over
   the sweep and grey elsewhere. So the port draws sp1 whole as the track
   and reveals a SECTOR of sp2 up to the value: red filling along gold.

   THE MEASUREMENT IS ITS OWN CHECK. sp1's gold spans -39.3..+125.7 deg,
   sp2's red -38.8..+125.0, and cockpit.ini says -34..+127 -- three
   independent statements of one sweep agreeing to four degrees, which is
   the tube's own end-cap rounding. The ini's pair is what the port uses;
   these two are the reason to believe it. Both rings are centred on their
   texture to within 0.006 of its side. */
#define HUD_DIAL_CU   0.50548f   /* cockpit_sp2's fitted centre */
#define HUD_DIAL_CV   0.49279f
#define HUD_DIAL_R0   0.29947f   /* the ring's inner and outer radius, */
#define HUD_DIAL_R1   0.35960f   /* fractions of the texture's side */

/* WHERE THE TWO DIALS SIT, and this is the one block in this file with
   no config key behind it: cockpit.ini carries indicatorShiftX/Y and
   nothing positional, so the dials' screen place is hardcoded in the exe.
   It is MEASURED instead, off the game's own full-HUD screenshot -- the
   cockpit option preview Textures.1/opt_cock_all.csi, a 250x191 render of
   the 800x600 frame, which shows the whole thing: `3rd' top left, the two
   clocks top centre, `Lap 1/6' top right, `100 Boost' bottom left and
   `29 mph' bottom right.

   Three numbers, each the most robust landmark for its axis. The ring's
   outer radius and its centre Y come out of the arc's VERTICAL extent,
   which runs from its topmost point down to its +127 end: 1.602 R, and
   415..562 in the shot. The centre X is the dark disc's own midpoint,
   22..152. race_ui.c derives the quad's side from R and the art's own
   outer radius above, so the two cannot disagree.

   THE SHOT SHOWS BOTH THE DIAL AND THE MAP PANEL ABOUT A TENTH WIDER THAN
   TALL against art that is square in both cases (168x147 and 182x167).
   Something in the original's 2D path is not a uniform scale and what it
   is has not been recovered; sqrt(4/3) = 1.155 fits the dial to 1.5% and
   the map to 6%, which is a guess and is not applied. Both are drawn
   SQUARE. See known-issues.md. */
#define HUD_DIAL_CX    87.f    /* the boost dial's ring centre */
#define HUD_DIAL_CY   507.f
#define HUD_DIAL_R_PX  92.f    /* its outer radius, same pixels */

/* ------------------------------------------- the engine's own font */

/* Language/English/Smash20 and Smash26: a 256x256 atlas each, 90 glyphs
   on a 10 x 9 grid, with the character ORDER in the matching .dat. The
   grid is not assumed -- the empty bands in the atlas alpha straddle
   exactly 256/10 and 256/9 -- and the two files' .dat are byte-identical,
   so one lookup serves both sizes.

   THE GAME HAS A FONT AND THIS PORT SPENT YEARS SAYING IT DID NOT. ui.h
   used to explain that `the game ships no reusable glyph atlas'; the claim
   was made off Textures.1/2/3 and Interface.sb, and the two atlases are in
   Language/English/, a directory these notes had never listed. Both that
   comment and gen_font.py's now say so. See traps.md. */
#define SF_COLS 10
#define SF_ROWS 9
#define SF_N    90
#define SF_ATLAS 256   /* both atlases are square and this size */

/* Per glyph, the INK's left and right edge as a fraction of its own cell.
   Measured off the atlas alpha: the art is left-aligned in the cell with
   a ragged right edge, so a monospaced advance spaces `1/6` and a clock
   out into nonsense. The two sizes are measured separately because their
   art is not a scaled copy. */
/* Smash20 */
static const float SF_INK_SMALL[SF_N][2] = {
    { 0.31250f, 0.66406f }, { 0.31250f, 0.62500f }, { 0.31250f, 0.62500f }, { 0.27344f, 0.58594f }, { 0.31250f, 0.54688f },   /* ABCDE */
    { 0.27344f, 0.50781f }, { 0.19531f, 0.50781f }, { 0.19531f, 0.50781f }, { 0.27344f, 0.39062f }, { 0.11719f, 0.42969f },   /* FGHIJ */
    { 0.35156f, 0.66406f }, { 0.35156f, 0.58594f }, { 0.27344f, 0.70312f }, { 0.27344f, 0.62500f }, { 0.27344f, 0.58594f },   /* KLMNO */
    { 0.27344f, 0.58594f }, { 0.19531f, 0.50781f }, { 0.19531f, 0.50781f }, { 0.15625f, 0.46875f }, { 0.19531f, 0.46875f },   /* PQRST */
    { 0.31250f, 0.62500f }, { 0.31250f, 0.66406f }, { 0.23438f, 0.74219f }, { 0.23438f, 0.58594f }, { 0.31250f, 0.58594f },   /* UVWXY */
    { 0.23438f, 0.50781f }, { 0.23438f, 0.50781f }, { 0.23438f, 0.50781f }, { 0.19531f, 0.46875f }, { 0.19531f, 0.46875f },   /* Zabcd */
    { 0.35156f, 0.62500f }, { 0.35156f, 0.54688f }, { 0.35156f, 0.62500f }, { 0.31250f, 0.58594f }, { 0.39062f, 0.50781f },   /* efghi */
    { 0.31250f, 0.46875f }, { 0.23438f, 0.50781f }, { 0.31250f, 0.42969f }, { 0.15625f, 0.50781f }, { 0.19531f, 0.46875f },   /* jklmn */
    { 0.31250f, 0.58594f }, { 0.35156f, 0.62500f }, { 0.35156f, 0.62500f }, { 0.31250f, 0.58594f }, { 0.31250f, 0.58594f },   /* opqrs */
    { 0.27344f, 0.46875f }, { 0.23438f, 0.50781f }, { 0.23438f, 0.54688f }, { 0.11719f, 0.62500f }, { 0.19531f, 0.50781f },   /* tuvwx */
    { 0.35156f, 0.66406f }, { 0.39062f, 0.62500f }, { 0.39062f, 0.58594f }, { 0.27344f, 0.58594f }, { 0.27344f, 0.58594f },   /* yz123 */
    { 0.23438f, 0.54688f }, { 0.19531f, 0.50781f }, { 0.19531f, 0.50781f }, { 0.19531f, 0.50781f }, { 0.19531f, 0.50781f },   /* 45678 */
    { 0.31250f, 0.62500f }, { 0.31250f, 0.62500f }, { 0.23438f, 0.74219f }, { 0.39062f, 0.50781f }, { 0.35156f, 0.58594f },   /* 90+!" */
    { 0.27344f, 0.58594f }, { 0.27344f, 0.50781f }, { 0.35156f, 0.46875f }, { 0.27344f, 0.39062f }, { 0.15625f, 0.50781f },   /* $-.:? */
    { 0.42969f, 0.70312f }, { 0.31250f, 0.54688f }, { 0.27344f, 0.50781f }, { 0.35156f, 0.62500f }, { 0.39062f, 0.54688f },   /* ?()*, */
    { 0.23438f, 0.46875f }, { 0.15625f, 0.66406f }, { 0.15625f, 0.66406f }, { 0.27344f, 0.42969f }, { 0.07812f, 0.58594f },   /* /<>;= */
    { 0.27344f, 0.78125f }, { 0.39062f, 0.62500f }, { 0.39062f, 0.58594f }, { 0.31250f, 0.50781f }, { 0.07812f, 0.82031f },   /* %\[]@ */
    { 0.07812f, 0.70312f }, { 0.11719f, 0.62500f }, { 0.31250f, 0.46875f }, { 0.03906f, 0.46875f }, { 0.15625f, 0.54688f },   /* #^'_& */
};
/* Smash26 */
static const float SF_INK_BIG[SF_N][2] = {
    { 0.31250f, 0.70312f }, { 0.31250f, 0.66406f }, { 0.31250f, 0.66406f }, { 0.27344f, 0.62500f }, { 0.27344f, 0.54688f },   /* ABCDE */
    { 0.27344f, 0.54688f }, { 0.19531f, 0.54688f }, { 0.19531f, 0.54688f }, { 0.23438f, 0.39062f }, { 0.15625f, 0.50781f },   /* FGHIJ */
    { 0.31250f, 0.70312f }, { 0.35156f, 0.62500f }, { 0.19531f, 0.74219f }, { 0.23438f, 0.62500f }, { 0.27344f, 0.62500f },   /* KLMNO */
    { 0.27344f, 0.62500f }, { 0.19531f, 0.54688f }, { 0.19531f, 0.54688f }, { 0.15625f, 0.50781f }, { 0.15625f, 0.46875f },   /* PQRST */
    { 0.31250f, 0.66406f }, { 0.27344f, 0.66406f }, { 0.19531f, 0.78125f }, { 0.23438f, 0.62500f }, { 0.23438f, 0.62500f },   /* UVWXY */
    { 0.23438f, 0.54688f }, { 0.19531f, 0.50781f }, { 0.19531f, 0.50781f }, { 0.15625f, 0.46875f }, { 0.15625f, 0.46875f },   /* Zabcd */
    { 0.31250f, 0.62500f }, { 0.35156f, 0.58594f }, { 0.31250f, 0.62500f }, { 0.27344f, 0.58594f }, { 0.35156f, 0.50781f },   /* efghi */
    { 0.27344f, 0.46875f }, { 0.19531f, 0.54688f }, { 0.27344f, 0.42969f }, { 0.07812f, 0.54688f }, { 0.15625f, 0.46875f },   /* jklmn */
    { 0.31250f, 0.62500f }, { 0.31250f, 0.62500f }, { 0.31250f, 0.62500f }, { 0.31250f, 0.62500f }, { 0.27344f, 0.58594f },   /* opqrs */
    { 0.23438f, 0.46875f }, { 0.19531f, 0.50781f }, { 0.19531f, 0.54688f }, { 0.00000f, 0.54688f }, { 0.15625f, 0.50781f },   /* tuvwx */
    { 0.31250f, 0.66406f }, { 0.31250f, 0.58594f }, { 0.31250f, 0.54688f }, { 0.19531f, 0.54688f }, { 0.23438f, 0.58594f },   /* yz123 */
    { 0.15625f, 0.54688f }, { 0.19531f, 0.54688f }, { 0.15625f, 0.50781f }, { 0.11719f, 0.50781f }, { 0.15625f, 0.50781f },   /* 45678 */
    { 0.31250f, 0.66406f }, { 0.31250f, 0.66406f }, { 0.15625f, 0.74219f }, { 0.35156f, 0.50781f }, { 0.27344f, 0.54688f },   /* 90+!" */
    { 0.23438f, 0.58594f }, { 0.19531f, 0.46875f }, { 0.27344f, 0.42969f }, { 0.23438f, 0.39062f }, { 0.11719f, 0.50781f },   /* $-.:? */
    { 0.31250f, 0.66406f }, { 0.31250f, 0.58594f }, { 0.35156f, 0.62500f }, { 0.27344f, 0.62500f }, { 0.31250f, 0.50781f },   /* ?()*, */
    { 0.23438f, 0.50781f }, { 0.03906f, 0.62500f }, { 0.07812f, 0.66406f }, { 0.23438f, 0.42969f }, { 0.03906f, 0.62500f },   /* /<>;= */
    { 0.19531f, 0.78125f }, { 0.31250f, 0.58594f }, { 0.39062f, 0.62500f }, { 0.31250f, 0.97656f }, { 0.00000f, 0.85938f },   /* %\[]@ */
    { 0.03906f, 0.74219f }, { 0.07812f, 0.66406f }, { 0.23438f, 0.42969f }, { 0.07812f, 0.58594f }, { 0.11719f, 0.54688f },   /* #^'_& */
};

/* char -> glyph index, or -1. Built here rather than searched at runtime:
   the order is the .dat's and it is not sorted. */
static const signed char SF_INDEX[256] = {
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  63,  64,  85,  65,  80,  89,  87,  71,  72,  73,  62,  74,  66,  67,  75,
     61,  52,  53,  54,  55,  56,  57,  58,  59,  60,  68,  78,  76,  79,  77,  70,
     84,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
     15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  82,  81,  83,  86,  88,
     -1,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
     41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  69,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
};

/* smash20.ini. letSizeX/Y are the cell as DRAWN, in pixels of the 800x600
   frame -- 25 x 28 against the atlas's own 25.6 x 28.44, so the art is
   drawn at very nearly 1:1. letSpace is the tracking added after each
   glyph's ink, spaceLen the width of a space, lineSpace the extra
   between lines, letBaseLine the font's nominal size. */
#define SF_SMALL_SIZE_X     25.000f   /* letSizeX */
#define SF_SMALL_SIZE_Y     28.000f   /* letSizeY */
#define SF_SMALL_SPACE       1.000f   /* letSpace */
#define SF_SMALL_SPACE_LEN   6.000f   /* spaceLen */
#define SF_SMALL_LINE       -5.000f   /* lineSpace */
#define SF_SMALL_BASELINE   20.000f   /* letBaseLine */
#define SF_SMALL_TEX "Smash20"

/* smash26.ini. letSizeX/Y are the cell as DRAWN, in pixels of the 800x600
   frame -- 25 x 28 against the atlas's own 25.6 x 28.44, so the art is
   drawn at very nearly 1:1. letSpace is the tracking added after each
   glyph's ink, spaceLen the width of a space, lineSpace the extra
   between lines, letBaseLine the font's nominal size. */
#define SF_BIG_SIZE_X     25.000f   /* letSizeX */
#define SF_BIG_SIZE_Y     28.000f   /* letSizeY */
#define SF_BIG_SPACE       0.000f   /* letSpace */
#define SF_BIG_SPACE_LEN   6.000f   /* spaceLen */
#define SF_BIG_LINE        0.000f   /* lineSpace */
#define SF_BIG_BASELINE   25.000f   /* letBaseLine */
#define SF_BIG_TEX "Smash26"

#endif /* HUD_DATA_H */
