/*
 * RC Cars — PS Vita track viewer / driving test.
 *
 * Renders a converted track and car through vitaGL's fixed-function pipeline.
 * The original engine is Direct3D 8 fixed-function with no shaders at all,
 * which maps almost one-to-one onto vitaGL — that is why this port is
 * tractable at all.
 *
 * Handling is the GAME'S OWN transcribed model -- rb.c + contact.c + collide.c,
 * data from rb_data.h, camera from cam.c, stepped at a FIXED 1/60 regardless of
 * the frame rate (see rbcar.h). It is the only model: physics.c, the arcade
 * placeholder, is no longer reachable from anywhere.
 * See rccars_re/PHYSICS.md.
 *
 * The car spawns at the track's real race start, taken from that track's own
 * Players/Player instance (tracks.h, generated by rccars_re/gen_tracks.py) --
 * position, heading, and the car the track starts with. It is NOT held there:
 * rb_car.frozen, the engine's start-line hold, is unusable in this port because
 * the rest damper is gated on !frozen, so a held car has nothing damping roll
 * and wanders between 1 and 19 degrees of tilt indefinitely. A free-rolling car
 * on a slope rolls, which is what a real one does.
 *
 * The visual subsystems are the game's own too: the projected car shadow
 * (shadow.c, shdAddSource type 3), the animated water (water.c, WaterLOD) and
 * the checkpoint arrows (checkpoint.c, anim_cp). SQUARE turns all three off.
 *
 * Controls:
 *   R trigger  throttle          L trigger  brake / reverse
 *   CROSS      boost             CIRCLE     jump / right the car
 *   left stick steer             right stick camera orbit (springs back)
 *   START      menu: track, car, tuning parts, texture quality, quit
 *   SQUARE     toggle shadow + water animation + checkpoint arrows
 *   SELECT     toggle free-fly camera
 *
 * CIRCLE is the game's own Jump action -- action 6 of the eight the original's
 * input layer binds (the table at 0x004e4188 names them Boost, Left, Right,
 * Forw, Back, JUMP, Brake, Reset). On its wheels the car hops; on its roof or
 * its side the same button rights it where it stands. See rb_car_jump.
 */

#include <psp2/ctrl.h>
#include <psp2/kernel/processmgr.h>
#include <psp2/kernel/clib.h>
#include <psp2/power.h>
#include <psp2/rtc.h>
#include <vitaGL.h>

#include "physics.h"
#include "col.h"
#include "rbcar.h"
#include "cam.h"
#include "carani.h"
#include "prop.h"
#include "scene.h"
#include "shadow.h"
#include "water.h"
#include "checkpoint.h"
#include "antenna.h"
#include "fx.h"
#include "trace.h"
#include "envmap.h"
#include "tracks.h"
#include "ui.h"
#include "menu.h"
#include "ai.h"
#include "carparts.h"
#include "audio.h"
#include "sfx.h"
#include "rlog.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* menu.h mirrors this rather than including scene.h -- menu.c is kept free of the
   GL layer so menu_test can build it without vitaGL. This is the one place both
   headers are visible, so it is where the two are held together. */
#if MENU_TEXQUAL_LEVELS != SCENE_TEX_QUALITY_LEVELS
#error "menu.h's MENU_TEXQUAL_LEVELS and scene.h's SCENE_TEX_QUALITY_LEVELS disagree"
#endif
#if MENU_SKINS != CARPARTS_SKINS
#error "menu.h's MENU_SKINS and carparts.h's CARPARTS_SKINS disagree"
#endif

#define SCR_W 960
#define SCR_H 544
#define DEADZONE 24
#define DEG (float)(M_PI / 180.0)

unsigned int _newlib_heap_size_user = 192 * 1024 * 1024;

static scene_t track, car;
/* props.vsc holds all 13 knockable props and is shared by every track, so it
   loads ONCE at init and is never released with the track. See prop.h. */
static scene_t props_scene;
static props_t props;

/* What is loaded right now. The menu changes these; load_track/load_car act. */
static int cur_track = 0, cur_car = 0;
static menu_t menu;

/* The upgrade parts the car wears: which exhaust, and which tyres. Rebound with
   the car scene, reapplied whenever the menu changes a level. */
static carparts_t parts;

/* The ground height the car was last placed at, so the fell-out-of-the-world
   test has a reference that follows the track instead of a constant tuned to
   one pier on beach_1. */
static float spawn_ground_y = 0.f;

/* How far the car's centre of mass has to sink below the water surface before it
   counts as drowned. The port's, not recovered -- the original uses per-track
   reset volumes the port has no data for. Sized off the cars: the tallest body
   box is 0.14 m, so half a metre under is unambiguously submerged, while the
   deepest water a car can actually FORD on any of the ten tracks is the stream,
   which runs 2 to 13 cm over its bed. */
#define DROWN_DEPTH 0.5f

/* The three visual subsystems, all transcribed from the game's own: the
   projected car shadow (shdAddSource type 3), the animated water (WaterLOD),
   and the checkpoint arrows (anim_cp). See each header. */
static shadow_t shadow;
static antenna_t antenna;
static water_t water;
static checkpoints_t cps;
static int show_vis = 1;

/* The three effects the car itself throws off, all the game's own as well: the
   wheel dust and exhaust smoke (fx.c, car_dustx / exhausted_gas), the tyre marks
   (trace.c, car_trace) and the body's env-map glance (envmap.c, CarEnvMap).
   They ride on show_vis with the other three. */
static fx_t fx;
static trace_t traces;
static envmap_t envmap;

/* Collision now lives in col.c, which also exposes the sphere and segment
   queries the transcribed physics needs (rb_world). */
static col_t col;

/* The AI opponents -- recorded laps, replayed and rubber-banded. See ai.h, and
 * note what it says about the mode this port does NOT take: they are on rails,
 * so they neither shove the player nor get shoved.
 *
 * ONE SCENE PER DISTINCT MODEL the roster needs, so up to three and usually two
 * or three. They cannot share the player's `car` scene: carani writes the
 * animated matrices INTO the scene's rig, so a frame that drew the player and
 * then an opponent of the same model would draw the player twice in the
 * opponent's pose. Two opponents on the SAME model can share one scene, because
 * draw_ai animates and draws each one before touching the next. */
static ai_t     ai;
static scene_t  ai_scene[3];
static shadow_t ai_shadow[3];
static int      ai_model[3];        /* 1 once loaded and rig-bound */
static ai_track ai_tr;

/* ONE EMITTER PER OPPONENT, into the player's shared particle pool.
 *
 * Not one fx_t per car: that is 123 KB of particles and a second fx_draw each,
 * and the plumes all composite into the same frame anyway. What must NOT be
 * shared is the emitter state -- the carry fractions, the backfire hold and the
 * smoke's colour ramp are per-system in the engine too, and sharing them makes
 * two cars' emission rates beat against each other. See fx.h.
 *
 * Indexed by opponent, NOT by model: two Buggies on one scene are still two cars
 * with two pipes in two places. The pipe itself is read off the shared rig's
 * REST matrices, which no animation touches, so reading it per car off a scene
 * several cars share is safe -- unlike carani_update, which draw_ai has to
 * sequence for exactly that reason. */
static fx_emitter ai_em[AI_MAX_OPPONENTS];

/* ------------------------------------------------------------------ state */

/* car pose: heading in degrees, forward = (sin h, 0, -cos h) */
/* Spawn chosen by texture, not just by flatness: picking "flattest ground near
   sea level" selects the ocean, which is the flattest surface on the map.
   This one is a 23-degree slope, so body pitch/roll is visible on spawn. */
static vehicle_t veh;

/* The game's own model, transcribed: rb.c + contact.c + collide.c. It is the
   ONLY model now -- the physics.c placeholder is no longer reachable. */
static rb_car rc;
static cam_t  rcam;
/* The model's timestep is decoupled from the frame rate -- see rbcar.h. The
   counter only exists to stop a sustained overload filling the log. */
static rbcar_clock phys_clock;
static int         phys_clip_log;

/* THE TRANSCRIBED MODEL, ALWAYS.
 *
 * This was a toggle -- TRIANGLE, and a menu row -- because the transcribed model
 * used to be unstable here and the physics.c placeholder was the fallback. That
 * is long over: the suspension ramp collapse is fixed (5.16 deg of tilt peak to
 * peak on a 1 degree slope, forever, is now 0.00), the damper is fed the right
 * signal, and the car spawns at the track's real race start rather than on a 23
 * degree pier edge. There is nothing left to A/B against, so the switch is gone.
 *
 * Kept as a const rather than deleted so the compiler folds the `if (use_rb)`
 * branches away by itself. `veh` stays: the rb pose is mirrored into it for the
 * HUD and the free-fly camera, which is now all it is for. */
static const int use_rb = 1;

/* adapter so physics.c stays independent of the collision grid */
static int ground_cb(float x, float z, float ceil_y,
                     float *y, float *nx, float *ny, float *nz)
{
    return col_ground_at(&col, x, z, ceil_y, y, nx, ny, nz);
}

static float orbit_yaw = 0.f, orbit_pitch = 14.f;
static int free_cam = 0;
static float fly_x = -18.f, fly_y = 110.f, fly_z = 40.f;
static float fly_yaw = 0.f, fly_pitch = -55.f;

static float axis(unsigned char v)
{
    int d = (int)v - 128;
    if (d > -DEADZONE && d < DEADZONE) return 0.f;
    return (float)d / 128.f;
}

static void perspective(float fovy, float aspect, float zn, float zf)
{
    float fh = tanf(fovy * 0.5f * DEG) * zn;
    glFrustum(-fh * aspect, fh * aspect, -fh, fh, zn, zf);
}

/* The camera's right and up in WORLD space, for the particle billboards. For an
   orthonormal view rotation R (column-vector, v_eye = R*v_world) the eye-space
   axes in world coordinates are R's ROWS, so these are rows 0 and 1 of Rx*Ry --
   the same product env_normal_matrix builds. */
static void cam_basis(float vpitch, float vyaw, float right[3], float up[3])
{
    float cp = cosf(vpitch * DEG), sp = sinf(vpitch * DEG);
    float cy = cosf(-vyaw * DEG), sy = sinf(-vyaw * DEG);

    right[0] = cy;        right[1] = 0.f; right[2] = sy;
    up[0] = sp * sy;      up[1] = cp;     up[2] = -sp * cy;
}

/*
 * The 3x3 that takes a MODEL-space normal to VIEW space, for the env-map glance.
 *
 * Built rather than read back out of GL, and built the long way on purpose --
 * this is the fourth transform in this port whose convention matters, and the
 * other three all went wrong when they were assumed. The view is laid down as
 * glRotatef(vpitch, X) then glRotatef(-vyaw, Y), which in GL's COLUMN-vector
 * terms is Rx*Ry; every matrix in this port is row-major ROW-vector, whose
 * rotation is that product transposed. The car's own matrix is already in that
 * convention (rbcar_matrix), so it composes on the left.
 */
static void env_normal_matrix(const float *carm, float vpitch, float vyaw,
                              float out[9])
{
    float cp = cosf(vpitch * DEG), sp = sinf(vpitch * DEG);
    float cy = cosf(-vyaw * DEG), sy = sinf(-vyaw * DEG);
    const float Rx[9] = { 1.f, 0.f, 0.f,  0.f, cp, -sp,  0.f, sp, cp };
    const float Ry[9] = { cy, 0.f, sy,  0.f, 1.f, 0.f,  -sy, 0.f, cy };
    float rxry[9], v3[9], c3[9];
    int r, c, k;

    for (r = 0; r < 3; r++)
        for (c = 0; c < 3; c++) {
            float s = 0.f;
            for (k = 0; k < 3; k++)
                s += Rx[r * 3 + k] * Ry[k * 3 + c];
            rxry[r * 3 + c] = s;
        }
    for (r = 0; r < 3; r++)
        for (c = 0; c < 3; c++)
            v3[r * 3 + c] = rxry[c * 3 + r];        /* the transpose */
    for (r = 0; r < 3; r++)
        for (c = 0; c < 3; c++)
            c3[r * 3 + c] = carm[r * 4 + c];
    for (r = 0; r < 3; r++)
        for (c = 0; c < 3; c++) {
            float s = 0.f;
            for (k = 0; k < 3; k++)
                s += c3[r * 3 + k] * v3[k * 3 + c];
            out[r * 3 + c] = s;
        }
}

/* ------------------------------------------------- loading and respawning */

/*
 * PUT THE CAR DOWN. There are TWO reasons to now, and they are not the same
 * reason:
 *
 *   respawn()             the race is STARTING -- the grid, the lap back to
 *                         zero, and the field back on its own grid.
 *   respawn_checkpoint()  the car DIED -- back to the last checkpoint it
 *                         actually crossed, with the lap, the opponents and the
 *                         race all left running.
 *
 * The second is the change. Drowning and falling out of the world used to call
 * respawn(), which is a whole race restart: ai_reset drops every opponent's
 * cursor back to its own grid, so going in the sea on the last corner un-drove
 * the race for the entire field as well as for the player. place_car is the part
 * both share.
 *
 * The ground probe is CEILED at the reference height plus a metre. Probing the
 * whole column picks the highest surface anywhere above (x,z), and beach_2's
 * race start is under an overpass -- ground 3.19, roof 10.08 -- so the car
 * spawned seven metres up, rolled off the roof and fell out of the world. The
 * checkpoint markers want it just as much: they sit on the racing line, and on
 * these tracks the racing line runs under things.
 */
static void place_car(float x, float z, float ref_y, float yaw)
{
    float gy = ref_y, n0, n1, n2;

    if (!col_ground_at(&col, x, z, ref_y + 1.0f, &gy, &n0, &n1, &n2))
        gy = ref_y;
    spawn_ground_y = gy;

    /* The heading goes across unchanged: the .sb Euler Y and rbcar_init's pose
       quaternion both map the car's local +Z to (sin yaw, 0, cos yaw). Checked
       numerically, not assumed -- four bugs in this port have come from
       inheriting a convention unverified. cp_respawn_pose builds its yaw in that
       same convention, atan2(dx, dz) along the spine. */
    rbcar_init(&rc, cur_car, col_rb_world(&col), x, gy, z, yaw);
    rc.tire_upgrade = menu.tires;
    rc.reso_upgrade = menu.reso;
    rc.boost_upgrade = menu.boost;
    /* With a full meter, at whatever capacity this booster level buys. AFTER the
       line above, not before -- the capacity reads it. The original's own reset
       path (0x004f27e6) fills the meter too, and it is the reset path for
       drowning as much as for the grid. */
    rb_boost_reset(&rc);
    /* Throw away time banked across the load or the teleport: the world did not
       experience it, and spending it would run several ticks on the first frame
       at the new spawn. */
    rbcar_clock_reset(&phys_clock);
    cam_init(&rcam, &rc);
    /* A respawn is a teleport, and a mark that survives one is drawn as a single
       quad stretching from wherever the car was to where it landed. The wheels
       stay in contact across it, so nothing else would break the strip. */
    trace_clear(&traces);

    /* the pose mirror the HUD and the free-fly camera read */
    vehicle_init(&veh, cur_car, x, gy + 0.06f, z, yaw);

    if (car.has_rig)
        carani_bind(&car.rig, &rc);
    /* Only now does an rb wheel index name a mesh node, so only now can the
       marks be fitted to the tyres that make them -- load_car built the trace
       before this ran. See trace_fit_tyres. */
    trace_fit_tyres(&traces, &car);

    /* The engine's own reset cue. Also the one place the loops are guaranteed
       to be re-evaluated against a car that has just teleported. */
    sfx_respawn();
}

/* The race is starting: the grid, and everything that only a start resets. */
static void respawn(void)
{
    const track_info *t = &TRACKS[cur_track];

    place_car(t->x, t->z, t->y, t->yaw);

    /* The spine cursor: the jump from wherever the car was back to the grid would
       otherwise sweep past every checkpoint station in between and fire a cue for
       each. cp_step's own CP_MAX_STEP guard would catch it a frame later; this
       catches it on the frame it happens.
     *
     * cp_restart, not cp_resync: a START also puts the lap back to zero and
     * forgets the last checkpoint crossed, so the first death of the new race
     * sends the car to the grid and not to a checkpoint left over from the
     * previous one. cp_resync deliberately keeps both, which is what the
     * drowning path wants. */
    cp_restart(&cps, t->x, spawn_ground_y, t->z);

    /* A restart puts the field back on its own grid. ai_reset also drops every
       cursor, so an opponent does not keep the lap it was on. */
    ai_reset(&ai);
    sfx_ai_silence();

    rlog("[rccars] start: %s  (%d,%d,%d) cm  yaw=%d deg  car=%s\n",
                  TRACKS[cur_track].name,
                  (int)(t->x * 100.f), (int)(spawn_ground_y * 100.f),
                  (int)(t->z * 100.f),
                  (int)t->yaw, rbcar_name(cur_car));
}

/*
 * THE CAR DIED -- drowned, or fell out of the world. Back to the last checkpoint
 * it crossed, and NOT a restart.
 *
 * Two things are deliberately absent against respawn(): no ai_reset, so the
 * opponents carry on from wherever they are; and cp_resync rather than
 * cp_restart, so the lap and the last crossing survive -- a drowning does not
 * un-drive a lap, and checkpoint.h says so at cp_resync.
 *
 * Falls back to the grid when cp_respawn_pose declines, which it does when no
 * checkpoint has been crossed yet. That is the right answer rather than a
 * degraded one: a car that drowns before its first checkpoint has nowhere else to
 * go, and going to the grid is exactly what a race module would do. It comes out
 * as a full respawn(), which is defensible -- the player has driven none of the
 * race -- and it is the one case where dying does restart.
 */
static void respawn_checkpoint(void)
{
    float p[3], yaw;

    if (!cp_respawn_pose(&cps, p, &yaw)) {
        respawn();
        return;
    }

    place_car(p[0], p[2], p[1], yaw);
    cp_resync(&cps, p[0], spawn_ground_y, p[2]);

    rlog("[rccars] respawn at checkpoint %d  (%d,%d,%d) cm  yaw=%d deg  "
         "lap %d, race running\n",
         cps.last + 1, (int)(p[0] * 100.f), (int)(spawn_ground_y * 100.f),
         (int)(p[2] * 100.f), (int)yaw, cps.lap);
}

/* ai_track.spine, bound to checkpoint.c's own spine. The original asks the same
   question of the player and of every opponent (FUN_004ea120), so this is the one
   function both sides are measured with. */
static int ai_spine(void *ctx, float x, float y, float z,
                    float *dist, int *cp)
{
    return cp_spine_dist((const checkpoints_t *)ctx, x, y, z, dist, cp);
}

/* Load the roster and the models it needs. Called by load_track AFTER cp_init,
 * because the spine has to exist before the rubber band can read it.
 *
 * The single-race path for now: every opponent in the layout starts, and the
 * static coefficient is the track's own CoeffCommonOpponents with no difficulty
 * multiplier -- which is what the original does outside the championship
 * (FUN_004f11b0 gates the multiplier on the mode being 1). When there is a
 * championship to be in, this is the one call that changes. */
static void load_ai(int idx)
{
    int i, k;

    sfx_ai_silence();
    for (k = 0; k < 3; k++) {
        if (ai_model[k]) {
            scene_release(&ai_scene[k]);
            ai_model[k] = 0;
        }
    }
    ai_free(&ai);

    ai_tr.ctx = &cps;
    ai_tr.spine = ai_spine;
    ai_tr.spine_len = cps.spine_len;

    if (!ai_init(&ai, idx, "app0:assets", col_rb_world(&col),
                 1 /* normal */, 0 /* single race */))
        return;

    /* One scene per model the roster actually asks for, and no more: a car .vsc
       is 3.7 to 4.2 MB, so loading all three when the field uses two is 4 MB of
       heap for nothing. */
    for (i = 0; i < ai.n; i++) {
        char path[128];
        int c = ai.car[i].car;
        if (c < 0 || c > 2 || ai_model[c])
            continue;
        snprintf(path, sizeof(path), "app0:assets/car%d.vsc", c + 1);
        if (!scene_load(path, &ai_scene[c])) {
            rlog("[rccars] ai: cannot load %s -- opponent invisible\n", path);
            continue;
        }
        /* Bind the rig ONCE per model. carani_bind resolves the wheel mapping
           from the mount positions, which are the model's, so every opponent on
           this model shares the binding -- and draw_ai re-animates it per car
           before drawing, which is what makes sharing safe. */
        if (ai_scene[c].has_rig)
            carani_bind(&ai_scene[c].rig, &ai.car[i].rb);
        /* ShadowSize and ShadowShift are per-car, so the decal is per model too. */
        shadow_init(&ai_shadow[c], &ai_scene[c], c);
        ai_model[c] = 1;
    }

    /* The exhaust emitters, AFTER the scene loop, because the pipe comes off a
       rig that loop may only just have bound -- and per OPPONENT, not per model,
       since the roster gives each driver its own booster level and the four
       levels are four different pipes in four different places (carparts.h). */
    for (i = 0; i < ai.n; i++) {
        int c = ai.car[i].car;
        fx_emitter_init(&ai_em[i]);
        if (c < 0 || c > 2 || !ai_model[c] || !ai_scene[c].has_rig)
            continue;
        /* rbcar_com_oy(c), the same MODEL -> BODY shift the player's pipe takes
           and the same one draw_ai translates by. Nothing here reads the rig's
           animated matrices, only its rest ones, so a shared scene is fine. */
        fx_pipe_from_rig(&ai_em[i], &ai_scene[c].rig, ai.car[i].boost,
                         rbcar_com_oy(c));
    }

    rlog("[rccars] ai: %d opponent(s) on %d model(s)\n", ai.n,
         ai_model[0] + ai_model[1] + ai_model[2]);
}

static int load_track(int idx)
{
    char path[128];

    if (idx < 0 || idx >= N_TRACKS)
        return 0;

    snprintf(path, sizeof(path), "app0:assets/%s.vsc", TRACKS[idx].base);
    scene_release(&track);
    if (!scene_load(path, &track)) {
        rlog("[rccars] cannot load %s\n", path);
        return 0;
    }
    snprintf(path, sizeof(path), "app0:assets/%s.col", TRACKS[idx].base);
    col_free(&col);
    if (!col_load(path, &col))
        rlog("[rccars] cannot load %s -- no collision\n", path);

    cur_track = idx;
    /* water and the checkpoint arrows are built FROM the scene, so they have to
       be rebuilt with it. Both no-op on a track packed before --markers.
       water_free before water_init: water_init memsets, so re-initialising over
       a built one drops its per-vertex damping and colour buffers on the floor.
       That leaked on every track change and on every texture-quality change --
       out of the same newlib heap vitaGL's RAM pool draws from. */
    water_free(&water);
    water_init(&water, &track, &col);
    cp_init(&cps, &track, &col);
    /* The glance's source is this track's sky -- the engine's S_SKY slot, which
       it fills at runtime, and the ten tracks do not share one sky texture. */
    envmap_init(&envmap, &track);
    /* Marks belong to the ground they were left on. */
    trace_clear(&traces);
    /* The ambient bed is per-track (the .sb's own ground_noise_snd) and the
       surface loop reads materials out of THIS grid, so both follow the load.
       Takes &col after col_load, never before -- the grid is rebuilt above. */
    sfx_set_track(idx, &col);
    /* The props belong to this track and this grid -- both were just rebuilt. */
    prop_init(&props, props_scene.n_batches ? &props_scene : NULL, &col, idx);
    /* The opponents are per-track too: their recorded laps ARE this track. After
       cp_init, because the rubber band reads that spine. */
    load_ai(idx);
    return 1;
}

static int load_car(int idx)
{
    char path[128];

    if (idx < 0 || idx > 2)
        return 0;

    snprintf(path, sizeof(path), "app0:assets/car%d.vsc", idx + 1);
    scene_release(&car);
    if (!scene_load(path, &car))
        rlog("[rccars] cannot load %s\n", path);

    cur_car = idx;
    /* The motor family is per-car -- three channels' worth of loops, and the
       biggest thing in the bank -- so it is paged in and out with the model. */
    sfx_set_car(idx);
    /* ShadowSize and ShadowShift are per-car, so the decal is rebuilt too. */
    shadow_init(&shadow, &car, idx);
    /* the whip is per-car too: Antenna_Car<n>.crs differs (0.25 m for the
       Overkill, 0.35 for the Buggy) and it binds to this scene's own batch */
    antenna_init(&antenna, &car, idx);

    /* Resolve this car's exhaust groups and wheel batches, then show the picked
       levels. Without this every car draws ALL FOUR of its UPGRADES groups on
       top of each other -- 662 overlapping triangles of exhaust on the Overkill.
       See carparts.h. */
    carparts_bind(&parts, &car);
    /* How many skins THIS model has. The menu cannot work it out -- it is a
       property of the packed scene, and a car packed without the three extra
       atlases has exactly one -- so it is handed over here, before the apply, and
       the stored per-car choice is clamped into what is really available. */
    menu.skins = parts.n_skin > 0 ? parts.n_skin : 1;
    if (menu.skin[idx] >= menu.skins)
        menu.skin[idx] = 0;
    carparts_apply(&parts, &car, menu.tires, menu.boost, menu.skin[idx]);

    /* The dust sprite and the four tyre marks are packed into the CAR, so both
       follow it. The pipe is the fitted booster's own node. */
    fx_init(&fx, &car);
    fx_pipe_from_rig(&fx.em, &car.rig, menu.boost, rbcar_com_oy(idx));
    trace_init(&traces, &car);
    trace_clear(&traces);
    rlog("[rccars] parts: %d exhausts  %d wheel batches  "
                  "tyres '%s' %d/4 levels packed  "
                  "skins %d/%d packed ('%s'%s%s) on %d+%d batches\n",
                  parts.n_boost, parts.n_wheel,
                  parts.family[0] ? parts.family : "-", parts.n_tire,
                  parts.n_skin, CARPARTS_SKINS,
                  parts.skin[0].family[0] ? parts.skin[0].family : "-",
                  parts.skin[1].family[0] ? "+" : "",
                  parts.skin[1].family[0] ? parts.skin[1].family : "",
                  parts.skin[0].n_batch, parts.skin[1].n_batch);
    return 1;
}

/* THE OPPONENTS' DRAW.
 *
 * Same shape as the player's own block above and for the same reasons -- the
 * body matrix goes in without a transpose, the model is dropped onto its own
 * wheel-centre plane, the exhaust is a second blended pass -- with three
 * differences, each of which is here rather than in ai.c because it is about
 * drawing and not about the model:
 *
 *   - the rig is ANIMATED THEN DRAWN, per car. carani writes into the scene's
 *     rig, so two opponents on the same model must not both be posed before
 *     either is drawn. That is the only reason one scene can serve several cars.
 *   - a distance cap. AI_DRAW_DIST is THE PORT'S: nothing recovered says when an
 *     opponent stops being drawn, and it is NOT AI_DIST_CAM, which is the
 *     original's radius for deciding whether to SIMULATE one. 80 m on a 0.42 m
 *     car is about five pixels across at this field of view, and the rubber band
 *     holds the field inside +-45 m of the player anyway, so this almost never
 *     fires -- which is why the count is logged rather than assumed.
 *   - no dust, no tyre marks, no antenna, no glance. Every one of those is a
 *     per-car particle system or vertex stream, and five of them is the cost the
 *     whole AI was kept cheap to avoid. Stated here so it is a decision and not
 *     an omission.
 */
#define AI_DRAW_DIST 80.0f
static int ai_drawn;
/* How many opponents were close enough to emit, for the once-a-second log, so
   "the opponents have no dust" arrives with a number the way the player's own
   effects do. */
static int ai_fx_emitted;

static void draw_ai(const float eye[3])
{
    int i;

    ai_drawn = 0;
    if (ai.n <= 0)
        return;

    /* A rigged scene is drawn under its own body matrix, so a model-space box
       tested against the world frustum means nothing -- the same reason the
       player's block turns culling off. */
    scene_cull_off();
    for (i = 0; i < ai.n; i++) {
        const ai_car *a = &ai.car[i];
        int c = a->car;
        scene_t *sc;
        float dx, dz;

        if (c < 0 || c > 2 || !ai_model[c])
            continue;
        dx = a->rb.body.x[0] - eye[0];
        dz = a->rb.body.x[2] - eye[2];
        if (dx * dx + dz * dz > AI_DRAW_DIST * AI_DRAW_DIST)
            continue;
        sc = &ai_scene[c];

        if (sc->has_rig)
            carani_update(&sc->rig, &a->rb);
        if (show_vis)
            shadow_draw(&ai_shadow[c], &col, ai_matrix(&ai, i));

        glPushMatrix();
        glMultMatrixf(ai_matrix(&ai, i));
        /* MODEL space -> BODY space, per CAR: rbcar_com_oy, not anything read
           off `sc->rig` -- two opponents on one model share that rig. */
        glTranslatef(0.f, -rbcar_com_oy(c), 0.f);
        scene_draw(sc, BATCH_SKY | BATCH_ALPHA_LOWREF, 0);
        /* The pipes and boosters, exactly as for the player: OPAQUE, and only
           the alpha-test reference dropped, because their ARGB4444 alpha sits
           at a plateau just under the world's cut-out threshold. */
        glAlphaFunc(GL_GREATER, 0.f);
        scene_draw(sc, BATCH_SKY | BATCH_ALPHA_LOWREF, BATCH_ALPHA_LOWREF);
        glAlphaFunc(GL_GREATER, 0.5f);
        glPopMatrix();
        ai_drawn++;
    }
}

int main(void)
{
    /* THE LOG FIRST, before anything that might have something to say.
     * sceClibPrintf goes to the debug channel, which retail hardware does not
     * have -- every diagnostic in this file was invisible on the machine whose
     * numbers matter. rlog writes ux0:data/rccars/rccars.log as well. */
    rlog_init();

    /* CLOCKS FIRST, before vitaGL builds anything.
     *
     * A Vita starts an app at 333 MHz CPU / 111 MHz GPU / 166 MHz bus and stays
     * there unless asked otherwise -- this port never asked, so it was driving the
     * whole renderer on less than half the GPU the machine has. These are the
     * documented maxima, and every non-trivial homebrew sets them.
     *
     * The GPU one is what matters most here: 111 -> 222 MHz is double the fill and
     * vertex rate, measured against a frame that sat pinned at 100% GPU. The bus
     * matters nearly as much, because every batch's vertices are streamed out of
     * main memory each frame -- this port uses no VBOs, which is 3.03 MB per frame
     * on beach_1 alone. */
    scePowerSetArmClockFrequency(444);
    scePowerSetBusClockFrequency(222);
    scePowerSetGpuClockFrequency(222);
    scePowerSetGpuXbarClockFrequency(166);
    rlog("[rccars] clocks: arm %d, bus %d, gpu %d, xbar %d MHz\n",
                  scePowerGetArmClockFrequency(), scePowerGetBusClockFrequency(),
                  scePowerGetGpuClockFrequency(),
                  scePowerGetGpuXbarClockFrequency());

    sceCtrlSetSamplingMode(SCE_CTRL_MODE_ANALOG);
    vglInitExtended(0, SCR_W, SCR_H, 0x1000000, SCE_GXM_MULTISAMPLE_NONE);

    /* The menu holds the selections; start it on the track's own default car,
       which every track names in its Players/Player instance (all ten say
       Car1). load_car/load_track then build everything from those. */
    menu_init(&menu, 0, TRACKS[0].car);

    /* Audio comes up BEFORE the first load: load_track and load_car page the
       track's ambient bed and the car's motor family into the bank, and both
       are no-ops until sfx_init has run. Neither call is fatal -- every sfx
       entry point is a no-op on a failed init, so a missing sound.sbk costs the
       audio and nothing else. */
    if (audio_init("app0:assets/sound.sbk", "app0:assets/music") != 0)
        rlog("[rccars] audio: no sound.sbk -- running silent\n");
    sfx_init();

    /* The three visual subsystems come up inside load_track/load_car. All are
       no-ops if the track was packed before --markers existed (no surface flags,
       no markers) or the car without --shadow-tex, so an old .vsc still runs. */
    /* Shared by all ten tracks -- loaded before the first one and never
       reloaded. A missing props.vsc is not fatal: prop_init takes NULL and
       the props simply do not appear. */
    if (!scene_load("app0:assets/props.vsc", &props_scene))
        rlog("[rccars] no props.vsc -- the track's props will not appear\n");

    if (!load_track(0)) {
        sceKernelExitProcess(0);
        return 0;
    }
    load_car(menu.car);          /* optional -- the track alone is still useful */
    respawn();

    ui_init();

    if (car.has_rig)
        rlog("[rccars] rig: wheels %d %d %d %d  knuckles %d %d  "
                      "axles %d/%d  springs %d\n",
                      car.rig.wheel[0], car.rig.wheel[1], car.rig.wheel[2],
                      car.rig.wheel[3], car.rig.support[0], car.rig.support[1],
                      car.rig.axle_front, car.rig.axle_rear, car.rig.n_springs);
    rlog("[rccars] car: %s   tracks: %d\n",
                  rbcar_name(cur_car), N_TRACKS);
    rlog("[rccars] visuals: shadow %s  water %d spawn points  "
                  "checkpoints %d\n",
                  shadow.enabled ? "on" : "OFF (no __shadow texture)",
                  water.n_spawn, cps.n);
    rlog("[rccars] audio: %s  music %d race / %d menu  "
                  "resident %u KB  ambient '%s'\n",
                  audio_ok() ? "on" : "OFF",
                  audio_music_count(AUDIO_MUSIC_RACE),
                  audio_music_count(AUDIO_MUSIC_MENU),
                  sfx_resident_bytes() / 1024u,
                  TRACKS[cur_track].ambient[0] ? TRACKS[cur_track].ambient : "-");

    glEnable(GL_DEPTH_TEST);
    glDepthFunc(GL_LEQUAL);
    glEnable(GL_TEXTURE_2D);
    glEnable(GL_CULL_FACE);
    glCullFace(GL_BACK);
    /* Foliage and signage are alpha-keyed quads. Without this they draw as
       opaque rectangles with the cut-out region showing black. Opaque textures
       are unaffected: RGB565 has no alpha channel and the RGBA decoder fills
       alpha with 255, so every texel passes the test. */
    glEnable(GL_ALPHA_TEST);
    glAlphaFunc(GL_GREATER, 0.5f);
    glClearColor(0.42f, 0.68f, 0.87f, 1.f);
    glEnableClientState(GL_VERTEX_ARRAY);
    glEnableClientState(GL_TEXTURE_COORD_ARRAY);

    SceCtrlData pad;
    unsigned int prev_buttons = 0, frames = 0;
    SceRtcTick t0, t1, tf;
    /* frame budget accounting -- see the report by the fps line */
    SceRtcTick t_draw0, t_swap0, t_swap1;
    double acc_sim = 0.0, acc_draw = 0.0, acc_swap = 0.0;
/* rbcar_step_frame's own share of `sim`, and the ticks it was spent on -- so the
   collision queries, which is where a hardware log put 111 ms of a 118 ms frame
   while `draw` never moved off 5.7 ms. The draw side has had this split since the
   memcpy work; from `sim` alone there was no way to separate the queries from the
   water/fx/trace vertex updates sharing that span. prop_step is deliberately NOT
   in here: the props sleep, and colprof measures their contribution at zero.
   See colprof.c. */
double acc_phys = 0.0;
unsigned int acc_ticks = 0;
    sceRtcGetCurrentTick(&t0);
    tf = t0;
    double hz = (double)sceRtcGetTickResolution();

    for (;;) {
        sceCtrlPeekBufferPositive(0, &pad, 1);

        sceRtcGetCurrentTick(&t1);
        float dt = (float)((double)(t1.tick - tf.tick) / hz);
        tf = t1;
        if (dt > 0.1f) dt = 0.1f;      /* don't integrate through a hitch */

        /* START opens the menu; it owns the button from here, so the app quits
           from the menu's Quit row rather than by pressing START. */
        menu_input(&menu, pad.buttons, prev_buttons);
        if (menu.req_quit)
            break;
        if (menu.req_track >= 0) {
            load_track(menu.req_track);
            menu.req_track = -1;
            respawn();
        }
        if (menu.req_car >= 0) {
            load_car(menu.req_car);
            menu.req_car = -1;
            respawn();
        }
        if (menu.req_reload) {
            /* Texture quality is chosen at UPLOAD time, so nothing already on
               the GPU changes by itself -- both scenes have to come back in. */
            menu.req_reload = 0;
            scene_set_tex_quality(menu.tex_quality);
            scene_set_tex_swap_rb(menu.tex_swap_rb);
            load_track(cur_track);
            load_car(cur_car);
            respawn();
        }
        if (menu.req_restart) {
            menu.req_restart = 0;
            respawn();
        }
        /* Upgrades are plain indices the model reads each frame, so they apply
           live -- no reload, and the effect is visible while driving. */
        rc.tire_upgrade = menu.tires;
        rc.reso_upgrade = menu.reso;
        /* Deliberately NOT rb_boost_reset: changing the booster mid-race moves
           the capacity and the fill rate, and the meter fills toward the new
           one at the new rate. Topping it up on a menu press would be a free
           tank of boost every time the row is touched. */
        rc.boost_upgrade = menu.boost;

        /* The two upgrades the car WEARS, and the paint. Only rebuilt when one of
           them actually changes: carparts_apply rebinds textures and index counts,
           which is wasted work at 60 Hz for something the player changes by hand.
           The skin needs no reload for the same reason the tyres do not -- the
           alternate atlases are already uploaded, and this re-points a GLuint. */
        {
            static int shown_tires = -1, shown_boost = -1, shown_skin = -1;
            /* cur_car, not menu.car: menu.car can be a frame ahead of the model
               while req_car is pending, and this must repaint the car that is
               loaded. load_car does its own apply for the one arriving. */
            int want_skin = menu.skin[cur_car >= 0 && cur_car < MENU_N_CARS
                                      ? cur_car : 0];
            if (shown_tires != menu.tires || shown_boost != menu.boost
                || shown_skin != want_skin) {
                carparts_apply(&parts, &car, menu.tires, menu.boost, want_skin);
                /* A different exhaust is a different pipe, in a different
                   place -- the four booster_<n>_end nodes are up to 18 cm
                   apart on the Overkill. */
                fx_pipe_from_rig(&fx.em, &car.rig, menu.boost,
                                 rbcar_com_oy(cur_car));
                shown_tires = menu.tires;
                shown_boost = menu.boost;
                shown_skin = want_skin;
            }
        }

        /* Freeze the world while the menu is up. dt = 0 rather than skipping the
           step, so the water clock and the camera hold their phase instead of
           jumping when it closes. */
        if (menu.open)
            dt = 0.f;

        if ((pad.buttons & SCE_CTRL_SELECT) && !(prev_buttons & SCE_CTRL_SELECT))
            free_cam = !free_cam;
        /* SQUARE turns the shadow, the water animation and the checkpoint
           arrows off together, so "is this new code the problem?" is one
           button press rather than a rebuild. */
        if ((pad.buttons & SCE_CTRL_SQUARE) && !(prev_buttons & SCE_CTRL_SQUARE)) {
            show_vis = !show_vis;
            rlog("[rccars] visuals: %s\n", show_vis ? "on" : "off");
        }
        prev_buttons = pad.buttons;

        /* The water clock and the wave sprites run whether or not the player is
           driving, so they step outside the free-cam branch. */
        if (show_vis)
            water_step(&water, dt);
        /* NOT on show_vis. That button is for turning the port's own visual
           subsystems off while looking for a rendering bug, and checkpoint
           progression stopped being one of those when the crossing became the
           thing that counts a lap and raises the cue -- cps.lap feeds the
           opponents' rubber band. Only the ARROWS ride on show_vis now. */
        cp_step(&cps, veh.x, veh.y, veh.z, dt);
        /* `veh` is the pose MIRROR, written after the physics further down, so
           this reads last frame's position. Deliberate: cps.lap is an input to
           ai_step inside that same physics block, so the progression has to be
           settled before it. It costs one frame of lag on top of the crossing
           test's own one -- about 22 cm at this car's top speed -- and is worth
           writing down only because the rule it replaced was out by tens of
           metres. */
        /* One cue per crossing. cps.passed is an EDGE (checkpoint.h), written by
           every cp_step call, so this needs no previous-value bookkeeping of its
           own -- which is what it used to have, hung off `next` changing, and
           `next` changed at the midpoint between two checkpoints rather than at
           one of them. That was "the sound triggers somewhere in different
           places". */
        if (cps.passed >= 0) {
            sfx_checkpoint();
            rlog("[rccars] checkpoint %d passed (lap %d)\n",
                 cps.passed + 1, cps.lap);
        }

        float lx = axis(pad.lx), ly = axis(pad.ly);
        float rx = axis(pad.rx), ry = axis(pad.ry);
        float thr = (pad.buttons & SCE_CTRL_RTRIGGER) ? 1.f : 0.f;
        float brk = (pad.buttons & SCE_CTRL_LTRIGGER) ? 1.f : 0.f;

        float ex, ey, ez, vyaw, vpitch;
        if (free_cam) {
            fly_yaw += rx * 2.2f;
            fly_pitch -= ry * 1.6f;
            if (fly_pitch > 89.f) fly_pitch = 89.f;
            if (fly_pitch < -89.f) fly_pitch = -89.f;
            float r = fly_yaw * DEG, sp = 1.4f;
            fly_x += (sinf(r) * -ly + cosf(r) * lx) * sp;
            fly_z += (-cosf(r) * -ly + sinf(r) * lx) * sp;
            if (thr) fly_y += sp;
            if (brk) fly_y -= sp;
            ex = fly_x; ey = fly_y; ez = fly_z;
            vyaw = fly_yaw; vpitch = fly_pitch;
        } else {
            vehicle_input_t vin;
#ifdef PHYS_SELFTEST
            /* hold throttle so the speed profile can be checked against
               splAccelBase1 and speedBaseMax without a controller */
            thr = 1.f; brk = 0.f; lx = 0.f;
#endif
            vin.throttle = thr;
            vin.brake = brk;
            vin.steer = lx;
            vin.boost = (pad.buttons & SCE_CTRL_CROSS) ? 1 : 0;

            /* The physics.c placeholder used to be reachable here on TRIANGLE
               and from a menu row, for A/B against the transcribed model. Both
               are GONE -- the transcribed model is the game's own and there is
               nothing left to compare it against. TRIANGLE is free again; SELECT
               is still the free-fly camera. */

            if (use_rb) {
                /* The Jump action, before the tick -- see rbcar_jump. The
                   placeholder model has no equivalent and does not get one:
                   it has no body attitude to right and no momentum to add to. */
                int jumped = rbcar_jump(&rc, (pad.buttons & SCE_CTRL_CIRCLE)
                                             && !menu.open, dt);
                /* FIXED TIMESTEP -- not rbcar_step(dt).
                   rb_car_tick can only simulate 8 * 1/240 = 33.3 ms per call,
                   so a measured frame time put the car into slow motion below
                   30 fps and changed its substep pattern with every frame's
                   jitter. rbcar_step_frame banks the real time and spends it in
                   whole 1/60 ticks; see the comment on it in rbcar.h. */
                SceRtcTick t_p0, t_p1;
                int ticks;
                sceRtcGetCurrentTick(&t_p0);
                ticks = rbcar_step_frame(&rc, &phys_clock, thr, brk, lx,
                                         vin.boost, dt);
                sceRtcGetCurrentTick(&t_p1);
                acc_phys += (double)(t_p1.tick - t_p0.tick) / hz;
                if (ticks > 0)
                    acc_ticks += (unsigned)ticks;
                /* The props advance on the SAME banked time the car does --
                   rbcar_step_frame returns how many 1/60 ticks it actually
                   spent, so feeding them the measured frame time instead would
                   drift them against the car below 60 fps, which is the bug
                   "Frame pacing" exists to stop. */
                if (ticks > 0) {
                    int pi;
                    prop_step(&props, &rc, ticks * RBCAR_TICK_DT);
                    /* The opponents advance on the same banked ticks, but ONE AT
                       A TIME rather than on ticks*dt in one go: ai_step's
                       acceleration limit and cursor walk are written for a 1/60
                       tick, and handing it 2/60 would quietly halve the
                       resolution of both. It is cheap enough to loop -- a
                       polyline walk and a spline lookup per car. */
                    float ai_bump = 0.f;
                    for (pi = 0; pi < ticks; pi++) {
                        float h;
                        ai_step(&ai, cps.enabled ? &ai_tr : NULL,
                                rc.body.x[0], rc.body.x[1], rc.body.x[2],
                                cps.lap, RBCAR_TICK_DT);
                        /* Solid opponents. Immediately after the step so the
                           contact sees the pose it just wrote, and inside the
                           tick loop so a bump is resolved at the rate the
                           physics runs at rather than once a frame. */
                        h = ai_collide_player(&ai, &rc, RBCAR_TICK_DT);
                        if (h > ai_bump)
                            ai_bump = h;
                    }
                    /* One cue per frame however many ticks touched, the way the
                       prop hits are one cue per event -- sfx_car_hit rate-limits
                       itself on top. */
                    if (ai_bump > 0.f)
                        sfx_car_hit(ai_bump);
                    /* Every prop the car just STARTED touching makes its own
                       noise -- stone.sb names a wav per model, see prop_data.h
                       and sfx_prop_hit. prop_t.hit is an EDGE (prop.h) and
                       sfx_prop_hit rate-limits itself, so running this every
                       frame is correct rather than merely cheap. */
                    for (pi = 0; pi < props.n; pi++)
                        if (props.p[pi].hit)
                            sfx_prop_hit(props.p[pi].model, props.p[pi].pos,
                                         props.p[pi].hit_speed);
                }
                if (ticks < 0 && ++phys_clip_log <= 10)
                    rlog("[rccars] physics: frame took %.1f ms, past "
                                  "the %d-tick catch-up cap -- surplus dropped, "
                                  "the world is running slow\n",
                                  (double)dt * 1000.0, RBCAR_MAX_CATCHUP);
                if (jumped == RB_JUMP_RESET) {
                    /* The reset moved and re-levelled the car. The original snaps
                       its follow camera across a teleport (FUN_00508b50 calls
                       camUpdate with a 2e6 dt); cam_init is this port's version of
                       that, and without it the camera spends a second catching up
                       through the geometry it was just behind. */
                    cam_init(&rcam, &rc);
                    sfx_respawn();
                    rlog("[rccars] jump: righted the car\n");
                }
                /* mirror the pose into veh so the camera and HUD are unchanged */
                veh.x = rc.body.x[0];
                veh.y = rc.body.x[1];
                veh.z = rc.body.x[2];
                veh.yaw = rbcar_yaw_deg(&rc);
                veh.drifting = rb_tire_drifting(&rc);
            } else {
                vehicle_step(&veh, &vin, dt, ground_cb);
            }

            /* Articulate the car: steering knuckles, rolling wheels, axles that
               follow the suspension, springs that stretch. carAniProc1
               (0x00504820), transcribed in carani.c.

               The placeholder model has no per-wheel spring length and no steer
               ANGLE (only the stick), so it gets the reduced version: wheels that
               steer and roll, axles at rest. */
            if (car.has_rig) {
                if (use_rb) {
                    carani_update(&car.rig, &rc);
                    /* The whip antenna. Acceleration is finite-differenced from
                       the body's own linear velocity, which rb.c already keeps
                       (P * 1/m) -- differencing the POSITION instead would be a
                       second difference and mostly noise. */
                    {
                        static float prev_v[3];
                        float acc[3];
                        int k;
                        for (k = 0; k < 3; k++) {
                            acc[k] = (dt > 1e-5f)
                                ? (rc.body.v[k] - prev_v[k]) / dt : 0.f;
                            prev_v[k] = rc.body.v[k];
                        }
                        antenna_step(&antenna, rc.m, acc, rbcar_speed(&rc), dt);
                    }
                } else {
                    static float flat_spin = 0.f;
                    float r = rc.wheel[0].radius > 0.001f ? rc.wheel[0].radius
                                                          : 0.07f;
                    flat_spin += (veh.vlong / r) * dt;
                    flat_spin = fmodf(flat_spin, 2.f * 3.14159265f);
                    /* same sign convention as rb_car.steer: positive points the
                       wheels LEFT, so the stick is negated */
                    carani_update_flat(&car.rig, -lx * 30.f, flat_spin);
                    {
                        /* the placeholder has no body matrix; feed the antenna
                           an upright frame and its forward speed */
                        static const float up_m[16] = {1,0,0,0, 0,1,0,0,
                                                       0,0,1,0, 0,0,0,1};
                        static float prev_s;
                        float acc[3];
                        acc[0] = 0.f;
                        acc[1] = 0.f;
                        acc[2] = (dt > 1e-5f) ? (veh.vlong - prev_s) / dt : 0.f;
                        prev_s = veh.vlong;
                        antenna_step(&antenna, up_m, acc, veh.vlong, dt);
                    }
                }
            }

            /* Water is deliberately excluded from the collision TRIANGLES -- the
               car fords the river rather than driving on it -- so driving off the
               end of the sand drops the car into a hole where the seabed runs
               out. Respawn rather than fall forever. Measured against the ground
               the car was last placed on, not a constant: the tracks sit at very
               different heights (urban_2 starts at -0.45 m, beach_3 at 8.56). */
            if (veh.y < spawn_ground_y - 30.f) {
                rlog("[rccars] died: fell out of the world\n");
                respawn_checkpoint();
            }
            /* Drowned. The original puts reset volumes over its water -- the
               track scripts named `car_reset`, loaded at 0x004f27a0, with the
               engine logging "Car '%s' is out of collision bbox ... decide to
               reset it" when one fires. Those scripts are not in the port's data,
               so this stands in for them, and it is deliberately generous: the
               car has to be a whole DROWN_DEPTH under the surface, which fording
               the deepest stream on any track (13 cm) cannot reach. Anything
               shallower is left to carSurfaceDrag, which is the engine's own and
               already makes deep water nearly impossible to drive through. */
            {
                float wy;
                if (col_water_at(&col, veh.x, veh.z, &wy)
                    && veh.y < wy - DROWN_DEPTH) {
                    rlog("[rccars] died: drowned (%d cm under)\n",
                                  (int)((wy - veh.y) * 100.f));
                    respawn_checkpoint();
                }
            }
            /* The orbit offsets used to accumulate forever, so any stick nudge
               or drift left the camera permanently off-axis -- very visible now
               that the camera sits 0.79 m from the car instead of 3.2 m. Spring
               them back to centre when the stick is released. */
            orbit_yaw += rx * 2.2f;
            orbit_pitch -= ry * 1.2f;
            if (rx == 0.f) {
                float k = 90.f * dt;
                if (orbit_yaw > k) orbit_yaw -= k;
                else if (orbit_yaw < -k) orbit_yaw += k;
                else orbit_yaw = 0.f;
            }
            if (ry == 0.f) {
                float k = 60.f * dt;
                if (orbit_pitch > k) orbit_pitch -= k;
                else if (orbit_pitch < -k) orbit_pitch += k;
                else orbit_pitch = 0.f;
            }
            if (orbit_yaw > 150.f) orbit_yaw = 150.f;
            if (orbit_yaw < -150.f) orbit_yaw = -150.f;
            if (orbit_pitch > 60.f) orbit_pitch = 60.f;
            if (orbit_pitch < -40.f) orbit_pitch = -40.f;

            if (use_rb) {
                /* The game's own follow camera: 0.79 m behind and 0.36 m above,
                   pulled back with speed and throttle, with the yaw lagging
                   inside a 20-degree slack window. See cam.c. */
                cam_update(&rcam, &rc, lx, dt);

                /* the right stick orbits on top of it */
                /* eye = car - F(h)*dist, where F is the RENDERER's view forward
                   (-sin h, 0, -cos h). Note the +sin: the placeholder path below
                   uses the other convention. See cam.c. */
                float h = (rcam.yaw + orbit_yaw) * DEG;
                ex = rc.body.x[0] + sinf(h) * rcam.dist;
                ez = rc.body.x[2] + cosf(h) * rcam.dist;
                ey = rc.body.x[1] + rcam.height;
                vyaw = rcam.yaw + orbit_yaw;
                vpitch = cam_pitch_deg(&rcam) + orbit_pitch;
            } else {
                /* chase camera for the placeholder model */
                float h = (veh.yaw + orbit_yaw) * DEG;
                const float DIST = 3.2f, HEIGHT = 1.3f;
                ex = veh.x - sinf(h) * DIST;
                ez = veh.z + cosf(h) * DIST;
                ey = veh.y + HEIGHT;
                vyaw = veh.yaw + orbit_yaw;
                vpitch = orbit_pitch;
            }
        }

        /* --- audio ---------------------------------------------------------
           The listener is the CAMERA, not the car: the player hears from where
           they see. vyaw is the renderer's yaw, which is what mix_pan expects
           -- see "The renderer's yaw convention is MIRRORED" in CLAUDE.md. */
        {
            float eye3[3];
            eye3[0] = ex; eye3[1] = ey; eye3[2] = ez;

            /* The menu freezes the world (dt = 0) but not the sound thread, so
               the loops are stopped explicitly rather than left droning on a
               car that is no longer moving. */
            sfx_pause(menu.open);
            audio_music_group(menu.open ? AUDIO_MUSIC_MENU : AUDIO_MUSIC_RACE);

            /* The menu raises what the last input DID; turning that into one of
               the game's own interface sounds is this side's job, so menu.c
               stays linkable without a mixer. */
            switch (menu.cue) {
            case MENU_CUE_MOVE:   sfx_ui(SFX_UI_FOCUS); break;
            case MENU_CUE_CHANGE: sfx_ui(SFX_UI_PRESS); break;
            case MENU_CUE_SELECT: sfx_ui(SFX_UI_ENTER); break;
            case MENU_CUE_CLOSE:  sfx_ui(SFX_UI_BACK);  break;
            default: break;
            }
            menu.cue = MENU_CUE_NONE;

            sfx_volumes((float)menu.vol_sfx / (float)MENU_VOL_STEPS,
                        (float)menu.vol_music / (float)MENU_VOL_STEPS);

            if (use_rb)
                sfx_update(&rc, eye3, vyaw, dt);
            /* One positional engine per opponent. Driven every frame, not every
               tick: it is a voice's gain and pitch, not part of the model. The
               ratio is the opponent's own speed over its own top speed, so an
               opponent on a different car sounds like that car. Stopped past the
               audible radius so a distant field costs no voices at all -- there
               are 24 in the mixer and the player's three layers plus the surface
               loop and the bed have first call on them. */
            {
                int i;
                for (i = 0; i < SFX_AI_MAX; i++) {
                    if (i >= ai.n) {
                        sfx_ai_motor(i, eye3, 0.f, 0);
                        continue;
                    }
                    {
                        const ai_car *a = &ai.car[i];
                        /* Its own top speed, the same expression sfx.c uses for
                           the player's: speedBaseMax is km/h and the resonator
                           upgrade scales it, so the note rises with the upgrade
                           the way the car's actual top speed does. */
                        int r = a->rb.reso_upgrade;
                        float top = a->rb.tune.speed_base_max;
                        int near_enough;
                        if (r >= 0 && r < 4)
                            top *= a->rb.tune.resonator_speed[r];
                        top /= 3.6f;
                        if (top < 0.5f)
                            top = 0.5f;
                        near_enough = ai_within(&ai, i, eye3[0], eye3[1],
                                                eye3[2], SFX_AI_RMAX);
                        sfx_ai_motor(i, a->rb.body.x, a->speed / top,
                                     near_enough && !menu.open);
                    }
                }
            }

            /* The checkpoint cue used to live here, once a second inside the
               audio block, hung off `next` having changed since the last frame.
               It is up beside cp_step now, on the crossing edge cp_step raises. */
        }

        /* The dust, the smoke and the tyre marks. All three read the wheel
           CONTACTS, which only the transcribed model fills -- the placeholder has
           no per-wheel contact at all -- so they step only on that path. The eye
           is needed here rather than at draw time because FUN_0052e320 culls
           emission beyond 12 m, not drawing. */
        if (show_vis && use_rb) {
            float eye[3];
            int k;
            eye[0] = ex; eye[1] = ey; eye[2] = ez;

            /* THE OPPONENTS EMIT FIRST, and the order is load-bearing rather
             * than a preference: fx_step is fx_emit + fx_age, the pool is
             * shared, and fx_age must run ONCE. Anything emitting after it
             * spawns particles that skip a tick of ageing; anything calling the
             * full fx_step twice ages every particle twice. So every extra
             * emitter goes here, above, and the player's fx_step closes the
             * frame.
             *
             * The distance gate is the dust's own recovered radius applied a
             * level up. fx_emit tests it per WHEEL (FUN_0052e320 walks the
             * cameras and gives up past 12 m), which is correct and would reject
             * these anyway -- but only after paying for the surface query and
             * the per-wheel arithmetic on a car that cannot be seen. The
             * exhaust has no such rule of its own in the original, so without
             * this a car 80 m away would still be filling the shared pool with
             * smoke nobody can see. Squared, and horizontal: the same shape
             * draw_ai's own cap uses. */
            ai_fx_emitted = 0;
            for (k = 0; k < ai.n && k < AI_MAX_OPPONENTS; k++) {
                const ai_car *a = &ai.car[k];
                float dx = a->rb.body.x[0] - ex;
                float dz = a->rb.body.x[2] - ez;
                if (dx * dx + dz * dz > FX_EMIT_RANGE * FX_EMIT_RANGE)
                    continue;
                fx_emit(&fx, &ai_em[k], &a->rb, &col, eye, dt);
                ai_fx_emitted++;
            }

            fx_step(&fx, &rc, &col, eye, dt);
            trace_step(&traces, &rc, &col, dt);
        }

        /* Frame budget: mark the boundary between simulation and submission. See
           the report under the fps line for what this is for. */
        sceRtcGetCurrentTick(&t_draw0);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        perspective(65.f, (float)SCR_W / (float)SCR_H, 0.1f, 4000.f);
        glMatrixMode(GL_MODELVIEW);

        /* sky first, locked to the camera and not writing depth, so it can
           never clip the world or occlude anything */
        scene_stats_reset();

        glLoadIdentity();
        glRotatef(vpitch, 1.f, 0.f, 0.f);
        glRotatef(-vyaw, 0.f, 1.f, 0.f);
        glDepthMask(GL_FALSE);
        /* The sky rides on this camera-locked matrix, which is not the one the
           world frustum describes. scene_draw declines to cull BATCH_SKY for
           exactly that reason, but say so here too. */
        scene_cull_off();
        scene_draw(&track, BATCH_SKY, BATCH_SKY);
        glDepthMask(GL_TRUE);

        glLoadIdentity();
        glRotatef(vpitch, 1.f, 0.f, 0.f);
        glRotatef(-vyaw, 0.f, 1.f, 0.f);
        glTranslatef(-ex, -ey, -ez);
        /* Cull against the matrices that are loaded RIGHT NOW -- read back out
           of GL rather than rebuilt here, so the frustum cannot drift away from
           the draw and start eating geometry that is on screen. This is the
           port's answer to submitting the whole track every frame with no VBOs;
           see scene.h. */
        scene_frustum_from_gl();
        /* The solid world. Water is excluded here and drawn by water.c below,
           because it moves and because the foam has to blend; the transition
           decals are excluded because they MULTIPLY this rather than being part
           of it. */
        scene_draw(&track, BATCH_SKY | BATCH_ANY_WATER | BATCH_MODULATE
                          | BATCH_TRANSP, 0);

        /* The sand / wet-sand transition, and anything else the artists authored
           as a signed detail map. Same object as a tyre mark and the same blend:
           the engine's mode 5, 2*src*dst, so the strip's neutral-128 border
           leaves the ground untouched and its middle darkens it. See
           BATCH_MODULATE in scene.h.
           Simpler than trace.c in one way -- there is no per-vertex strength to
           lerp, so plain GL_MODULATE against a white current colour is enough
           and no combiner is needed. It DOES need the colour forced white: with
           no colour array bound, src = texture * current colour, and whatever
           drew last owns that. */
        glEnable(GL_BLEND);
        glBlendFunc(GL_DST_COLOR, GL_SRC_COLOR);
        glColor4f(1.f, 1.f, 1.f, 1.f);
        glDepthMask(GL_FALSE);
        /* Both halves, as trace.c and water.c do for their coplanar decals: the
           artists' own 1 cm lift stops separating anything far out, and the
           offset scales with depth slope but depends on what GXM makes of its
           units. */
        glEnable(GL_POLYGON_OFFSET_FILL);
        glPolygonOffset(-1.f, -2.f);
        scene_draw(&track, BATCH_MODULATE, BATCH_MODULATE);
        glPolygonOffset(0.f, 0.f);
        glDisable(GL_POLYGON_OFFSET_FILL);
        glDepthMask(GL_TRUE);
        glDisable(GL_BLEND);

        /* The marks the artists PAINTED on the track -- start line, checkpoint
           and arrow icons -- plus glass and the tagged foliage. Their alpha is a
           soft ramp and the ordinary path puts it through GL_GREATER 0.5, which
           is a hard cut; blended, the ramp survives and the mark reads as paint
           rather than a sticker. See BATCH_TRANSP.

           GREATER 0 rather than the test off, so the fully transparent region
           stays a real cut-out and does not cost a blend; depth writes off,
           because these are decals and several of them overlap the same ground.
           The polygon offset is the same pair the other decals use -- most of
           these icons are painted flat on the track surface. */
        glEnable(GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        glColor4f(1.f, 1.f, 1.f, 1.f);
        glEnable(GL_ALPHA_TEST);
        glAlphaFunc(GL_GREATER, 0.f);
        glDepthMask(GL_FALSE);
        glEnable(GL_POLYGON_OFFSET_FILL);
        glPolygonOffset(-1.f, -2.f);
        scene_draw(&track, BATCH_TRANSP, BATCH_TRANSP);
        glPolygonOffset(0.f, 0.f);
        glDisable(GL_POLYGON_OFFSET_FILL);
        glDepthMask(GL_TRUE);
        glDisable(GL_BLEND);
        /* Put the threshold back: scene_draw turns the test on per batch for the
           alpha-keyed ones and would otherwise inherit GREATER 0, which passes
           every cut-out texel and un-does the foliage. */
        glAlphaFunc(GL_GREATER, 0.5f);

        /* The shadow goes down on the terrain before anything transparent, and
           before the car, so the car is never drawn through its own decal. The
           tyre marks are the same kind of decal and go down FIRST, so the shadow
           darkens them rather than the other way round. */
        if (show_vis) {
            float eye[3];
            eye[0] = ex; eye[1] = ey; eye[2] = ez;
            if (use_rb)
                trace_draw(&traces, eye);
            if (use_rb)
                shadow_draw(&shadow, &col, rbcar_matrix(&rc));
            else
                shadow_draw_yaw(&shadow, &col, veh.x, veh.y, veh.z, veh.yaw);
        }

        if (car.n_batches) {
            /* The car is drawn under its own body matrix, so a model-space box
               tested against the world frustum means nothing. scene_draw already
               declines to cull a scene that has a rig, but a car packed without
               --rig would slip past that. */
            scene_cull_off();
            glPushMatrix();
            if (use_rb) {
                /* Take the body's whole orientation straight from the rigid
                   body. The engine's row-major row-vector matrix has the same
                   memory layout as an OpenGL column-major column-vector one, so
                   it goes in without a transpose.

                   This block used to draw from veh.yaw/pitch/roll in every case,
                   and the rb path only ever fills yaw -- pitch and roll stayed
                   zero, so the body rendered dead level no matter how the car
                   was actually lying. That is what made it look static while
                   sliding around. */
                /* NO half turn here, unlike the placeholder path below.
                 *
                 * The two models do not share a forward convention. vehicle_t
                 * travels along -Z at heading 0, so its render needs a half turn
                 * to line the mesh up. The rigid body travels along its local +Z
                 * -- measured dot(velocity, body +Z) = +0.998 -- and the mesh nose
                 * is also +Z (front wheels sit at z = +0.149, rear at -0.149), so
                 * the two already agree.
                 *
                 * Adding the half turn anyway drew the car facing exactly backwards
                 * (dot with velocity -0.999), which is why the view looked right
                 * only while reversing. */
                glMultMatrixf(rbcar_matrix(&rc));
                /* ...but model space is NOT body space, and assuming it was
                   floated every car off the ground. The rigid body's origin is
                   its centre of mass, and the game says where that is:
                   CenterMassOY, `com_oy` metres above the MODEL origin -- 0.0000
                   on the Overkill, 0.0323 on the other two. FUN_00475030 is the
                   original's own version of this line and negates exactly that
                   vector; see rb_data.h.

                   This used to subtract carani_wheel_plane_y(&car.rig) instead,
                   the mesh's own wheel-centre plane, which was the right number
                   only while gen_rb_data.py parked the com on that plane. It no
                   longer does, and the alignment now falls out of mount_y rather
                   than being arranged here: a resting wheel centre in body space
                   IS the model's wheel node. rccars_re/meshalign.c measures it. */
                glTranslatef(0.f, -rbcar_com_oy(cur_car), 0.f);
            } else {
                glTranslatef(veh.x, veh.y, veh.z);
                /* The model faces +Z (wheels sit at z=+0.147 front, -0.147 rear)
                   but travel is along -Z at heading 0, so the body needs a half
                   turn. That also mirrors its local X and Z, which is why the
                   slope angles have to be negated to stay the right way up. */
                glRotatef(veh.yaw + 180.f, 0.f, 1.f, 0.f);
                glRotatef(-veh.pitch, 1.f, 0.f, 0.f);
                glRotatef(-veh.roll, 0.f, 0.f, 1.f);
            }
            antenna_apply(&antenna);
            scene_draw(&car, BATCH_SKY | BATCH_ALPHA_LOWREF, 0);
            /* The exhaust last, OPAQUE, and with only the ALPHA-TEST REFERENCE
             * moved.
             *
             * Every <prefix>turbo_<n> texture is ARGB4444 with a large plateau
             * at alpha nibble 7 -- 0.467 once expanded to a byte, over 1 to 23%
             * of the image. The world's cut-out test is
             * glAlphaFunc(GL_GREATER, 0.5), which sits just above it, so every
             * one of those texels was being discarded and the pipes and
             * boosters had holes punched clean through them. Measured at the
             * meshes' own UVs on the packed cars: 25 of the Overkill's 76
             * booster-1 vertices sample alpha 119, 48 of booster-4's 214.
             *
             * THIS PASS USED TO BLEND, and that was a second bug in the other
             * direction -- it made solid brass velocity stacks and painted
             * muffler barrels 47% see-through, reported as "car boosters and
             * exhaust looks semi transparent". The plateau is not an opacity;
             * see BATCH_ALPHA_LOWREF in scene.h for the artwork and the shop
             * icons that settle it, and for the engine's own blend selector.
             *
             * GREATER 0 rather than no test at all, so the alpha-0 region -- the
             * bores looking into the stacks -- stays a real cut-out. Its own
             * pass rather than the body's, because the threshold is global state
             * in this fixed-function path and the rest of the car still needs
             * 0.5. Depth writes were never off here and stay on. */
            glAlphaFunc(GL_GREATER, 0.f);
            scene_draw(&car, BATCH_SKY | BATCH_ALPHA_LOWREF, BATCH_ALPHA_LOWREF);
            glAlphaFunc(GL_GREATER, 0.5f);
            /* The glance goes on last, over the paint and the exhaust both --
               EnvMapUpgrades exists precisely because the bolt-on pipe is
               env-mapped too. Inside the same matrix push, because it re-draws
               the very same geometry. */
            if (show_vis && use_rb) {
                float n3[9];
                env_normal_matrix(rbcar_matrix(&rc), vpitch, vyaw, n3);
                envmap_draw(&envmap, &car, n3);
            }
            glPopMatrix();
        }

        /* The opponents, after the player's car and before the water, for the
           same reason the props are: they are opaque and the foam blends over
           them. See draw_ai. */
        {
            float aeye[3];
            aeye[0] = ex; aeye[1] = ey; aeye[2] = ez;
            draw_ai(aeye);
        }

        /* Water last of the world: the sea surface and the stream are opaque,
           but the foam band and the breaking waves blend, so they have to come
           after everything they can be seen through. The checkpoint arrows go
           on top of all of it. */
        if (show_vis) {
            float eye[3], right[3], up[3];
            eye[0] = ex; eye[1] = ey; eye[2] = ez;
            /* Before the water: the props are opaque and the foam blends
               over them. After the track, so they are not drawn through it. */
            prop_draw(&props, eye);
            water_draw(&water, eye);
            /* Dust and smoke over the water as well as the land, and before the
               checkpoint arrows, which are meant to read through everything. */
            if (use_rb) {
                cam_basis(vpitch, vyaw, right, up);
                fx_draw(&fx, eye, right, up);
            }
            cp_draw(&cps, eye);
        }

        /* The menu goes over everything, in its own ortho pass. */
        if (menu.open)
            menu_draw(&menu, SCR_W, SCR_H);

        sceRtcGetCurrentTick(&t_swap0);
        vglSwapBuffers(GL_FALSE);
        sceRtcGetCurrentTick(&t_swap1);
        acc_sim  += (double)(t_draw0.tick - tf.tick) / hz;
        acc_draw += (double)(t_swap0.tick - t_draw0.tick) / hz;
        acc_swap += (double)(t_swap1.tick - t_swap0.tick) / hz;

        if (++frames >= 60) {
            sceRtcGetCurrentTick(&t1);
            double el = (double)(t1.tick - t0.tick) / hz;
            /* Integer FPS on purpose: this rlog drops the leading text
               and the first conversion when a float is the first vararg
               (AAPCS 8-byte alignment of the promoted double). Later floats are
               fine, so only the first argument has to be an int. */
rlog("[rccars] %u fps  spd=%d cm/s  pos=%d,%d,%d cm  yaw=%d%s\n",
                          (unsigned)(frames / el + 0.5),
                          (int)(vehicle_speed(&veh) * 100.f),
                          (int)(veh.x * 100.f), (int)(veh.y * 100.f), (int)(veh.z * 100.f),
                          (int)veh.yaw, veh.drifting ? " DRIFT" : "");
            /* WHERE THE FRAME GOES, so "GPU at 100%" can be confirmed or denied
               from the log instead of guessed at.
             *
             *   sim    everything before the first GL call -- input, physics,
             *          the water/fx/trace vertex updates
             *   draw   building and submitting the frame (CPU side)
             *   swap   time inside vglSwapBuffers
             *
             * `swap` is the tell. vglSwapBuffers is where the CPU waits for the
             * GPU to finish the previous frame, so a frame that is GPU-bound
             * spends most of itself there while sim+draw stay small. If instead
             * `draw` dominates, the cost is submission -- which for this port
             * means the per-frame vertex streaming, since it uses no VBOs and
             * pushes 3.03 MB of vertices on beach_1 every frame.
             *
             * `phys` splits the physics out of `sim`, with the tick count it was
             * spent on: the collision queries scale with the ticks, everything
             * else in `sim` runs once a frame, so phys/ticks is the number to
             * compare between two places on a track. A log where `sim` climbs and
             * `phys` does not is the water, fx and trace vertex updates, not the
             * collision grid. */
            rlog("[rccars] frame %d us = sim %d + draw %d + swap %d "
                          "(%d%% waiting on the GPU)\n",
                          (int)((acc_sim + acc_draw + acc_swap) * 1e6 / frames),
                          (int)(acc_sim * 1e6 / frames),
                          (int)(acc_draw * 1e6 / frames),
                          (int)(acc_swap * 1e6 / frames),
                          (int)(100.0 * acc_swap
                                / (acc_sim + acc_draw + acc_swap + 1e-9)));
            rlog("[rccars] sim: phys %d us over %d tick(s) = %d us/tick, "
                 "rest of sim %d us\n",
                 (int)(acc_phys * 1e6 / frames),
                 (int)acc_ticks,
                 (int)(acc_phys * 1e6 / (acc_ticks ? acc_ticks : 1u)),
                 (int)((acc_sim - acc_phys) * 1e6 / frames));
            /* And WHAT was submitted, from the last frame of the window, so the
               two lines can be read together. A spot that is slow because the
               camera can see an unusual amount of geometry says so here (`tris`
               up, `cull` down); one that is slow for a fill reason does not move
               either number, and the answer is overdraw. `keyed` is the
               punch-through subset -- those triangles cost the tile the hidden
               surface removal that makes this GPU fast, so a rise there is worth
               more than its count suggests. */
            {
                scene_stats_t st;
                scene_stats_get(&st);
                rlog("[rccars] draw: %u batches %u tris (%u keyed), "
                     "culled %u batches %u tris (%u%% of the track)\n",
                     st.batches, st.tris, st.tris_keyed,
                     st.batches_culled, st.tris_culled,
                     (unsigned)(100u * st.tris_culled
                                / (st.tris + st.tris_culled ? st.tris + st.tris_culled : 1u)));
            }
            acc_sim = acc_draw = acc_swap = acc_phys = 0.0;
            acc_ticks = 0;
            if (use_rb) {
                /* Physics telemetry, so a "it still looks wrong" report comes
                   with numbers. tilt is the body up axis against world up;
                   contacts are the four wheels; len is spring length in mm
                   (rest is about 98). All ints -- see the note above about the
                   first vararg. */
                const float *up = &rc.m[4];
                float c1 = up[1] > 1.f ? 1.f : (up[1] < -1.f ? -1.f : up[1]);
                rlog("[rccars] rb tilt=%d deg  contacts=%d%d%d%d  "
                              "len=%d %d %d %d mm  emb=%d  spd=%d cm/s  "
                              "boost=%d/%d %s\n",
                              (int)(acosf(c1) * 57.295776f),
                              rc.hit[0].active, rc.hit[1].active,
                              rc.hit[2].active, rc.hit[3].active,
                              (int)(rc.wheel[0].len * 1000.f),
                              (int)(rc.wheel[1].len * 1000.f),
                              (int)(rc.wheel[2].len * 1000.f),
                              (int)(rc.wheel[3].len * 1000.f),
                              rc.embedded,
                              (int)(rbcar_speed(&rc) * 100.f),
                              /* The boost meter. It has NO on-screen gauge yet,
                                 so a finite resource is otherwise invisible --
                                 this is the only way to see why boost stopped.
                                 The original draws one; 0x004eb200 is where it
                                 hands the pair to the HUD. */
                              (int)rc.boost_tank,
                              (int)rb_boost_capacity(&rc.tune, rc.boost_upgrade),
                              rc.boost_lock ? "locked" :
                                  (rc.in.boost ? "ON" : "--"));
            }
            if (ai.n > 0) {
                /* The field, once a second. Placing, and for the nearest
                   opponent the two numbers that say whether the rubber band is
                   working: how far ahead of the player it is, and what
                   coefficient that bought it. Without these, "the opponents feel
                   wrong" has nothing behind it. */
                int i, best = 0;
                float bd = 1e30f;
                for (i = 0; i < ai.n; i++) {
                    float dx = ai.car[i].rb.body.x[0] - rc.body.x[0];
                    float dz = ai.car[i].rb.body.x[2] - rc.body.x[2];
                    float d = dx * dx + dz * dz;
                    if (d < bd) { bd = d; best = i; }
                }
                rlog("[rccars] ai: %d cars, %d drawn, player P%d/%d;  nearest"
                             " %s %d m away  lead=%d m  coeff=%d%%  lap %d"
                             "  spd=%d cm/s  bump=%d cm%s\n",
                             ai.n, ai_drawn, ai_player_place(&ai), ai.n + 1,
                             ai.car[best].name, (int)sqrtf(bd),
                             (int)ai.car[best].lead,
                             (int)(ai.car[best].coeff * 100.f),
                             ai.car[best].lap,
                             (int)(ai.car[best].speed * 100.f),
                             /* How far off its recorded line a shove has this
                                one -- the only visible half of the bump model,
                                and without it "the opponents get knocked about
                                oddly" has nothing behind it. See ai.h. */
                             (int)(ai.car[best].bump * 100.f),
                             ai.car[best].airborne ? "  airborne" : "");
            }
            if (car.has_rig) {
                /* Rig telemetry, for the same reason: "the wheels look wrong"
                   should never need a guess. steer in degrees (body sense,
                   positive = wheels left), wheel rates in rad/s. */
                rlog("[rccars] rig steer=%d deg  spin=%d %d %d %d rad/s"
                              "  angle=%d %d %d %d mrad\n",
                              (int)rc.steer,
                              (int)rc.wheel[0].spin_w, (int)rc.wheel[1].spin_w,
                              (int)rc.wheel[2].spin_w, (int)rc.wheel[3].spin_w,
                              (int)(rc.wheel[0].spin * 1000.f),
                              (int)(rc.wheel[1].spin * 1000.f),
                              (int)(rc.wheel[2].spin * 1000.f),
                              (int)(rc.wheel[3].spin * 1000.f));
            }
            if (show_vis) {
                /* Visuals telemetry, same reasoning as the physics lines above:
                   "the shadow is gone" should come with a receiver count.
                   Distances in cm, all ints. */
                rlog("[rccars] vis shadow=%d tris  waves=%d live  "
                              "cp=%d/%d lap=%d  dist=%d cm  props=%d/%d drawn\n",
                              shadow.n_tris, water.n_live,
                              cps.next + 1, cps.n, cps.lap,
                              (int)(cp_dist_to_next(&cps, veh.x, veh.y, veh.z)
                                    * 100.f),
                              props.n_drawn, props.n);
                /* The car's own three, for the same reason as the rest: "there
                   is no dust" should arrive with a number. */
                rlog("[rccars] fx particles=%d  marks=%d quads  "
                              "glance=%d batches %d tris  pipe=%d %d %d mm\n",
                              fx.n_live, traces.n_quads,
                              envmap.n_batches, envmap.n_tris,
                              (int)(fx.em.pipe[0] * 1000.f),
                              (int)(fx.em.pipe[1] * 1000.f),
                              (int)(fx.em.pipe[2] * 1000.f));
                /* The field's own share. A count of the WHOLE field, so with
                   three opponents in view the glance line above is one car and
                   this one is three. Without it "the opponents still have no
                   smoke" is a guess: emitted=0 says they were all outside
                   FX_EMIT_RANGE, emitted>0 with no visible plume says the
                   throttle or the surface is the problem. */
                rlog("[rccars] ai fx emitters=%d/%d in range\n",
                              ai_fx_emitted, ai.n);
            }
            t0 = t1;
            frames = 0;
        }
    }

    /* Audio DOES have a teardown, and it needs one: two threads are running and
       both read the mixer, so they are stopped and joined before the process
       goes. This is why the app can exit cleanly here even though vitaGL cannot. */
    sfx_shutdown();
    audio_shutdown();

    /* AND THE LOG NOW NEEDS ONE TOO, for the same reason audio does: a thread owns
       the file (see rlog.h), so the last lines are still in RAM and the
       sceKernelExitProcess below would take them with it. Omitting this was safe
       only while rlog() flushed from the caller. It goes last so it also captures
       whatever the two shutdowns above had to say. */
    rlog_shutdown();

    /* this vitaGL exposes no teardown entry point; exiting releases the GPU */
    sceKernelExitProcess(0);
    return 0;
}
