/* Generated by gen_physics_header.py -- do not edit.
 * Values recovered from RC Cars' own Settings and Splines data,
 * converted to physical units using the loader scale constants.
 * See rccars_re/PHYSICS.md. */
#ifndef PHYSICS_DATA_H
#define PHYSICS_DATA_H

typedef struct { float in, out; } curve_pt_t;

typedef struct {
    const char *name;
    float speed_base_max;
    float speed_boost_max;
    float boost_up;
    float boost_down;
    float air_drag;
    float bearing_friction;
    float grip_front;
    float grip_rear;
    float drift_rear;
    float drift_angle_on;
    float drift_speed_on;
    float coeff_sand;
    float coeff_water;
    float steer_max_deg;
    float susp_k_pos;
    float susp_k_speed;
    float susp_length;
    float susp_len_min;
    float susp_len_max;
    float moment_ox;
    float moment_oz;
    float len_axe;
    float touch_point;
    const curve_pt_t *accel;  int accel_n;
    const curve_pt_t *steer;  int steer_n;
} car_phys_t;

static const curve_pt_t accel1[] = {{0.000000f,9.550539f}, {8.035714f,8.934223f}, {10.242929f,2.864129f}, {15.364392f,1.067980f}, {25.000000f,-0.000000f}};
static const curve_pt_t steer1[] = {{0.000000f,0.000000f}, {2.000000f,40.000000f}};
static const curve_pt_t accel2[] = {{0.000000f,9.600000f}, {10.000000f,7.000000f}, {15.000000f,3.000000f}, {25.000000f,1.000000f}, {30.000000f,-0.000000f}};
static const curve_pt_t steer2[] = {{0.000000f,0.000000f}, {2.000000f,40.000000f}};
static const curve_pt_t accel3[] = {{0.000000f,8.000000f}, {15.220588f,0.266010f}, {20.000000f,-0.000000f}};
static const curve_pt_t steer3[] = {{0.000000f,0.000000f}, {2.000000f,40.000000f}};

static const car_phys_t CARS[3] = {
  { "Overkill",
    /* speed_base_max     */ 27.000000f,
    /* speed_boost_max    */ 35.000000f,
    /* boost_up           */ 1.500000f,
    /* boost_down         */ 5.454546f,
    /* air_drag           */ 0.032323f,
    /* bearing_friction   */ 0.202020f,
    /* grip_front         */ 0.700000f,
    /* grip_rear          */ 0.700000f,
    /* drift_rear         */ 0.218182f,
    /* drift_angle_on     */ 10.000000f,
    /* drift_speed_on     */ 3.000000f,
    /* coeff_sand         */ 0.060606f,
    /* coeff_water        */ 0.191919f,
    /* steer_max_deg      */ 30.000000f,
    /* susp_k_pos         */ 64.000000f,
    /* susp_k_speed       */ 4.181818f,
    /* susp_length        */ 0.217879f,
    /* susp_len_min       */ 0.100000f,
    /* susp_len_max       */ 1.100000f,
    /* moment_ox          */ 1.045455f,
    /* moment_oz          */ 1.868687f,
    /* len_axe            */ 0.089394f,
    /* touch_point        */ 0.101010f,
    accel1, (int)(sizeof(accel1)/sizeof(curve_pt_t)),
    steer1, (int)(sizeof(steer1)/sizeof(curve_pt_t)) },
  { "Buggy",
    /* speed_base_max     */ 27.000000f,
    /* speed_boost_max    */ 35.000000f,
    /* boost_up           */ 1.500000f,
    /* boost_down         */ 5.454546f,
    /* air_drag           */ 0.032323f,
    /* bearing_friction   */ 0.202020f,
    /* grip_front         */ 0.700000f,
    /* grip_rear          */ 0.700000f,
    /* drift_rear         */ 0.218182f,
    /* drift_angle_on     */ 10.000000f,
    /* drift_speed_on     */ 3.000000f,
    /* coeff_sand         */ 0.060606f,
    /* coeff_water        */ 0.191919f,
    /* steer_max_deg      */ 30.000000f,
    /* susp_k_pos         */ 43.000000f,
    /* susp_k_speed       */ 4.181818f,
    /* susp_length        */ 0.242626f,
    /* susp_len_min       */ 0.100000f,
    /* susp_len_max       */ 1.100000f,
    /* moment_ox          */ 1.045455f,
    /* moment_oz          */ 1.868687f,
    /* len_axe            */ 0.087879f,
    /* touch_point        */ 0.101010f,
    accel2, (int)(sizeof(accel2)/sizeof(curve_pt_t)),
    steer2, (int)(sizeof(steer2)/sizeof(curve_pt_t)) },
  { "Hummer",
    /* speed_base_max     */ 27.000000f,
    /* speed_boost_max    */ 35.000000f,
    /* boost_up           */ 1.500000f,
    /* boost_down         */ 5.454546f,
    /* air_drag           */ 0.032323f,
    /* bearing_friction   */ 0.202020f,
    /* grip_front         */ 0.700000f,
    /* grip_rear          */ 0.700000f,
    /* drift_rear         */ 0.218182f,
    /* drift_angle_on     */ 10.000000f,
    /* drift_speed_on     */ 3.000000f,
    /* coeff_sand         */ 0.060606f,
    /* coeff_water        */ 0.191919f,
    /* steer_max_deg      */ 30.000000f,
    /* susp_k_pos         */ 64.000000f,
    /* susp_k_speed       */ 4.181818f,
    /* susp_length        */ 0.217879f,
    /* susp_len_min       */ 0.100000f,
    /* susp_len_max       */ 1.100000f,
    /* moment_ox          */ 1.045455f,
    /* moment_oz          */ 1.868687f,
    /* len_axe            */ 0.089394f,
    /* touch_point        */ 0.101010f,
    accel3, (int)(sizeof(accel3)/sizeof(curve_pt_t)),
    steer3, (int)(sizeof(steer3)/sizeof(curve_pt_t)) },
};

#endif
