/* Generated by rccars_re/gen_rb_data.py -- do not edit.
 *
 * Per-car tuning for the transcribed model (rb.c / contact.c /
 * collide.c), taken from the game's own Settings, Splines and
 * Scripts/upgrades.ini with the conversions the loaders actually
 * apply. See rccars_re/PHYSICS.md. */
#ifndef RB_DATA_H
#define RB_DATA_H

#include "rb.h"

static const rb_curve_pt rb_accel1[] = {{0.000000f,6.000000f}, {16.000000f,3.000000f}, {32.000000f,-0.000000f}};
static const rb_curve_pt rb_restr1[] = {{0.000000f,2.000000f}, {15.000000f,-0.000000f}};
static const rb_curve_pt rb_accel2[] = {{0.000000f,9.000000f}, {10.000000f,8.000000f}, {25.000000f,2.000000f}, {38.000000f,-0.000000f}};
static const rb_curve_pt rb_restr2[] = {{0.000000f,-4.000000f}, {10.000000f,-3.000000f}, {25.000000f,-0.000000f}};
static const rb_curve_pt rb_accel3[] = {{0.000000f,4.000000f}, {22.000000f,4.000000f}, {30.000000f,-0.000000f}};
static const rb_curve_pt rb_restr3[] = {{0.000000f,6.000000f}, {11.507380f,5.705911f}, {20.000000f,-0.000000f}};

/* Geometry and mass are NOT in the .crs files -- the original takes
 * them from the car's mesh and its cdt block. These are measured from
 * the extracted models (see rccars_obj) with lenAxe as the half-track.
 */
typedef struct {
    const char *name;
    int   nwheels;
    float mass;
    float extent[3];      /* box extents for the inertia tensor */
    float half_track;     /* lenAxe */
    float half_base;      /* from the mesh */
    float mount_y;
    float steer_max_deg;  /* AngleSteer */
    rb_tuning tune;
    float len_free, len_min, len_max, sag, k_speed, radius;
} rb_car_data;

static const rb_car_data RB_CARS[3] = {
  { "Overkill",
    /* nwheels        */ 4,
    /* mass           */ 2.000000f,
    /* extent         */ {0.140000f,0.106000f,0.422000f},
    /* half_track     */ 0.141000f,
    /* half_base      */ 0.149000f,
    /* mount_y        */ 0.098442f,
    /* steer_max_deg  */ 30.000000f,
    { /* tune */
      /* moment_ox     */ 1.045455f,
      /* moment_oz     */ 1.868687f,
      /* len_axe       */ 0.089394f,
      /* angle_up      */ 0.000000f,
      /* angle_down    */ 0.000000f,
      /* bearings      */ 0.202020f,
      /* air_res       */ 0.032323f,
      /* front_tires   */ 0.700000f,
      /* rear_tires    */ 0.700000f,
      /* angle_drift   */ 10.000000f,
      /* speed_drift   */ 3.000000f,
      /* drift_rear    */ 0.218182f,
      /* deep_sand     */ 0.060606f,
      /* water         */ 0.191919f,
      /* tire_upgrade  */ {0.900000f,1.020000f,1.100000f,1.200000f},
      /* spin_extra    */ 0.000000f,
      /* speed_base    */ 27.000000f,
      /* speed_boost   */ 35.000000f,
      /* boost_ratio   */ 1.296296f,
      /* reso_speed    */ {0.920000f,0.970000f,1.070000f,1.120000f},
      /* reso_accel    */ {0.700000f,0.800000f,0.900000f,1.000000f},
      /* accel curve   */ { rb_accel1, 3 },
      /* restrict      */ { rb_restr1, 2 },
      /* cdt_rad_wheel */ 0.071818f,
      /* cdt_rad_back  */ 0.071818f,
      /* cdt_front_x   */ 0.000000f,  /* FrontWheelDeltaX: scale unrecovered */
      /* cdt_side_x    */ 0.050000f,
      /* body_sphere   */ {
        { {-0.070000f,0.031179f,0.075758f}, 0.051010f, 0.000000f },  /* X clamped */
        { {0.000000f,0.128540f,-0.160040f}, 0.051010f, 0.000000f },  /* THE PORT'S: roof, aft, 28 mm proud */
        { {0.000000f,0.128540f,0.181040f}, 0.051010f, 0.000000f },  /* THE PORT'S: roof, fore, 28 mm proud */
      },
    },
    /* len_free */ 0.217879f,
    /* len_min  */ 0.021788f,
    /* len_max  */ 0.239667f,
    /* sag      */ 0.119437f,
    /* k_speed  */ 4.181818f,
    /* radius   */ 0.071818f },
  { "Buggy",
    /* nwheels        */ 4,
    /* mass           */ 2.000000f,
    /* extent         */ {0.216000f,0.157500f,0.532800f},
    /* half_track     */ 0.146700f,
    /* half_base      */ 0.182250f,
    /* mount_y        */ 0.146679f,
    /* steer_max_deg  */ 30.000000f,
    { /* tune */
      /* moment_ox     */ 1.045455f,
      /* moment_oz     */ 1.868687f,
      /* len_axe       */ 0.087879f,
      /* angle_up      */ 35.454545f,
      /* angle_down    */ 26.363636f,
      /* bearings      */ 0.202020f,
      /* air_res       */ 0.032323f,
      /* front_tires   */ 0.700000f,
      /* rear_tires    */ 0.700000f,
      /* angle_drift   */ 10.000000f,
      /* speed_drift   */ 3.000000f,
      /* drift_rear    */ 0.218182f,
      /* deep_sand     */ 0.060606f,
      /* water         */ 0.191919f,
      /* tire_upgrade  */ {0.970000f,1.120000f,1.250000f,1.450000f},
      /* spin_extra    */ 0.000000f,
      /* speed_base    */ 27.000000f,
      /* speed_boost   */ 35.000000f,
      /* boost_ratio   */ 1.296296f,
      /* reso_speed    */ {0.980000f,1.040000f,1.100000f,1.170000f},
      /* reso_accel    */ {0.750000f,0.850000f,0.950000f,1.000000f},
      /* accel curve   */ { rb_accel2, 4 },
      /* restrict      */ { rb_restr2, 3 },
      /* cdt_rad_wheel */ 0.049091f,
      /* cdt_rad_back  */ 0.067438f,
      /* cdt_front_x   */ 0.000000f,  /* FrontWheelDeltaX: scale unrecovered */
      /* cdt_side_x    */ 0.050000f,
      /* body_sphere   */ {
        { {-0.108000f,0.012121f,0.184848f}, 0.051010f, 0.000000f },  /* X Y Y>floor clamped */
        { {0.000000f,0.080840f,-0.246890f}, 0.051010f, 0.000000f },  /* THE PORT'S: roof, aft */
        { {0.000000f,0.080840f,0.183890f}, 0.051010f, 0.000000f },  /* THE PORT'S: roof, fore */
      },
    },
    /* len_free */ 0.242626f,
    /* len_min  */ 0.024263f,
    /* len_max  */ 0.266889f,
    /* sag      */ 0.095948f,
    /* k_speed  */ 4.181818f,
    /* radius   */ 0.049091f },
  { "Hummer",
    /* nwheels        */ 6,
    /* mass           */ 2.000000f,
    /* extent         */ {0.194220f,0.118170f,0.507780f},
    /* half_track     */ 0.170235f,
    /* half_base      */ 0.182520f,
    /* mount_y        */ 0.098442f,
    /* steer_max_deg  */ 30.000000f,
    { /* tune */
      /* moment_ox     */ 1.045455f,
      /* moment_oz     */ 1.868687f,
      /* len_axe       */ 0.089394f,
      /* angle_up      */ 0.000000f,
      /* angle_down    */ 0.000000f,
      /* bearings      */ 0.202020f,
      /* air_res       */ 0.032323f,
      /* front_tires   */ 0.700000f,
      /* rear_tires    */ 0.700000f,
      /* angle_drift   */ 10.000000f,
      /* speed_drift   */ 3.000000f,
      /* drift_rear    */ 0.218182f,
      /* deep_sand     */ 0.060606f,
      /* water         */ 0.191919f,
      /* tire_upgrade  */ {0.970000f,1.050000f,1.120000f,1.250000f},
      /* spin_extra    */ 0.000000f,
      /* speed_base    */ 27.000000f,
      /* speed_boost   */ 35.000000f,
      /* boost_ratio   */ 1.296296f,
      /* reso_speed    */ {0.980000f,1.050000f,1.110000f,1.170000f},
      /* reso_accel    */ {0.750000f,0.850000f,0.950000f,1.000000f},
      /* accel curve   */ { rb_accel3, 3 },
      /* restrict      */ { rb_restr3, 3 },
      /* cdt_rad_wheel */ 0.059091f,
      /* cdt_rad_back  */ 0.059091f,
      /* cdt_front_x   */ 0.000000f,  /* FrontWheelDeltaX: scale unrecovered */
      /* cdt_side_x    */ 0.050000f,
      /* body_sphere   */ {
        { {-0.097110f,0.034691f,0.015152f}, 0.051010f, 0.000000f },  /* X clamped */
        { {0.000000f,0.138530f,-0.209900f}, 0.051010f, 0.000000f },  /* THE PORT'S: roof, aft, 4 mm proud */
        { {0.000000f,0.138530f,0.195860f}, 0.051010f, 0.000000f },  /* THE PORT'S: roof, fore, 4 mm proud */
      },
    },
    /* len_free */ 0.217879f,
    /* len_min  */ 0.021788f,
    /* len_max  */ 0.239667f,
    /* sag      */ 0.119437f,
    /* k_speed  */ 4.181818f,
    /* radius   */ 0.059091f },
};

/* Scripts/upgrades.ini [BOOSTERS]. VISUAL SELECTION ONLY: the model
 * does not read this, because where the original applies it is not
 * recovered. See carparts.c and the note on menu_t.boost. */
static const float RB_BOOSTER_UPGRADE[3][4] = {
    { 0.800000f, 0.970000f, 1.110000f, 1.240000f },   /* Overkill */
    { 0.850000f, 1.000000f, 1.150000f, 1.300000f },   /* Buggy */
    { 0.850000f, 1.000000f, 1.150000f, 1.300000f },   /* Hummer */
};

/* Camera, from Settings/Camera.crs via physLoadCamera (0x004f9da0).
 * The conversions are that function's own clamped affine maps. */
typedef struct {
    float dist_xz;     /* defDistXZ, metres behind */
    float dist_y;      /* defDistY, metres above */
    float acc_dist_y;  /* accDistY, vertical pull-back per second */
    float acc_alpha;   /* accAlpha, yaw pull-back scale */
    float vis_turn;    /* VisTurn, degrees of look-into-turn */
} rb_camera_data;

static const rb_camera_data RB_CAMERA = {
    /* dist_xz    */ 0.792929f,   /* raw 30 */
    /* dist_y     */ 0.363636f,   /* raw 30 */
    /* acc_dist_y */ 0.100000f,   /* raw 1 */
    /* acc_alpha  */ 0.494949f,   /* raw 50 */
    /* vis_turn   */ 11.818181f    /* raw 70 */
};

#endif
