/* Generated by rccars_re/gen_str_data.py -- do not edit.
 *
 * THE GAME'S OWN AUTHORED TEXT, decoded out of
 * Language/Game/english.tbl. Every string below is the original's,
 * character for character; nothing here is written by this port.
 *
 * The .tbl is 892 entries XORed against one arithmetic ramp that
 * runs across the concatenated payloads -- see the generator's
 * docstring for the cipher and for how the per-track arrays are put
 * back into THIS port's track order.
 *
 * A multi-line blurb keeps its '\n': the original draws three or
 * five lines and so does mainmenu.c. */
#ifndef STR_DATA_H
#define STR_DATA_H

#define STR_N_TRACKS 10
#define STR_N_CARS   3
/* The three PURCHASABLE levels above Default, which is what the
   original's own enumUpgrades walks -- its left arrow is grey at
   level 1 on the game's own screenshot, so Default is not in it. */
#define STR_N_PART_LEVELS 3

/* 40000 + t -- the name the menu shows, in tracks.h's order */
static const char *const STR_TRACK_NAME[] = {
    "Surf",
    "Camping",
    "Fort",
    "War path",
    "Rancho",
    "Mines",
    "Fishers",
    "Silo",
    "AWACS",
    "AAD base",
};

/* 40020 + t -- three lines, dlgSTAT's staticTrackInfo */
static const char *const STR_TRACK_SHORT[] = {
    "Hot Sun - Hot Sand\nHigh waves - cool Girls.\nTip: Beware of angry surfers!",
    "Gas station, tunnels,\nDrivers don't like you much.\nTip: just watch out!",
    "Old fort on the beach,\nTunnels filled with cars.\nTip: big, heavy, fast cars",
    "Long way along the beach\nSoldiers on watch-towers\nTip: Waves get in your way",
    "There are no cows here\nBut fences still stand\nTip: very old wooden floors",
    "Abandoned mines\nRails, steep slopes\nTip: Cars can jump!",
    "Abandoned fishing village,\nDust, rust and peace\nTip: men leave  - dogs stay",
    "Nice, flat, hard road\nMilitary stuff all over\nTip: cowards invented brakes",
    "Radars scanning skies,\nKhaki is the main color here\nTip: Soldiers like to shoot!",
    "Heart of military base\nCool guys with guns\nTip: Get by them fast!",
};

/* 40030 + t -- five lines, dlgMAPINFO's staticTrackInfo */
static const char *const STR_TRACK_LONG[] = {
    "Adventure on the beach.\nSpook innocent campers.\nMake sharp turns on hot sand.\nKick your pal's car in the sea.\nBeware of skids and surfers!",
    "Long long tunnels,\nBig, ugly, fast cars\nRisky drive between wheels\nBang! You're flying high!\nRight into the sea.",
    "There is an old fort\nWith cobblestone road\nAnd asphalt road with cars\nDrivers don't like you much\nSo, watch out, speedster!",
    "Along the beach\nBetween high waves\nAround military junkyard\nUnder the fire from the towers\nTo the hall of fame!",
    "Cow bones\nWooden fences and wagons\nReal Wild West\nRide the Tornado\nStart your Rodeo!",
    "Miners left this mine\nLeft their tools behind\nRails and tubs and shovels\nBut remember one thing:\nCars can jump!",
    "No one lives here now\nBesides dogs and spiders\nMaybe you can catch gold fish\nDon't get caught in the net\nAnd watch out wild animals!",
    "Nuclear Base\nHeart of war\nPrepare to push \"start\" button\nBut don't confuse it\nWith the Big Red Button!",
    "Radars search the skies\nYou are on the ground\nRadars cannot see you\nBut soldiers can!\nGet fast, save car!",
    "Air Defense Base\nIt is not easy to get in\nOnly cool racers come here\nUse wicked tricks\nTo dodge bullets!",
};

/* 40040 + t -- three lines, the main menu's carousel caption */
static const char *const STR_TRACK_MENU[] = {
    "Start the race along the sea\nMake sharp turns on hot sand.\nBeware of skids and surfers!",
    "Burn the road\nWith power boost\nMake tricks to be the first",
    "Ride the wind\nOvercome big cars\nBut don't be flattened by them",
    "Along the beach\nBetween high waves\nTo the hall of fame!",
    "Real Wild West\nRide the Tornado\nStart your Rodeo!",
    "Like Tornado\nIn the tunnels\nFaster then echoing sound",
    "Win race here\nCatch gold fish!\nWatch out for wild dogs!",
    "Prepare to push \"start\" button\nBut don't confuse it\nWith the Big Red Button!",
    "Radars cannot see you\nBut soldiers can!\nGo fast, save your car!",
    "It's not easy to get in\nCool racers come here\nTo outrun bullets!",
};

/* 40050 + t -- the engine's internal name. Emitted so the ordering above can be checked against tracks.h at a glance */
static const char *const STR_TRACK_BASE[] = {
    "Beach_1",
    "Beach_2",
    "Beach_3",
    "Beach_4",
    "Country_1",
    "Country_2",
    "Country_3",
    "Country_4",
    "Urban_1",
    "Urban_2",
};

/* the three cars, in rb_data.h's order */
static const char *const STR_CAR_NAME[] = {
    "Road Rage RR",
    "Tornado Buggy TB",
    "Warhammer WH",
};

/* each car's seven-line spec block */
static const char *const STR_CAR_INFO[] = {
    "Metalloplastic body\nHigh 4w axle suspension\nWeight: 2.8 kg\nMax Speed: 36 km/h\nVolume: 1.5 c/cm\nBoost capacity: 53 units\nTire type: Non Spiked",
    "Reinforced plastic body\nLow 4w ind. suspension\nWeight: 2.2 kg\nMax Speed: 43 km/h\nVolume: 2.2 c/cm\nBoost capacity: 50 units\nTyre type: Non Spiked",
    "Metalloplastic body\nHigh 6w axle suspension\nWeight: 3.6 kg\nMax Speed: 35 km/h\nVolume: 2.4 c/cm\nBoost capacity: 65 units\nTyre type: Non Spiked",
};

/* the same, first three lines -- what a narrow column takes */
static const char *const STR_CAR_INFO_SHORT[] = {
    "Metalloplastic body\nHigh 4w axle suspension\nWeight: 2.8 kg",
    "Reinforced plastic body\nLow 4w ind. suspension\nWeight: 2.2 kg",
    "Metalloplastic body\nHigh 6w axle suspension\nWeight: 3.6 kg",
};

/* 40112 + 6c + 2L -- the booster's name for car c at level L */
static const char *const STR_PART_BOOSTER_NAME[STR_N_CARS][3] = {
    {
        "RRB-C \"White Flash\"",
        "RRB-B \"Blue Flash\"",
        "RRB-1A \"Flashstorm\"",
    },
    {
        "TBB-C \"Flame fist\"",
        "TBB-B \"Flame strike\"",
        "TBB-1A \"Firestarter\"",
    },
    {
        "WHB-C\"Destructor\"",
        "WHB-B \"Demolisher\"",
        "WHB-1A \"Devastator\"",
    },
};

/* and its two-line effect block */
static const char *const STR_PART_BOOSTER_INFO[STR_N_CARS][3] = {
    {
        "Boost accumulation +20%\nMax Boost: 64 units",
        "Boost accumulation +30%\nMax Boost: 73 units",
        "Boost accumulation +45%\nMax Boost: 83 units",
    },
    {
        "Boost accumulation +25%\nMax Boost: 59 units",
        "Boost accumulation +45%\nMax Boost: 68 units",
        "Boost accumulation +55%\nMax Boost: 76 units",
    },
    {
        "Boost accumulation +20%\nMax Boost: 77 units",
        "Boost accumulation +35%\nMax Boost: 88 units",
        "Boost accumulation +50%\nMax Boost: 100 units",
    },
};

/* 40140 + 6c + 2L -- the engine's name for car c at level L */
static const char *const STR_PART_ENGINE_NAME[STR_N_CARS][3] = {
    {
        "RR-Nitro-C\"Firefly\"",
        "RR-Nitro-B \"Fireball\"",
        "RR-Nitro-1A \"Firestorm\"",
    },
    {
        "TB-Nitro-C \"Red Panther\"",
        "TB-Nitro-B \"Red dragon\"",
        "TB-Nitro-1A \"Devil Inside\"",
    },
    {
        "WH-Nitro-C \"Road King\"",
        "WH-Nitro-B \"Road Prince\"",
        "OWH-Nitro-1A \"Road God\"",
    },
};

/* and its two-line effect block */
static const char *const STR_PART_ENGINE_INFO[STR_N_CARS][3] = {
    {
        "Max Speed: 38 km/h\nAcceleration: + 10%",
        "Max Speed: 40 km/h\nAcceleration: + 15%",
        "Max Speed: 42 km/h\nAcceleration: + 25%",
    },
    {
        "Max Speed: 45 km/h\nAcceleration: + 20%",
        "Max Speed: 48 km/h\nAcceleration: + 30%",
        "Max Speed: 51 km/h\nAcceleration: + 45%",
    },
    {
        "Max Speed: 39 km/h\nAcceleration: +15%",
        "Max Speed: 41 km/h\nAcceleration: +25%",
        "Max Speed: 44 km/h\nAcceleration: + 30%",
    },
};

/* 40170 + 6c + 2L -- the tires's name for car c at level L */
static const char *const STR_PART_TIRES_NAME[STR_N_CARS][3] = {
    {
        "RRT-C \"Hypervelocity\"",
        "RRT-B \"Megavelocity\"",
        "RRT-1A \"Ultravelocity\"",
    },
    {
        "TBT-C \"Speedburst\"",
        "TBT-B \"Speedkill\"",
        "TBT-1A\"Ultrascorcher\"",
    },
    {
        "WHT-C\"Bloodhound\"",
        "WHT-B \"Hellhound\"",
        "WHT-1A \"Meatgrinder\"",
    },
};

/* and its two-line effect block */
static const char *const STR_PART_TIRES_INFO[STR_N_CARS][3] = {
    {
        "Slightly Spiked type\nStability +10%",
        "Medium Spiked type\nStability +15%",
        "Heavily Spiked type\nStability +20%",
    },
    {
        "Slightly Spiked type\nStability +10%",
        "Meduim Spiked type\nStability +15%",
        "Heavily Spiked type\nStability +25%",
    },
    {
        "Slightly Spiked type\nStability +10%",
        "Medium Spiked type\nStability +15%",
        "Heavily Spiked type\nStability +25%",
    },
};

/* 40550 + r -- the rank ladder the player card names, bottom rung first. player_rank() is FUN_004e85d0's thresholds over it */
static const char *const STR_RANK[] = {
    "Retard",
    "Casual",
    "Rookie",
    "Driver",
    "Racer",
    "Speedster",
    "Professional",
    "Contender",
    "Champion",
    "Super Star",
};

/* The front end's own words. */
#define STR_UI_MAIN_MENU       "Main menu"
#define STR_UI_RACE            "Race"
#define STR_UI_QUICK_RACE      "Quick race"
#define STR_UI_RACE_SUMMARY    "Race summary"
#define STR_UI_MAP_AND_INFO    "Map and info"
#define STR_UI_TRACK_STATS     "Track stats"
#define STR_UI_GARAGE          "Garage"
#define STR_UI_N_LAPS          "Number of laps"
#define STR_UI_SKILL           "Opponents skill"
#define STR_UI_SCREENSHOTS     "Screenshots"
#define STR_UI_SORT_BY         "Sort results by"
#define STR_UI_COL_PLAYER      "Player"
#define STR_UI_COL_CAR         "Car"
#define STR_UI_BEST_LAP        "Best lap"
#define STR_UI_3_LAPS          "3 laps"
#define STR_UI_5_LAPS          "5 laps"
#define STR_UI_7_LAPS          "7 laps"
#define STR_UI_NA              "n/a"
#define STR_UI_SELECT_PLAYER   "Select player"
#define STR_UI_CREATE_PLAYER   "Create player"
#define STR_UI_REMOVE_PLAYER   "Remove player"
#define STR_UI_SORT_BY_SCORE   "Sort by score"
#define STR_UI_SORT_BY_CASH    "Sort by cash"
#define STR_UI_SORT_BY_TIME    "Sort by time"
#define STR_UI_SORT_BY_NAME    "Sort by name"
#define STR_UI_FACE            "Face"
#define STR_UI_CHANGE_PLAYER   "Change player"
#define STR_UI_CONTINUE        "Continue"
#define STR_UI_OK              "Ok"
#define STR_UI_CANCEL          "Cancel"
#define STR_UI_YES             "Yes"
#define STR_UI_NO              "No"
#define STR_UI_PLAYER_NAME     "Player name"
#define STR_UI_REMOVE_ASK      "Do you want to remove current player?"
#define STR_UI_LAST_PLAYER     "Can't remove last player"
#define STR_UI_PLAYER_EXISTS   "Player already exists"
#define STR_UI_CREATE_FAILED   "Unable create player"
#define STR_UI_SAVE_FAILED     "Unable to save player file"
#define STR_UI_COL_SCORE       "Score"
#define STR_UI_COL_CASH        "Cash"
#define STR_UI_COL_TIME        "Time"
#define STR_UI_RANK            "Rank"
#define STR_UI_CURRENT_CAR     "Current car"
#define STR_UI_PLAY_TIME       "Play time"
#define STR_UI_CASH            "Cash"
#define STR_UI_SCORES          "Scores"
#define STR_UI_DEFAULT_NAME    "Player"
#define STR_UI_BACK            "Back"
#define STR_UI_QUIT            "Quit"
#define STR_UI_SELECT_CAR      "Select car"
#define STR_UI_UP_BOOSTER      "Upgrade booster"
#define STR_UI_UP_ENGINE       "Upgrade engine"
#define STR_UI_UP_TIRES        "Upgrade tires"
#define STR_UI_NEXT_SKIN       "Next skin"
#define STR_UI_BUY_CAR         "Buy car"
#define STR_UI_SELL_CAR        "Sell car"
#define STR_UI_UPGRADE         "Upgrade"
#define STR_UI_DOWNGRADE       "Downgrade"
#define STR_UI_YOUR_CASH       "Your cash"
#define STR_UI_CAR             "Car"
#define STR_UI_CUR_UPGRADES    "Current upgrades"
#define STR_UI_UPGRADE_LABELS  "Booster:\nEngine:\nTires:"
#define STR_UI_BOOSTER         "Booster"
#define STR_UI_ENGINE          "Engine"
#define STR_UI_TIRES           "Tires"
#define STR_UI_PRICE           "Price"
#define STR_UI_NOT_AVAILABLE   "Not available"
#define STR_UI_INSTALLED       "INSTALLED"
#define STR_UI_SELL_PART_FOR   "Sell part for"
#define STR_UI_PART_DEFAULT    "Default"
#define STR_UI_BUY_PRICE       "Buy price: %s"
#define STR_UI_SELL_PRICE      "Sell price: %s"
#define STR_UI_CASH_LEFT       "Cash remainder %s"
#define STR_UI_CAN_BUY_CAR     "You can buy this car"
#define STR_UI_NO_MONEY        "Not enough money"
#define STR_UI_HAVE_UPGRADE    "You already have this upgrade"
#define STR_UI_BUY_PREV        "You shoud buy previous upgrade"
#define STR_UI_NO_UPGRADE      "You don't have this upgrade"
#define STR_UI_SELL_PREV       "You have to sell\nprevious upgrade first!"
#define STR_UI_CANT_SELL_CAR   "This operation is impossible.\nYou'll not be able to buy any car."
#define STR_UI_BUY_CAR_ASK     "Do you really want to buy car"
#define STR_UI_SELL_CAR_ASK    "Do you want to sell car and upgrades?\ncar: %s, details: %s"
#define STR_UI_BUY_UP_ASK      "Do you want to buy upgrade"
#define STR_UI_MULTIPLAYER     "Multiplayer"
#define STR_UI_CREATE_GAME     "Create game"
#define STR_UI_JOIN_GAME       "Join game"
#define STR_UI_WAIT_PLAYERS    "Wait players"
#define STR_UI_DISCONNECT      "Disconnect"
#define STR_UI_CAR_SETUP       "Car setup"
#define STR_UI_CAR_RESTR       "Car restrictions"
#define STR_UI_KICK_PLAYER     "Kick player off"
#define STR_UI_N_LAPS_SHORT    "N laps"
#define STR_UI_MAP             "Map"
#define STR_UI_CANT_KICK_SELF  "You can't kick yourself"
#define STR_UI_COL_BOOST       "Boost"
#define STR_UI_COL_ENGINE      "Engine"
#define STR_UI_COL_TIRES       "Tires"
#define STR_UI_COL_STATUS      "Status"
#define STR_UI_READY           "ready"
#define STR_UI_NOT_READY       "not ready"
#define STR_UI_DISCONNECT_ASK  "Do you really want to disconnect?"
#define STR_UI_CAR_TYPE        "Car type"
#define STR_UI_CAR_ENABLED     "Car enabled"
#define STR_UI_RESTR_DISABLE   "Disable"
#define STR_UI_LEVEL_1         "Level 1"
#define STR_UI_LEVEL_2         "Level 2"
#define STR_UI_LEVEL_3         "Level 3"
#define STR_UI_BOOSTER_LBL     "Booster:"
#define STR_UI_ENGINE_LBL      "Engine:"
#define STR_UI_TIRES_LBL       "Tires:"
#define STR_UI_SERVER          "Server"
#define STR_UI_CONNECTING      "Connecting...\nPlease wait"
#define STR_UI_PLEASE_WAIT     "Please wait"
#define STR_UI_CONNECT_ERR     "Connecting error\nSorry :)"
#define STR_UI_CONN_LOST       "Connection lost"
#define STR_UI_KICKED_OFF      "You were kicked off from game"
#define STR_NET_CONNECTED      ">%s connected to server"
#define STR_NET_DISCONNECTED   ">%s disconnected from server"
#define STR_NET_KICKED         ">%s is kicked off by server"
#define STR_NET_RESTR          ">Car restrictions are changed"
#define STR_NET_MAP            ">Map is changed to: %s"
#define STR_NET_LAPS           ">Number of laps is changed to: %d"
#define STR_NET_READY          ">%s ready"
#define STR_NET_FINISHED       ">%s has finished"
#define STR_UI_CHAMPIONSHIP    "Championship"
#define STR_UI_NEW_CHAMPIONSHIP "New championship"
#define STR_UI_TRAINING        "Training"
#define STR_UI_COL_TRACK       "Track"
#define STR_UI_COL_SCORES_REQ  "Scores req."
#define STR_UI_COL_COST        "Cost"
#define STR_UI_COL_PLACE       "Place"
#define STR_UI_COL_PRIZE       "Prize"
#define STR_UI_DASH            "---"
#define STR_UI_CH_NOT_STARTED  "Not started"
#define STR_UI_CH_PREV_RESULT  "Previous race result %s"
#define STR_UI_CH_NO_SCORES    "Not enough scores"
#define STR_UI_CH_WIN_ALL      "Win on all tracks to gain access"
#define STR_UI_CH_SCORES_FEE   "Scores required %i; Fee payment %s."
#define STR_UI_CH_PRIZES       "Prize money: 1st %s 2nd %s 3rd %s"
#define STR_UI_CH_LOCKED_SCORES "You don't have access to this track\nNot enough scores"
#define STR_UI_CH_LOCKED_WIN   "You don't have access to this track\nWin on all tracks to gain access"
#define STR_UI_CH_NEW_ASK      "Do you want to start new championship?"
#define STR_UI_CH_ERASE_ASK    "Warning! Do you really want to erase\ndata and start new championship?"
#define STR_UI_CH_CANT_START   "Unable to start race"
#define STR_UI_CH_PAY          "You are to pay"
#define STR_UI_CH_REMAINDER    "remainder will be"
#define STR_UI_CH_TRACK        "Track"
#define STR_UI_CH_PRIZE        "Prize"
#define STR_UI_CH_POINTS       "points   "
#define STR_UI_CH_LEVEL        "level %i"
#define STR_UI_CH_NONE         "none"
#define STR_UI_PLACE_1         "1st"
#define STR_UI_PLACE_2         "2nd"
#define STR_UI_PLACE_3         "3rd"
#define STR_UI_PLACE_4         "4th"
#define STR_UI_PLACE_5         "5th"
#define STR_UI_PLACE_6         "6th"
#define STR_UI_PRIZE_CASH      "Prize cash"
#define STR_UI_RACE_SCORE      "Race score"
#define STR_UI_HIT_BONUS       "Hit bonus (%i hits):"
#define STR_UI_GAP_BONUS       "Gap bonus (%i sec):"
#define STR_UI_MAX_BONUS       "Max bonus allowed: %s"
#define STR_UI_NO_PRIZE        "No prize money"

#endif /* STR_DATA_H */
