/* Generated by rccars_re/gen_tracks.py -- do not edit.
 *
 * The race start of each track, read from its own Players/Player
 * instance. `yaw` is the .sb Euler Y and goes straight into
 * rbcar_init: both conventions map local +Z to (sin y, 0, cos y).
 * `y` is the marker height, used only as the ceiling for the
 * runtime ground probe so a pier is not mistaken for the sand
 * under it.
 *
 * `ambient` is the track's own sound bed, read from its single
 * global MOD_SNDCHANNEL (`ground_noise_snd`). sfx.c loops it
 * non-positionally, which is what its zero radii mean. */
#ifndef TRACKS_H
#define TRACKS_H

typedef struct {
    const char *name;      /* menu label */
    const char *base;      /* assets/<base>.vsc and .col */
    float x, y, z;         /* race start, world space */
    float yaw;             /* degrees, straight into rbcar_init */
    int   car;             /* 0 Overkill, 1 Buggy, 2 Hummer */
    const char *ambient;   /* bank sound for the ambient bed */
} track_info;

#define N_TRACKS 10

static const track_info TRACKS[N_TRACKS] = {
    { "Beach 1", "beach_1", -9.03305f, 0.30800f, -55.57899f, 13.37994f, 0, "noise1" },
    { "Beach 2", "beach_2", 67.64058f, 3.55975f, -6.55663f, -87.16467f, 0, "noise1" },
    { "Beach 3", "beach_3", -36.69868f, 9.03599f, -51.98118f, -103.08044f, 0, "noise1" },
    { "Beach 4", "beach_4", 43.66217f, 5.87600f, -15.96085f, 29.43036f, 0, "noise1" },
    { "Country 1", "country_1", 21.99630f, -1.48880f, -40.57381f, -173.54994f, 0, "noise2" },
    { "Country 2", "country_2", 1.73054f, 5.15000f, 12.94670f, -40.81500f, 0, "noise3" },
    { "Country 3", "country_3", 33.88171f, 2.81600f, -32.51354f, -112.28996f, 0, "noise1" },
    { "Country 4", "country_4", -14.59037f, 2.20400f, 64.12112f, -170.93951f, 0, "noise4" },
    { "Urban 1", "urban_1", -70.97053f, 4.38000f, -24.32026f, -5.67020f, 0, "noise1" },
    { "Urban 2", "urban_2", -2.70602f, -0.05800f, -1.08644f, 89.10095f, 0, "noise4" },
};

#endif
