/*
 * ui.h -- immediate-mode text and panels for the in-game menu.
 *
 * The engine is Direct3D 8 fixed-function and vitaGL gives us the OpenGL 1.x
 * equivalent, so this is plain client-array quads: no shaders, nothing that the
 * rest of the renderer does not already rely on.
 *
 * Colour arrives per vertex through GL_COLOR_ARRAY rather than glColor4f,
 * because the scene renderer already drives everything through client arrays
 * and that path is known to work on this vitaGL build.
 *
 * The font here is compiled in (font.h, generated by rccars_re/gen_font.py),
 * because a menu that cannot load is worse than one that cannot be restyled --
 * font.h is in the binary and no asset has to come up for the START menu to
 * work.
 *
 * THIS FILE USED TO SAY "the game ships no reusable glyph atlas -- Faces/ and
 * FacesSys/ are avatar portraits and Interface.sb has only dialog skins", AND
 * THAT WAS WRONG. The engine has two fonts and they are in `Language/English/`:
 * `Smash20.csi` and `Smash26.csi`, 90 glyphs each on a 10 x 9 atlas, with the
 * character order in a matching `.dat` and the metrics in
 * `Settings/smash20.ini` / `smash26.ini`. The claim was made over
 * `Textures.1/2/3` and `Interface.sb` and never re-checked against the one
 * directory that had it -- see traps.md, "A DOCUMENTED NEGATIVE IS STILL A
 * CLAIM". race_ui.c draws the in-race HUD's numbers in the engine's own letters;
 * this file's baked Consolas stays, for the reason above.
 */

#ifndef UI_H
#define UI_H

/* The most quads ui_arc will cut a sweep into. MAX_VTX in ui.c bounds it too;
   this is the readable bound, and 64 over a 161 degree sweep is 2.5 degrees a
   quad, which on a 92 px radius is a 4 px chord. */
#define UI_ARC_MAX_SEGS 64

/* Uploads the font atlas. Call once, after the GL context exists. */
void  ui_init(void);

/* Bracket all UI drawing. ui_begin switches to a pixel-space ortho projection
   with the origin top-left, turns on blending and turns off depth, alpha test
   and culling; ui_end puts every one of those back. */
void  ui_begin(int screen_w, int screen_h);
void  ui_end(void);

void  ui_rect(float x, float y, float w, float h,
              float r, float g, float b, float a);
void  ui_text(float x, float y, float scale,
              float r, float g, float b, float a, const char *s);

/* One textured quad from an arbitrary texture, with an explicit UV rect so a
   caller can take one cell out of an atlas -- which is what the game's own
   on-screen messages are (msg_hits holds two of them, one per half). `tex` is a
   GLuint; it is spelt unsigned int here so ui.h stays free of the GL headers,
   the way the rest of this interface is. A tex of 0 draws nothing rather than
   binding the default texture, because an unbound sampler is undefined on this
   GPU (see BATCH_NO_TEXTURE in scene.h). */
void  ui_image(float x, float y, float w, float h, unsigned int tex,
               float u0, float v0, float u1, float v1,
               float r, float g, float b, float a);

/* ONE QUAD WITH FOUR ARBITRARY CORNERS, in the order (x0,y0) (x1,y0-ish)
   (x1,y1) (x0,y1) -- i.e. going round, not a Z. Needed because the minimap
   panel's own shape is a strip of TRAPEZOIDS: the engine's outline table
   (0x56db70) is four rows of two points at four different widths, and an
   axis-aligned rect cannot express the clipped corners. `tex` 0 draws
   untextured, the way ui_rect does. */
void  ui_image_quad(const float x[4], const float y[4],
                    const float u[4], const float vv[4],
                    unsigned int tex, float r, float g, float b, float a);

/* ONE QUAD, ROTATED ABOUT ITS OWN CENTRE. (x, y) is the centre rather than a
   corner, because that is what a rotation is about; `ang` is radians, positive
   clockwise on screen, which is the sense a screen-space heading turns in with
   Y running down. The minimap's car marker is the reason this exists -- an arrow
   that does not point where the car points is not an arrow. */
void  ui_image_rot(float cx, float cy, float w, float h, float ang,
                   unsigned int tex,
                   float u0, float v0, float u1, float v1,
                   float r, float g, float b, float a);

/* AN ANNULAR SECTOR of a texture, as a triangle strip: the band between radii
   `r0` and `r1` about (cx, cy), swept from `a0` to `a1` radians, textured by
   sampling the SAME ring out of the texture -- centre (cu, cv), radii `tr0` and
   `tr1` in texture units. Angles are measured with zero straight UP and positive
   clockwise, which is the convention cockpit.ini's indicatorAngMin/Max are in.
   `segs` is how many quads the sweep is cut into. `tex_mirror` negates the
   texture's own angle about `cu`, so a caller drawing the mirrored dial can
   sweep the SCREEN the other way round while still sampling the art where the
   art actually is -- the red arc is not symmetric, so reflecting the sample
   point as well would read grey.

   The gauges are what this is for: a partial reveal of cockpit_sp2's red ring
   over cockpit_sp1's gold track. A quad with a UV rect cannot express it, and
   bending ui_image into a polar mode would put a branch in the one function
   every other caller shares. */
void  ui_arc(float cx, float cy, float r0, float r1, float a0, float a1,
             int segs, unsigned int tex,
             float cu, float cv, float tr0, float tr1, int tex_mirror,
             float r, float g, float b, float a);

/* Layout helpers, in the same pixel space. */
float ui_text_w(float scale, const char *s);
float ui_text_h(float scale);

#endif
