/*
 * ui.h -- immediate-mode text and panels for the in-game menu.
 *
 * The engine is Direct3D 8 fixed-function and vitaGL gives us the OpenGL 1.x
 * equivalent, so this is plain client-array quads: no shaders, nothing that the
 * rest of the renderer does not already rely on.
 *
 * Colour arrives per vertex through GL_COLOR_ARRAY rather than glColor4f,
 * because the scene renderer already drives everything through client arrays
 * and that path is known to work on this vitaGL build.
 *
 * The font is compiled in (font.h, generated by rccars_re/gen_font.py). The game
 * ships no reusable glyph atlas -- Faces/ and FacesSys/ are avatar portraits and
 * Interface.sb has only dialog skins -- and a menu that cannot load is worse
 * than one that cannot be restyled.
 */

#ifndef UI_H
#define UI_H

/* Uploads the font atlas. Call once, after the GL context exists. */
void  ui_init(void);

/* Bracket all UI drawing. ui_begin switches to a pixel-space ortho projection
   with the origin top-left, turns on blending and turns off depth, alpha test
   and culling; ui_end puts every one of those back. */
void  ui_begin(int screen_w, int screen_h);
void  ui_end(void);

void  ui_rect(float x, float y, float w, float h,
              float r, float g, float b, float a);
void  ui_text(float x, float y, float scale,
              float r, float g, float b, float a, const char *s);

/* One textured quad from an arbitrary texture, with an explicit UV rect so a
   caller can take one cell out of an atlas -- which is what the game's own
   on-screen messages are (msg_hits holds two of them, one per half). `tex` is a
   GLuint; it is spelt unsigned int here so ui.h stays free of the GL headers,
   the way the rest of this interface is. A tex of 0 draws nothing rather than
   binding the default texture, because an unbound sampler is undefined on this
   GPU (see BATCH_NO_TEXTURE in scene.h). */
void  ui_image(float x, float y, float w, float h, unsigned int tex,
               float u0, float v0, float u1, float v1,
               float r, float g, float b, float a);

/* Layout helpers, in the same pixel space. */
float ui_text_w(float scale, const char *s);
float ui_text_h(float scale);

#endif
