/*
 * vis_data.h -- constants for the port's visual subsystems, generated by
 * rccars_re/gen_vis_data.py from the game's own slider and config files.
 *
 * DO NOT EDIT. Regenerate with:
 *     python3 rccars_re/gen_vis_data.py
 *
 * Every conversion is the one the matching loader performs; see the script's
 * docstring for the function each came from. The sea surface is per track --
 * see WSURF[] below.
 */

#ifndef VIS_DATA_H
#define VIS_DATA_H

/* ---- car shadow: FUN_004f9aa0 (CarRender), used by FUN_005072f0 ---- */

/* radius of the projected shadow, metres, per car (1 Overkill,
   2 Buggy, 3 Hummer). shdAddSource's `radius` argument. */
#define SHADOW_SIZE   { 0.360000f, 0.290000f, 0.420000f }
/* offset of the shadow centre along the body's +Z (forward). */
#define SHADOW_SHIFT  { 0.000000f, 0.000000f, 0.010000f }

#define SHADOW_DENSITY             34   /* 0..255, the shadow's alpha */
#define SHADOW_TEX_SIZE            256   /* TextureSizePow2, the render-target edge */
#define SHADOW_FRAME_SKIP          0   /* regenerate the shadow texture every n+1 frames */
#define SHADOW_FILTER_SPEED        201   /* FilterSpeed */
#define LIGHT_AZIMUTH_DEG          0.000000f   /* CarLight AngleAzimuth */
#define LIGHT_ELEVATION_DEG        75.000000f   /* CarLight AngleElevation */
#define LIGHT_AMBIENT              138   /* CarLight AmbientI */
#define LIGHT_DIRECT               128   /* CarLight DirectI */

/* ---- the car's own light: carVisualBody 0x005077e0, and the LOD fade ---- */

#define LIGHT_FADE_NEAR            2.000000f   /* LOD DistLOD1SwitchOn: full lighting closer than this, metres */
#define LIGHT_FADE_FAR             4.303030f   /* + Delta12: flat (ambient 255, no light) beyond this */

/* ---- car_lmshd: the lightmap under the wheels (FUN_00531ff0 / FUN_005323a0) ---- */

#define LIGHT_LM_ALPHAVEL          1.270000f   /* car_lmshd alphavel/100: light level chase, per second */
#define LIGHT_LM_DELTA             0.050000f   /* deltaalpha/100: dead band, below which nothing moves */
#define LIGHT_LM_MAXDIST           25.000000f   /* maxdist: no camera within this of the car -> level 1.0, metres */
/* Splines/light_car.bspl: lightmap brightness (0..255) -> the
   car's light level (0..255). Clamped piecewise linear, the
   engine's own 0x0040f830 -- so 0.623 at or below 112.6 and
   1.019 at or above 200.9, a line between. Which is why a tunnel
   darkens the car by a bit over a third and no more. */
#define LIGHT_LM_CURVE_N 2
#define LIGHT_LM_CURVE { {112.565773f, 158.859390f}, {200.891724f, 259.951721f} }

/* ---- checkpoint markers: FUN_0052b370 (anim_cp), drawn by FUN_0052abc0 ---- */

#define CP_SIZE                    1.460000f   /* half-extent of the billboard quad, metres */
#define CP_SHIFT                   1.280000f   /* lift above the checkpoint centroid, metres */
#define CP_MIN_DIST                2.370000f   /* fully opaque closer than this */
#define CP_MAX_DIST                9.000000f   /* invisible beyond this */
#define CP_BLINK_DELTA             0.100000f   /* seconds per animation frame (3 frames) */

/* ---- coast foam band: FUN_0051cef0 (WaterLOD_Coast) ---- */

#define COAST_HEIGHT_ON            0.000000f   /* metres */
#define COAST_HEIGHT_OFF           -0.320000f   /* metres */
#define COAST_SCROLL_VEL           0.110000f   /* UV per second */
#define COAST_ALPHA_MIN            0.141176f   /* 0..1 */
#define COAST_ALPHA_MAX            1.000000f   /* 0..1 */
#define COAST_ACTIVE_RAD           100.000000f   /* metres */

/* ---- stream: FUN_00523a10 (WaterLOD_Stream) ---- */

#define STREAM_SCROLL_VEL          0.890000f   /* UV per second */
#define STREAM_NOISE               0.080000f   /*  */
#define STREAM_POOL_NOISE_LEN      0.010000f   /*  */
#define STREAM_POOL_NOISE_FREQ     1.550000f   /*  */

/* ---- stream / waterfall / pool: the node table at 0x575710 -------------
 *
 * NOT a config section -- a static table of three entries in the exe, scanned
 * per node by 0x523760. read_surface_table cites the instruction behind every
 * field; what matters here is +0x34, which 0x523866 writes into EVERY vertex
 * colour of the matched surface as `0xffffff | (alpha << 24)`. White at a flat
 * opacity: that single byte is the whole of what makes one of these three a
 * body of water rather than a textured slab, and the three do not agree.
 *
 * The port used to have one number, 0.55, for all of them, marked "NOT
 * recovered" -- which turns out to be the WATERFALL'S value, and it was never
 * applied to a pool at all because pools were not classified. */

#define STREAM_VERTEX_ALPHA        0.470588f   /* `stream`, raw 120/255 at +0x34 */
#define FALL_VERTEX_ALPHA          0.549020f   /* `wtr_fall`, raw 140/255 at +0x34 */
#define POOL_VERTEX_ALPHA          0.431373f   /* `pool`, raw 110/255 at +0x34 */

/* Does this kind scroll its UVs (+0x20)? A pool does not: its
   entry sets the NOISE flag at +0x24 instead, so it shimmers in
   place. The noise field itself is the one part of the entry the
   port does not transcribe -- see water_draw. */
#define STREAM_SCROLLS             1   /* +0x20 */
#define FALL_SCROLLS               1   /* +0x20 */
#define POOL_SCROLLS               0   /* +0x20 */

/* ---- shore wave spawner: FUN_00525c10 (WaterLOD_Wave) ---- */

#define WAVE_TIME_LONG             2.000000f   /* seconds between long-lived waves */
#define WAVE_TIME_SHORT            0.500000f   /* seconds between short-lived waves */
#define WAVE_SPAWN_ANGLE           5.000000f   /* degrees of spread around the marker's facing */
#define WAVE_SPAWN_LEN             3.500000f   /* metres the wave travels */
#define WAVE_ACTIVE_RAD            40.000000f   /* metres */

/* ---- shore wave sprite: FUN_0052a550 (Water_Wave_New), drawn by FUN_0052a030.
   Every key goes through FUN_00532410, which is `cfgGetInt(...) / 100`. ---- */

#define WAVE_LIFE_LONG             3.500000f   /* seconds */
#define WAVE_LIFE_SHORT            1.000000f   /* seconds */
#define WAVE_LIFE_SHORT_DISP       0.250000f   /* seconds of random spread on the short life */
#define WAVE_SPEED                 1.450000f   /* m/s */
#define WAVE_LEN                   1.700000f   /* half-length of the quad along the crest */
#define WAVE_HEIGHT                0.300000f   /* crest height scale */
#define WAVE_DHEIGHT               -0.050000f   /* DHeight-1: the vertical lift applied to the whole quad */
#define WAVE_ANIM_SPEED            7.230000f   /* UV per second */
#define WAVE_ANIM_WAIT             0.100000f   /* seconds */
#define WAVE_DEC_TIME              0.670000f   /* fraction of life spent fading out */
#define WAVE_INC_TIME              0.330000f   /* fraction of life spent fading in */

/* ---- the sea surface: FUN_00521540 loads it, FUN_005240c0 evaluates it -----
 *
 * Per surface vertex, with the projections FUN_0051c000 precomputes at load:
 *
 *     phi1 = (t*speed + x*cos(angle) + z*sin(angle)) * period
 *     phi2 =  t*period2 + |(x,z) - (posX,posZ)| / length2
 *     damp = clamp01(depth / magnetRadius)
 *     y    = restY + offset + (1 - damp)*magnetOffset
 *                  + damp * ( amp*(0.25 + 0.75*sin phi1) + amp2*sin phi2 )
 *
 * So `period` is a SPATIAL frequency in rad/m -- wavelength 2*pi/period -- and
 * the time term rides on speed*period, which leaves speed as the phase speed in
 * m/s. Wave two is RADIAL about (posX, posZ) with wavelength 2*pi*length2.
 * `speed2` and `angle2` are loaded and FUN_005240c0 never reads them; angle2's
 * projection is precomputed all the same, so both are carried here.
 *
 * `amp` and `amp2` are HEIGHTS, in metres, and both are read: the key string at
 * 0x5756e0 is "amp" and the loader puts it in param_2[8], "amp2" at 0x5756c0
 * goes to param_2[9]. The 1/amp2 stored beside it is not a sign that amp2 is a
 * divisor -- it is used at 0x51c71d to normalise the coast foam's signal back
 * to unit amplitude. The amp term is deliberately asymmetric: 0.25 + 0.75*sin
 * spans -0.5..+1.0, so crests stand twice as far above the mean as troughs fall
 * below it, which is what a swell does.
 *
 * The steepness these produce is the check that the units are read right: every
 * track lands between 2 and 9 per cent, and real swell breaks past about 14.
 * Reading `period` as a time instead put two of the five past breaking.
 *
 * magnetOffset/magnetRadius are the shallow-water block. Both conversions are
 * unobvious and neither is raw*0.01: magnetOffset is raw*0.01 - 0.5, so the
 * shipped raw 50 is exactly ZERO on every track and there is no shore lift at
 * all; magnetRadius is raw*0.05, so the shipped raw 51 is 2.55 m of DEPTH over
 * which the swell fades to flat -- five times the 0.5 m the port had guessed.
 *
 * NOT here, and each for its own reason:
 *   texScaleX/Z  the world-to-UV rate the engine tessellates its own grid with
 *                (raw*0.1). The port ships authored tiles that carry their own
 *                UVs, so there is nothing for it to scale.
 *   alphaPow     conversion known -- raw*0.2 - 10, stored as -1/that, so the
 *                shipped raw 60 is -0.5 -- but the code that consumes it is not
 *                transcribed, and -0.5 is not an exponent water.c could use.
 *                The port's own depth ramp keeps its own constant, in water.h.
 *
 * The section is PER TRACK (WLOD_<track>_more1); the ones that ship one are the
 * four beaches and country_3, and beach_2 also ships a .crs override. A track
 * without one falls back to WaterLOD, whose amp and amp2 are both 0 -- and
 * every track that falls back has no sea surface at all. ---- */

#define WSURF_N_TRACKS 10

typedef struct {
    const char *track;         /* tracks.h's base name, for the index check */
    const char *section;       /* the config section this row was read from */
    float angle_deg, speed, period;              /* wave 1, directional */
    float angle2_deg, speed2, period2, length2;  /* wave 2, radial */
    float amp, amp2;                             /* metres */
    float offset, magnet_offset, magnet_radius;  /* metres */
    float pos_x, pos_z;                          /* the radial wave's centre */
    float tex_rad_min, tex_rad_max;              /* UV, the orbit's radius */
    float tex_speed_min, tex_speed_max;          /* degrees per second */
    float alpha_min, alpha_max;                  /* 0..1 */
} wsurf_t;

static const wsurf_t WSURF[WSURF_N_TRACKS] = {
    { "beach_1", "WLOD_beach_1_more1",
      60.000000f, 2.060000f, 0.600000f,
      40.000000f, 1.970000f, 1.800000f, 1.610000f,
      0.160000f, 0.250000f,
      -0.370000f, 0.000000f, 2.550000f,
      -47.000000f, 3.000000f,
      0.000000f, 0.030000f,
      46.800000f, 100.800000f,
      0.101961f, 1.000000f },
      /* swell 0.740 m peak to peak; wavelengths 10.5 m and 10.1 m, steepness 0.023 and 0.049 */
    { "beach_2", "WLOD_beach_2_more1",
      60.000000f, 2.060000f, 0.900000f,
      40.000000f, 1.970000f, 1.500000f, 1.610000f,
      0.370000f, 0.280000f,
      0.000000f, 0.000000f, 2.550000f,
      -473.000000f, -419.000000f,
      0.000000f, 0.030000f,
      46.800000f, 100.800000f,
      0.101961f, 1.000000f },
      /* swell 1.115 m peak to peak; wavelengths 7.0 m and 10.1 m, steepness 0.079 and 0.055 */
    { "beach_3", "WLOD_beach_3_more1",
      90.000000f, 1.920000f, 1.400000f,
      40.000000f, 4.090000f, 1.200000f, 1.240000f,
      0.250000f, 0.200000f,
      -0.070000f, 0.000000f, 2.550000f,
      -26.000000f, -73.000000f,
      0.000000f, 0.030000f,
      46.800000f, 100.800000f,
      0.101961f, 1.000000f },
      /* swell 0.775 m peak to peak; wavelengths 4.5 m and 7.8 m, steepness 0.084 and 0.051 */
    { "beach_4", "WLOD_beach_4_more1",
      170.000000f, 2.060000f, 1.200000f,
      40.000000f, 1.970000f, 1.800000f, 1.610000f,
      0.120000f, 0.120000f,
      -0.020000f, 0.000000f, 2.550000f,
      23.000000f, 36.000000f,
      0.000000f, 0.030000f,
      46.800000f, 100.800000f,
      0.101961f, 1.000000f },
      /* swell 0.420 m peak to peak; wavelengths 5.2 m and 10.1 m, steepness 0.034 and 0.024 */
    { "country_1", "WaterLOD",
      60.000000f, 3.150000f, 0.100000f,
      40.000000f, 2.670000f, 0.300000f, 1.610000f,
      0.000000f, 0.000000f,
      -0.500000f, 0.000000f, 2.550000f,
      0.000000f, 0.000000f,
      0.010000f, 0.030000f,
      90.000000f, 270.000000f,
      0.101961f, 1.000000f },
      /* swell 0.000 m peak to peak; wavelengths 62.8 m and 10.1 m, steepness 0.000 and 0.000 */
    { "country_2", "WaterLOD",
      60.000000f, 3.150000f, 0.100000f,
      40.000000f, 2.670000f, 0.300000f, 1.610000f,
      0.000000f, 0.000000f,
      -0.500000f, 0.000000f, 2.550000f,
      0.000000f, 0.000000f,
      0.010000f, 0.030000f,
      90.000000f, 270.000000f,
      0.101961f, 1.000000f },
      /* swell 0.000 m peak to peak; wavelengths 62.8 m and 10.1 m, steepness 0.000 and 0.000 */
    { "country_3", "WLOD_country_3_more1",
      60.000000f, 1.800000f, 1.900000f,
      40.000000f, 1.970000f, 1.800000f, 1.610000f,
      0.200000f, 0.290000f,
      -0.080000f, 0.000000f, 2.550000f,
      -73.000000f, -17.000000f,
      0.000000f, 0.030000f,
      46.800000f, 100.800000f,
      0.101961f, 1.000000f },
      /* swell 0.880 m peak to peak; wavelengths 3.3 m and 10.1 m, steepness 0.091 and 0.057 */
    { "country_4", "WaterLOD",
      60.000000f, 3.150000f, 0.100000f,
      40.000000f, 2.670000f, 0.300000f, 1.610000f,
      0.000000f, 0.000000f,
      -0.500000f, 0.000000f, 2.550000f,
      0.000000f, 0.000000f,
      0.010000f, 0.030000f,
      90.000000f, 270.000000f,
      0.101961f, 1.000000f },
      /* swell 0.000 m peak to peak; wavelengths 62.8 m and 10.1 m, steepness 0.000 and 0.000 */
    { "urban_1", "WaterLOD",
      60.000000f, 3.150000f, 0.100000f,
      40.000000f, 2.670000f, 0.300000f, 1.610000f,
      0.000000f, 0.000000f,
      -0.500000f, 0.000000f, 2.550000f,
      0.000000f, 0.000000f,
      0.010000f, 0.030000f,
      90.000000f, 270.000000f,
      0.101961f, 1.000000f },
      /* swell 0.000 m peak to peak; wavelengths 62.8 m and 10.1 m, steepness 0.000 and 0.000 */
    { "urban_2", "WaterLOD",
      60.000000f, 3.150000f, 0.100000f,
      40.000000f, 2.670000f, 0.300000f, 1.610000f,
      0.000000f, 0.000000f,
      -0.500000f, 0.000000f, 2.550000f,
      0.000000f, 0.000000f,
      0.010000f, 0.030000f,
      90.000000f, 270.000000f,
      0.101961f, 1.000000f },
      /* swell 0.000 m peak to peak; wavelengths 62.8 m and 10.1 m, steepness 0.000 and 0.000 */
};


/* ---- the whip antenna: FUN_00500230 (Antenna_Car<n>).
   A chain of nPoints masses, chainLength long in TOTAL -- the loader
   divides by nPoints-1 to get the segment length. Every scalar is
   raw*0.01 clamped at 10, which is why stiffness's raw 2000 lands on
   10.0 and not 20.0. ---- */

/* car 1 */
#define ANT1_POINTS                4   /* chain masses */
#define ANT1_LENGTH                0.250000f   /* metres, total */
#define ANT1_SEG                   0.083333f   /* metres per segment */
#define ANT1_MASS                  0.250000f   /*  */
#define ANT1_STIFFNESS             10.000000f   /* raw 2000 clamps to 10 */
#define ANT1_DAMPING               1.160000f   /*  */
#define ANT1_WIND                  4.600000f   /*  */
#define ANT1_VOLUME                0.030000f   /*  */

/* car 2 */
#define ANT2_POINTS                4   /* chain masses */
#define ANT2_LENGTH                0.350000f   /* metres, total */
#define ANT2_SEG                   0.116667f   /* metres per segment */
#define ANT2_MASS                  0.290000f   /*  */
#define ANT2_STIFFNESS             10.000000f   /* raw 2000 clamps to 10 */
#define ANT2_DAMPING               1.160000f   /*  */
#define ANT2_WIND                  4.600000f   /*  */
#define ANT2_VOLUME                0.030000f   /*  */

/* car 3 */
#define ANT3_POINTS                4   /* chain masses */
#define ANT3_LENGTH                0.250000f   /* metres, total */
#define ANT3_SEG                   0.083333f   /* metres per segment */
#define ANT3_MASS                  0.200000f   /*  */
#define ANT3_STIFFNESS             10.000000f   /* raw 2000 clamps to 10 */
#define ANT3_DAMPING               1.160000f   /*  */
#define ANT3_WIND                  4.600000f   /*  */
#define ANT3_VOLUME                0.030000f   /*  */


/* ---- the sun and its lens flare: FUN_00479b70 loads
   Settings/LENS_FLARE, FUN_00478fd0 places it, FUN_00479070
   builds the disc, FUN_00479250 the ghost chain and
   FUN_004797c0 draws all five sprites.

   The sun's WORLD POSITION is not here -- it is the SUN_AF
   marker in each track's own .sb, which pack_vsc.py exports.
   Eight tracks have one; urban_1 and urban_2 do not, and the
   original draws no sun on those two. ---- */

#define SUN_SIZE                   0.050000f   /* SizeSun, a fraction of the viewport half-width */
#define SUN_COLOR_R                255   /* ColorRSun, 0..255 */
#define SUN_COLOR_G                255   /* ColorGSun */
#define SUN_COLOR_B                188   /* ColorBSun */
#define SUN_RAY_PERIOD             0.500000f   /* TimeShootRay: seconds between line-of-sight casts */
#define SUN_FADE_TIME              0.250000f   /* FadeTime: seconds to fade the flare in or out */
#define SUN_CAM_OFFSET             0.000000f   /* CamOffset: added to the camera's focal distance */

/* The four lens GHOSTS, in FUN_00479250's own order: a point
   `Dist` metres from the view centre along the line to the sun,
   at the camera's focal depth. Negative is the far side of the
   centre from the sun -- which is what a lens ghost does. */
#define SUN_DIST1                  -0.050000f   /* Dist1, negated at 0x00479c3a */
#define SUN_DIST2                  -0.020000f   /* Dist2, negated at 0x00479c5d */
#define SUN_DIST3                  0.040000f   /* Dist3 */
#define SUN_DIST4                  0.110000f   /* Dist4 */

/* The five SPRITE sizes and colours. Sprite 5 sits on the sun
   itself and is the `shine`; 2 and 4 are left white by the
   loader (0x00479ce6 onward writes 0xff into those slots), which
   is why only 1 and 3 have keys. */
#define SUN_FLARE_SIZE1            0.450000f   /* Size1 */
#define SUN_FLARE_SIZE2            0.030000f   /* Size2 */
#define SUN_FLARE_SIZE3            0.100000f   /* Size3 */
#define SUN_FLARE_SIZE4            0.020000f   /* Size4 */
#define SUN_FLARE_SIZE5            0.500000f   /* Size5 */
#define SUN_FLARE_RGB1           200, 255, 201   /* ColorR1/G1/B1 */
#define SUN_FLARE_RGB2           255, 255, 255   /* not a key: the loader writes 0xff */
#define SUN_FLARE_RGB3           171, 255, 170   /* ColorR3/G3/B3 */
#define SUN_FLARE_RGB4           255, 255, 255   /* not a key: the loader writes 0xff */
#define SUN_FLARE_RGB5           255, 255, 255   /* not a key: the loader writes 0xff */

/* Settings/Sky.crs, one key, and no consumer recovered. */
#define SKY_HOR_ANGLE_RAW          3   /* horAngle, raw 0..100 -- conversion and consumer unknown */

#endif /* VIS_DATA_H */
