/*
 * vis_data.h -- constants for the port's visual subsystems, generated by
 * rccars_re/gen_vis_data.py from the game's own slider and config files.
 *
 * DO NOT EDIT. Regenerate with:
 *     python3 rccars_re/gen_vis_data.py
 *
 * Every conversion is the one the matching loader performs; see the script's
 * docstring for the function each came from. Water surface section: WLOD_beach_1_more1.
 */

#ifndef VIS_DATA_H
#define VIS_DATA_H

/* ---- car shadow: FUN_004f9aa0 (CarRender), used by FUN_005072f0 ---- */

/* radius of the projected shadow, metres, per car (1 Overkill,
   2 Buggy, 3 Hummer). shdAddSource's `radius` argument. */
#define SHADOW_SIZE   { 0.360000f, 0.290000f, 0.420000f }
/* offset of the shadow centre along the body's +Z (forward). */
#define SHADOW_SHIFT  { 0.000000f, 0.000000f, 0.010000f }

#define SHADOW_DENSITY             34   /* 0..255, the shadow's alpha */
#define SHADOW_TEX_SIZE            256   /* TextureSizePow2, the render-target edge */
#define SHADOW_FRAME_SKIP          0   /* regenerate the shadow texture every n+1 frames */
#define SHADOW_FILTER_SPEED        201   /* FilterSpeed */
#define LIGHT_AZIMUTH_DEG          0.000000f   /* CarLight AngleAzimuth */
#define LIGHT_ELEVATION_DEG        75.000000f   /* CarLight AngleElevation */
#define LIGHT_AMBIENT              138   /* CarLight AmbientI */
#define LIGHT_DIRECT               128   /* CarLight DirectI */

/* ---- checkpoint markers: FUN_0052b370 (anim_cp), drawn by FUN_0052abc0 ---- */

#define CP_SIZE                    1.460000f   /* half-extent of the billboard quad, metres */
#define CP_SHIFT                   1.280000f   /* lift above the checkpoint centroid, metres */
#define CP_MIN_DIST                2.370000f   /* fully opaque closer than this */
#define CP_MAX_DIST                9.000000f   /* invisible beyond this */
#define CP_BLINK_DELTA             0.100000f   /* seconds per animation frame (3 frames) */

/* ---- coast foam band: FUN_0051cef0 (WaterLOD_Coast) ---- */

#define COAST_HEIGHT_ON            0.000000f   /* metres */
#define COAST_HEIGHT_OFF           -0.320000f   /* metres */
#define COAST_SCROLL_VEL           0.110000f   /* UV per second */
#define COAST_ALPHA_MIN            0.141176f   /* 0..1 */
#define COAST_ALPHA_MAX            1.000000f   /* 0..1 */
#define COAST_ACTIVE_RAD           100.000000f   /* metres */

/* ---- stream: FUN_00523a10 (WaterLOD_Stream) ---- */

#define STREAM_SCROLL_VEL          0.890000f   /* UV per second */
#define STREAM_NOISE               0.080000f   /*  */
#define STREAM_POOL_NOISE_LEN      0.010000f   /*  */
#define STREAM_POOL_NOISE_FREQ     1.550000f   /*  */

/* ---- shore wave spawner: FUN_00525c10 (WaterLOD_Wave) ---- */

#define WAVE_TIME_LONG             2.000000f   /* seconds between long-lived waves */
#define WAVE_TIME_SHORT            0.500000f   /* seconds between short-lived waves */
#define WAVE_SPAWN_ANGLE           5.000000f   /* degrees of spread around the marker's facing */
#define WAVE_SPAWN_LEN             3.500000f   /* metres the wave travels */
#define WAVE_ACTIVE_RAD            40.000000f   /* metres */

/* ---- shore wave sprite: FUN_0052a550 (Water_Wave_New), drawn by FUN_0052a030.
   Every key goes through FUN_00532410, which is `cfgGetInt(...) / 100`. ---- */

#define WAVE_LIFE_LONG             3.500000f   /* seconds */
#define WAVE_LIFE_SHORT            1.000000f   /* seconds */
#define WAVE_LIFE_SHORT_DISP       0.250000f   /* seconds of random spread on the short life */
#define WAVE_SPEED                 1.450000f   /* m/s */
#define WAVE_LEN                   1.700000f   /* half-length of the quad along the crest */
#define WAVE_HEIGHT                0.300000f   /* crest height scale */
#define WAVE_DHEIGHT               -0.050000f   /* DHeight-1: the vertical lift applied to the whole quad */
#define WAVE_ANIM_SPEED            7.230000f   /* UV per second */
#define WAVE_ANIM_WAIT             0.100000f   /* seconds */
#define WAVE_DEC_TIME              0.670000f   /* fraction of life spent fading out */
#define WAVE_INC_TIME              0.330000f   /* fraction of life spent fading in */

/* ---- water surface: FUN_00521540, section WLOD_beach_1_more1.
   The evaluator that consumes these (the WaterLOD tessellator) is NOT
   transcribed, and neither are the surface's AMPLITUDES: the loader
   reads angle/speed/period and their `2` counterparts plus length2, and
   stores 1/amp2 and 1/length2 -- reciprocals, which is what you
   precompute for a divisor. So these give the DIRECTIONS and RATES of
   the two wave trains and nothing about how tall they are. water.c
   therefore uses them for the shoreline foam's on/off signal, whose
   range HeightOn/HeightOff DO pin down, and keeps the surface itself
   nearly flat -- which is what the retail game looks like. ---- */

#define WSURF_ANGLE_DEG            60.000000f   /* raw*10 */
#define WSURF_SPEED                2.060000f   /*  */
#define WSURF_PERIOD               0.600000f   /* seconds */
#define WSURF_ANGLE2_DEG           40.000000f   /* raw*10 */
#define WSURF_SPEED2               1.970000f   /*  */
#define WSURF_PERIOD2              1.800000f   /* seconds */
#define WSURF_LENGTH2              1.610000f   /* metres */
#define WSURF_AMP2                 0.250000f   /* metres */
#define WSURF_OFFSET               -0.370000f   /*  */
#define WSURF_TEX_SCALE_X          0.040000f   /*  */
#define WSURF_TEX_SCALE_Z          0.040000f   /*  */
#define WSURF_TEX_SPEED_MIN        0.130000f   /*  */
#define WSURF_TEX_SPEED_MAX        0.280000f   /*  */
#define WSURF_ALPHA_POW            0.600000f   /* exponent on the depth ramp */
#define WSURF_ALPHA_MIN            0.101961f   /* 0..1 */
#define WSURF_ALPHA_MAX            1.000000f   /* 0..1 */

/* ---- the whip antenna: FUN_00500230 (Antenna_Car<n>).
   A chain of nPoints masses, chainLength long in TOTAL -- the loader
   divides by nPoints-1 to get the segment length. Every scalar is
   raw*0.01 clamped at 10, which is why stiffness's raw 2000 lands on
   10.0 and not 20.0. ---- */

/* car 1 */
#define ANT1_POINTS                4   /* chain masses */
#define ANT1_LENGTH                0.250000f   /* metres, total */
#define ANT1_SEG                   0.083333f   /* metres per segment */
#define ANT1_MASS                  0.250000f   /*  */
#define ANT1_STIFFNESS             10.000000f   /* raw 2000 clamps to 10 */
#define ANT1_DAMPING               1.160000f   /*  */
#define ANT1_WIND                  4.600000f   /*  */
#define ANT1_VOLUME                0.030000f   /*  */

/* car 2 */
#define ANT2_POINTS                4   /* chain masses */
#define ANT2_LENGTH                0.350000f   /* metres, total */
#define ANT2_SEG                   0.116667f   /* metres per segment */
#define ANT2_MASS                  0.290000f   /*  */
#define ANT2_STIFFNESS             10.000000f   /* raw 2000 clamps to 10 */
#define ANT2_DAMPING               1.160000f   /*  */
#define ANT2_WIND                  4.600000f   /*  */
#define ANT2_VOLUME                0.030000f   /*  */

/* car 3 */
#define ANT3_POINTS                4   /* chain masses */
#define ANT3_LENGTH                0.250000f   /* metres, total */
#define ANT3_SEG                   0.083333f   /* metres per segment */
#define ANT3_MASS                  0.200000f   /*  */
#define ANT3_STIFFNESS             10.000000f   /* raw 2000 clamps to 10 */
#define ANT3_DAMPING               1.160000f   /*  */
#define ANT3_WIND                  4.600000f   /*  */
#define ANT3_VOLUME                0.030000f   /*  */


#endif /* VIS_DATA_H */
